<?php if ($this->pageCount): ?>
	<div style="padding-top:20;text-align:center">
		<!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
			<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
				«« Ankstesnis
			</a> |
		<?php else: ?>
			<span class="disabled">«« Ankstesnis</span> |
		<?php endif; ?>

		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
			    <a href="<?php echo $this->url(array('page' => $page)); ?>">
					<?php echo $page; ?>
			    </a> |
			<?php else: ?>
				<?php echo $page; ?> |
			<?php endif; ?>
		<?php endforeach; ?>

		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
			<a href="<?php echo $this->url(array('page' => $this->next)); ?>">
				Sekantis »»
			</a>
		<?php else: ?>
			<span class="disabled">Sekantis »»</span>
		<?php endif; ?>
	</div>
<?php endif; ?>
