<div align="center" style="width:800">
<div style="width:400px"><div class="ui-widget">
<div class="ui-widget ui-state-highlight ui-corner-all" > 
<div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix"><span class="ui-dialog-title" id="ui-dialog-title-login-dialog">
<span style="font-size:20"> Registracija </span></span></div>
<div style="padding: 15px">
<? if($this->errors) {
?>
	<div class="ui-state-error ui-corner-all" style="margin-bottom:20px"><ul class="formError">
<?
	for ($i=0;$i<count($this->errors);$i++) {
?>
		<li><?=$this->errors[$i]["message"];?></li>
<?
	}
?>
</ul></div></div>
<?
}else{
if ($this->success) {
?>
Registracijos patvirtinimui Jums  išsiųstas laiškas nurodytu el. pašto adresu
<?
}
}
?> 
<?
   print $this->form;
?>
</div>
</div>
</div>
