<div id="auth_info_container" class="inner_container">
	<div class="inner_header">Slaptažodžio priminimas</div>
	<?php
	if($this->errors) {
		?>
		<div class="ui-state-error ui-corner-all" style="margin-bottom: 20px;">
			<ul class="formError">
			<?
			for ($i=0;$i<count($this->errors);$i++) {
				?>
				<li><?=$this->errors[$i]["message"];?></li>
				<?
			}
			?>
			</ul>
		</div>
		<?
	} else {
		if ($this->success) {
			?>
			<div>Registracijos patvirtinimui Jums  išsiųstas laiškas nurodytu el. pašto adresu</div>
			<?
		}
	}
	?>
	<div>Įveskite savo el.pašto adresą, kuriuo jungiatės prie sistemos</div>
	<div><?=$this->form;?></div>
</div>