<?php
$this->headTitle()->headTitle("Statistika");
?>
<?
$this->headScript()->appendFile("/public/ui/flot/jquery.flot.js");
$this->headScript()->appendFile("/public/ui/flot/jquery.flot.stack.js");
$this->headScript()->appendFile("/public/ui/flot/jquery.flot.selection.js");

$id = isset($_GET['id']) ? $_GET['id'] : "";
$_options = array("recipes" => "Sukurtų receptų skaičius (mėnesiais)", "users" => "Prisiregistravusių naujų naudotojų skaičius (mėnesiais)", "sessions" => "Virimų statistika", "styles" => "Sukurtų receptų skaičius pagal stilių", "cats" => "Sukurtų receptų skaičius pagal kategorijas", "abv" => "Išvirto alaus stiprumas", "ibu" => "Išvirto alaus kartumas", "locations" => "Naudotojų geografija");
?>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Statistika</div>
	<div style="margin-bottom: 5px;">
		Statistikos tipas:
		<select onchange="window.location=this.value">
			<?
			foreach ($_options as $key => $value) {
				$selected = ($id == $key) ? "selected" : "";
				?>
				<option value="?id=<?= $key; ?>" <?= $selected; ?>><?= $value ?></option>
				<?
			}
			?>
		</select>
	</div> 
	<?php
	if ($id == "locations"){
		?>
		<div style="margin-bottom: 20px;">
			<div id="placeholder" style="width:700px;height:600px; float: left;"></div> 
			<div id="locat_legend" style="width: 100px; float: left;"></div>
			<div class="clear"></div>
		</div>
		<?php
	} else {
		?>
		<div id="placeholder" style="width:800px;height:600px;"></div> 
		<div id="hover" style="margin-left:50px;margin-top:10px;width:700px;"></div> 
		<?php
	}
	?>
</div> 
<?php
if ($id == "locations"){
	?>
	<style>
		.xAxis .tickLabel {
			-webkit-transform: rotate(-90deg); 
			-moz-transform: rotate(-90deg);	
			margin-top: 50px;
			filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
		}
	</style>
	<?php
}
?>
<script id="source"> 
	var stack = 1, bars = true, lines = false, steps = false;
	<?
	switch ($id) {
		case "locations":
			?>
			var a=<?= $this->location_count; ?>;
			var d = [];
			var total=0;
			var dn=[];
			for (var i=0;i<a.length;i++) {
				a[i].user_location=a[i].user_location==null ? "?" : a[i].user_location;
				d[i]={label:a[i].user_location+" - " +a[i].count,data:[[i,a[i].count]]};
				dn[i]=[i,a[i].user_location]

			}
			var options = {


				bars:{show: true, barWidth: 0.9, align: 'center'}, 
				xaxis: { ticks: dn, autoscaleMargin: .10, labelAngle: 90  }, 
				grid: { hoverable: true, clickable: true },
				legend: {
					container: "#locat_legend"
				}
			}
			<?
		break;
		case "abv":
			?>
			var a=<?= $this->abv; ?>;
			var d = [];
			var total=0;
			var dn=[];
			for (var i=0;i<a.length;i++) {
				a[i].label=a[i].label==null ? "?" : a[i].label;
				d[i]={label:a[i].label+"% - " +a[i].count,data:[[i,a[i].count]]};
				dn[i]=[i,a[i].label]

			}
			var options = {


				bars:{show: true, barWidth: 0.9, align: 'center'}, 
				xaxis: { ticks: dn, autoscaleMargin: .10 }, 
				grid: { hoverable: true, clickable: true }
			}
			<?
		break;
		case "ibu":
			?>
			var a=<?= $this->ibu; ?>;
			var d = [];
			var total=0;
			var dn=[];
			for (var i=0;i<a.length;i++) {
				a[i].label=a[i].label==null ? "?" : a[i].label;
				d[i]={label:a[i].label+" IBU - " +a[i].count,data:[[i,a[i].count]]};
				dn[i]=[i,a[i].label]

			}
			var options = {


				bars:{show: true, barWidth: 0.9, align: 'center'}, 
				xaxis: { ticks: dn, autoscaleMargin: .10 }, 
				grid: { hoverable: true, clickable: true }
			}
			<?
		break;
	}
	?>
	$.plot($("#placeholder"),d,options);
</script> 
