<!DOCTYPE html>
<html>
	<head>
		<title>Atviras Alus</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
		<script src="js/jquery.js"></script>
		<script src="bootstrap/js/bootstrap.js"></script>
	</head>
	<body>
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li class="active">
							<a href="#">
								Titulinis
							</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Alaus receptai
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">
										Alaus stiliai
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										Visi receptai
									</a>
								</li>
								<li>
									<a href="#">
										Receptų paieška
									</a>
								</li>
								<li>
									<a href="#">
										Įdomiausi receptai
									</a>
								</li>
								<li>
									<a href="#">
										Atsitiktinis
									</a>
								</li>
								<li>
									<a href="#">
										Komentarai
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										Virimai
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										Mano receptai
									</a>
								</li>
								<li>
									<a href="#">
										Mėgstamiausi receptai
									</a>
								</li>
								<li>
									<a href="#">
										Mano virimai
									</a>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Skaičiuoklės
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">
										Receptų skaičiuoklė
									</a>
								</li>
								<li>
									<a href="#">
										Kitos skaičiuoklės
									</a>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Alus ir maistas
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">
										Užkandžiai prie alaus
									</a>
								</li>
								<li>
									<a href="#">
										Patiekalai prie alaus
									</a>
								</li>
								<li>
									<a href="#">
										Pateikalai iš alaus
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										Mano receptai
									</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="#">
								Forumas
							</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Skaitykla
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">
										Straipsniai
									</a>
								</li>
								<li>
									<a href="#">
										Dienoraščiai
									</a>
								</li>
								<li>
									<a href="#">
										Aludarių pranešimai
									</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="#">
								Įvykiai
							</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="menu" aria-labelledby="dLabel">
								Atviras Alus
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">
										Aludariai
									</a>
								</li>
								<li>
									<a href="#">
										Aludarių grupės
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										Apie projektą
									</a>
								</li>
								<li>
									<a href="#">
										Pagalba
									</a>
								</li>
								<li>
									<a href="#">
										Statistika
									</a>
								</li>
								<li class="divider"></li>
								<li class="dropdown-submenu">
									<a href="#">
										Idėjų bankas
									</a>
									<ul class="dropdown-menu">
										<li>
											<a href="#">
												Naujausios
											</a>
										</li>
										<li>
											<a href="#">
												Populiariausios
											</a>
										</li>
										<li>
											<a href="#">
												Įgyvendintos
											</a>
										</li>
										<li>
											<a href="#">
												Atmestos
											</a>
										</li>
										<li>
											<a href="#">
												Komentarai
											</a>
										</li>
										<li class="divider"></li>
										<li>
											<a href="#">
												Mano sukurtos
											</a>
										</li>
										<li>
											<a href="#">
												Neįvertintos
											</a>
										</li>
									</ul>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!--
		<div class="container" style="padding-top: 40px;">
			<div class="row">
				<div class="span12">1</div>
			</div>
			<div class="row">
				<div class="span6">21</div>
				<div class="span6">22</div>
			</div>
			<div class="row">
				<div class="span2">31</div>
				<div class="span2">32</div>
				<div class="span2">33</div>
				<div class="span2">34</div>
				<div class="span2">35</div>
				<div class="span2">36</div>
			</div>
		</div>
		-->
	</body>
</html>
