<!DOCTYPE html>
<html>
	<head>
		<title>Atviras Alus</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
		<link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.css">
		<link rel="stylesheet" href="style.css">
		<script src="js/jquery.js"></script>
		<script src="bootstrap/js/bootstrap.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a href="#" class="brand visible-phone">Atviras Alus</a>
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse">
						<i class="icon-align-justify icon-white"></i>
					</button>
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#user-collapse">
						<i class="icon-user icon-white"></i>
					</button>
					<div class="btn-group pull-right hidden-phone">
						<button class="btn btn-small">Tomas (T&amp;M Beer)</button>
						<button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
							&nbsp;<span class="caret"></span>&nbsp;
						</button>
						<ul class="dropdown-menu">
							<li>
								<a href="#">
									<i class="icon-envelope"></i>
									&nbsp;
									Paštas
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#">
									<i class="icon-book"></i>
									&nbsp;
									Receptai
								</a>
							</li>
							<li>
								<a href="#">
									<i class="icon-star"></i>
									&nbsp;
									Mėgstamiausi receptai
								</a>
							</li>
							<li>
								<a href="#">
									<i class="icon-th-list"></i>
									&nbsp;
									Virimų istorija
								</a>
							</li>
							<li>
								<a href="#">
									<i class="icon-wrench"></i>
									&nbsp;
									Paskyros nustatymai
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#">
									<i class="icon-off"></i>
									&nbsp;
									Atsijungti
								</a>
							</li>
						</ul>
					</div>	
					<div class="nav-collapse collapse visible-phone" id="user-collapse">
						<ul class="nav">
							<li>
								<a href="#">
									Paštas
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#">
									Receptai
								</a>
							</li>
							<li>
								<a href="#">
									Mėgstamiausi receptai
								</a>
							</li>
							<li>
								<a href="#">
									Virimų istorija
								</a>
							</li>
							<li>
								<a href="#">
									Paskyros nustatymai
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#">
									Atsijungti
								</a>
							</li>
						</ul>
					</div>
					<div class="nav-collapse collapse" id="nav-collapse">
						<ul class="nav">
							<li class="active">
								<a href="#">
									Titulinis
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Receptai
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											Alaus stiliai
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Visi receptai
										</a>
									</li>
									<li>
										<a href="#">
											Receptų paieška
										</a>
									</li>
									<li>
										<a href="#">
											Įdomiausi receptai
										</a>
									</li>
									<li>
										<a href="#">
											Atsitiktinis
										</a>
									</li>
									<li>
										<a href="#">
											Komentarai
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Virimai
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Mano receptai
										</a>
									</li>
									<li>
										<a href="#">
											Mėgstamiausi receptai
										</a>
									</li>
									<li>
										<a href="#">
											Mano virimai
										</a>
									</li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Skaičiuoklės
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											Receptų skaičiuoklė
										</a>
									</li>
									<li>
										<a href="#">
											Kitos skaičiuoklės
										</a>
									</li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Alus ir maistas
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											Užkandžiai prie alaus
										</a>
									</li>
									<li>
										<a href="#">
											Patiekalai prie alaus
										</a>
									</li>
									<li>
										<a href="#">
											Pateikalai iš alaus
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Mano receptai
										</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="#">
									Forumas
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Skaitykla
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											Straipsniai
										</a>
									</li>
									<li>
										<a href="#">
											Dienoraščiai
										</a>
									</li>
									<li>
										<a href="#">
											Aludarių pranešimai
										</a>
									</li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="menu" aria-labelledby="dLabel">
									Bendruomenė
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											Įvykiai
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Aludariai
										</a>
									</li>
									<li>
										<a href="#">
											Aludarių grupės
										</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="#">
											Apie projektą
										</a>
									</li>
									<li>
										<a href="#">
											Pagalba
										</a>
									</li>
									<li>
										<a href="#">
											Statistika
										</a>
									</li>
									<li class="divider"></li>
									<li class="dropdown-submenu">
										<a href="#">
											Idėjų bankas
										</a>
										<ul class="dropdown-menu">
											<li>
												<a href="#">
													Naujausios
												</a>
											</li>
											<li>
												<a href="#">
													Populiariausios
												</a>
											</li>
											<li>
												<a href="#">
													Įgyvendintos
												</a>
											</li>
											<li>
												<a href="#">
													Atmestos
												</a>
											</li>
											<li>
												<a href="#">
													Komentarai
												</a>
											</li>
											<li class="divider"></li>
											<li>
												<a href="#">
													Mano sukurtos
												</a>
											</li>
											<li>
												<a href="#">
													Neįvertintos
												</a>
											</li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container" style="padding-top: 60px;">
			<div class="row">
				<div class="span2 hidden-phone">
					<div style="text-align: center">
						<a href="#"><img alt="Atviras alus" src="/public/images/logo.png" /></a>
					</div>
					<div>
						<strong>Paskutiniai prisijungę aludariai</strong>
						<div class="clearfix"></div>
						<div class="home_user_avatar">
							<a href="#" title="Tomas (T&amp;M Beer)"><img class="img-rounded" src="http://www.gravatar.com/avatar/49004731f79f4e0999009e8c9a6704c8?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="haris"><img class="img-rounded" src="http://www.gravatar.com/avatar/c7f8d8f6fb22959e0eface837542d079?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="dzukas"><img class="img-rounded" src="http://www.gravatar.com/avatar/c6701140eadfc100e8dcb67c8eb68e94?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="JodaZ"><img class="img-rounded" src="http://www.gravatar.com/avatar/efcfbed5334ba7b88f65b4518d54a501?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Mantas (T&amp;M Beer)"><img class="img-rounded" src="http://www.gravatar.com/avatar/0a4b8bc1cdc7cff2608013f05c9fc693?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="erstikis"><img class="img-rounded" src="http://www.gravatar.com/avatar/b866f73439ccda6e58fdfa9a7a0c714e?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="svyturys"><img class="img-rounded" src="http://www.gravatar.com/avatar/8c4a0f50c861f0c4023759359d86540f?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="lukasvera"><img class="img-rounded" src="http://www.gravatar.com/avatar/93bcbfd119a63a600b125bbc07ac7037?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Sidras"><img class="img-rounded" src="http://www.gravatar.com/avatar/73a4dae008755142b5834a39b2b89f42?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Ignieška"><img class="img-rounded" src="http://www.gravatar.com/avatar/230f793bd610d20e36bced53c6265c68?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Vajezus"><img class="img-rounded" src="http://www.gravatar.com/avatar/956bc9a3a079177b1d9fab961bb4fcf9?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="vapas"><img class="img-rounded" src="http://www.gravatar.com/avatar/7f4ace3b4624a7bb260570d562e7b667?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="DV"><img class="img-rounded" src="http://www.gravatar.com/avatar/357777c0b366340347dbbcd91b99814d?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Regis"><img class="img-rounded" src="http://www.gravatar.com/avatar/44c317ed5dd7eb0b71d14cc3fde98e03?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="home_user_avatar">
							<a href="#" title="Pikas"><img class="img-rounded" src="http://www.gravatar.com/avatar/3dda34b7713ad3df3d4614977dc096a2?rating=G&amp;size=50&amp;default=mm" border="0"></a>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="well well-small">
						Per mėnėsį <b>40</b> aludariai išvirė <b>2093.5</b> litrus alaus
					</div>
				</div>
				<div class="span10">
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
					<p>a</p>
				</div>
			</div>
		</div>
	</body>
</html>
