<?php
$this->headTitle()->headTitle("Ingridientų užsakymas el. parduotuvėje Savas Alus");
?>
<script type="text/javascript">
	$(document).ready(function() {
	});
</script>
<?php
$user_id = isset($this->user_info->user_id) ? $this->user_info->user_id : 0;
?>
<div class="inner_container">
	<div class="inner_header">Ingridientų užsakymas el. parduotuvėje "Savas Alus"</div>
	<div>Dėkojame, užsakymas išsiųstas į el. parduotuvę.</div>
	<div>Jei per 8 darbo valandas negausite atsakymo iš parduotuvės atstovo, prašome susisiekti telefonu <b>+370 656 34844</b> arba el. pašto adresu <a href="mailto:info@savasalus.lt">info@savasalus.lt</a></div>
</div>