<? $this->element->user_email->setAttribs(array("style"=>'width:200'));?>
<form action="<?=$this->element->getAction();?>" method="<?= $this->element->getmethod();?>" target="_self" name="__passwordForm" id="__passwordForm" class="password_form">
	<dl>
		<dt><?=$this->element->user_email->getLabel();?></dt>
		<dd><?=$this->element->user_email;?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><?=$this->element->captcha->getLabel();?></dt>
		<dd><?=$this->element->captcha;?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><?=$this->element->password_action;?></dd>
		<div class="clear"></div>
	</dl>
</form>

