<? $this->element->user_email->setAttribs(array("style"=>'width:200'));?>
<form action="<?=$this->element->getAction();?>" method="<?= $this->element->getmethod();?>" target="_self" name="__passwordForm" id="__passwordForm">
<table width="100%">

<tr>
<td  align="right"><? echo $this->element->user_email->getLabel();?></td>
<td><?=$this->element->user_email;?></td>
</tr>
<tr>
<td align="right" valign="bottom"><?=$this->element->captcha->getLabel();?></td>
<td><?=$this->element->captcha;?></td>
</tr>

<tr >
<td style="padding-top:30" align="center" colspan="2"><?=$this->element->password_action;?></td>
</tr>
</table>
</form>

