<? $this->element->user_email->setAttribs(array("style"=>'width:200'));?>
<form action="<?=$this->element->getAction();?>" method="<?= $this->element->getmethod();?>" class="register_form">
	<dl>
		<dt><?=$this->element->user_name->getLabel();?></dt>
		<dd><?=$this->element->user_name;?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><?=$this->element->user_email->getLabel();?></dt>
		<dd><?=$this->element->user_email;?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd>Spausdami "Registruotis" Jūs patvirtinate, kad susipažinote bei sutinkate su <a href="/salygos" target="_blank">svetainės naudojimosi sąlygomis</a>.</dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><?=$this->element->register_action;?></dd>
		<div class="clear"></div>
	</dl>
</form>