<?php
$this->headTitle()->headTitle("Naujas skelbimas");
$this->headScript()->appendFile("/public/ui/ui/jquery.ui.datepicker.js");
$this->headScript()->appendFile("/public/js/ui.datepicker-lt.js");
?>
<script type="text/javascript">
	$(document).ready(function() {
		$("input[name='market_till']").datepicker();
		$('select[name="market_action"]').change(function(){
			if ($(this).val() == "sell"){
				$("#sell_options").show();
			} else {
				$("#sell_options").hide();
			}
		});
		$("#market_form").submit(function(){
			if ($("input[name='market_title']").val().trim() == ""){
				alert("Įveskite produkto pavadinimą")
				return false;
			}
			if ($("input[name='market_till']").val().trim() == ""){
				alert("Įveskite skelbimo galiojimo pabaigos datą")
				return false;
			}
			if ($("input[name='market_city']").val().trim() == ""){
				alert("Įveskite miesto pavadinimą")
				return false;
			}
			if ($("textarea[name='market_text']").val().trim() == ""){
				alert("Įveskite skelbimo tekstą")
				return false;
			}
			if ($("select[name='market_action']").val() == "sell" && $("select[name='market_category']").val() == "beer" && $("select[name='market_sell_option']").val() == "sell"){
				alert("\"Atviras alus\" svetainėje draudžiama talpinti skelbimus apie parduodamą alų. Tokia veikla prieštarauja Lietuvos Respublikos Alkoholio kontrolės Įstatymo 10 straipsniui.");
				return false;
			}
			return true;
		});
	});
</script>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Naujas skelbimas</div>
	<div class="ideas_actions" style="line-height: 28px;">
		<a href="/turgus">Skelbimų sąrašas</a>
		<?php
		if ($this->uid != 0) {
			?>
			<a href="/turgus/mano">Mano skelbimai</a>
			<a href="/turgus/naujas"><b>Naujas skelbimas</b></a>
			<?php
		}
		?>
	</div>
	<div>
		<form action="" method="post" id="market_form">
			<dl>
				<dt>Veiksmas:</dt>
				<dd>
					<select name="market_action">
						<option value="sell">Siūlau</option>
						<option value="buy">Ieškau</option>
					</select>
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Kategorija:</dt>
				<dd>
					<select name="market_category">
						<option value="beer">Alus</option>
						<option value="hop">Apyniai</option>
						<option value="yeast">Mielės</option>
						<option value="malt">Salyklas</option>
						<option value="other">Kita</option>
					</select>
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Produkto pavadinimas:</dt>
				<dd>
					<input type="text" name="market_title" value="" />
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Skelbimas galioja iki:</dt>
				<dd>
					<input type="text" name="market_till" value="<?= date("Y-m-d", strtotime("+2 week")); ?>" />
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Miestas:</dt>
				<dd>
					<input type="text" name="market_city" value="<?= $this->city ?>" />
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Skelbimo tekstas, kontaktai:</dt>
				<dd>
					<textarea name="market_text"></textarea>
				</dd>
				<div class="clear"></div>
			</dl>
			<dl id="sell_options">
				<dt>Prašomas atlygis:</dt>
				<dd>
					<select name="market_sell_option">
						<option value="give">Dovanoju</option>
						<option value="sell">Parduodu (skelbimo tekste nurodykite kainą)</option>
						<option value="exchange">Keičiu (skelbimo tekste nurodykite į ką)</option>
					</select>
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>&nbsp;</dt>
				<dd>
					<input type="submit" value="Sukurti" />
				</dd>
				<div class="clear"></div>
			</dl>
		</form>
	</div>
</div>