<?php
$this->headTitle()->headTitle("Nauja idėja");
?>
<?php
$user_id = isset($this->user_info->user_id) ? $this->user_info->user_id : 0;
?>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Idėjos</div>
	<div class="ideas_actions">
		<a href="/idejos/naujausios">Naujausios</a>
		<a href="/idejos/populiariausios">Populiariausios</a>
		<a href="/idejos/igyvendintos">Įgyvendintos</a>
		<a href="/idejos/atmestos">Atmestos</a>
		<?php
		if ($user_id){
			?>
			<a href="/idejos/mano">Mano sukurtos</a>
			<a href="/idejos/balsavimas">Neįvertintos</a>
			<?
		}
		?>
			<a href="/idejos/komentarai">Komentarai</a>
		<?
		if ($user_id){
			?>
			<a href="/idejos/nauja" style="font-weight: bold;">Sukurti naują</a>
			<?
		}
		?>
	</div>
	<?php
	if ($this->please_login === true){
		?>
		<div>
			Norėdami sukurti naują idėja, privalote prisijungti.
		</div>
		<?
	} else {
		?>
		<div>
			<?=$this->createForm;?>
		</div>
		<?
	}
	?>
</div>