<div class="new_block ico_idea_comment">
	<div class="white">
		<div class="avatar">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
			</a>
		</div>
		<div class="post">
			<div class="post_action">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<?= $item["user_name"] ?>
				</a>
				komentavo idėją 
				<a href="/ideja/<?= $item['idea_comment_idea_id']; ?>">
					<?= $item["idea_comment_idea_title"] ?>
				</a>
			</div>
			<div class="post_content">
				<?php
				$fhtml = new Zend_Filter_StripTags(array("allowTags" => array("br", "p")));
				$f = new Entities_Filter_Excerpt();
				$item['idea_comment_text'] = str_replace("\n", "<br />", $item['idea_comment_text']);
				?>
				<a href="/ideja/<?= $item['idea_comment_idea_id']; ?>" style="color: #666">
					<?=$f->filter($fhtml->filter($item['idea_comment_text']), 30); ?>
				</a>
			</div>
			<div class="post_stamp">
				<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>