<div class="new_block ico_market">
	<div class="white">
		<div class="avatar">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
			</a>
		</div>
		<div class="post">
			<div class="post_action">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<?= $item["user_name"] ?>
				</a>
				<?php
				switch($item['market_action']){
					case "buy":
						?>
						ieško
						<?php
						switch($item['market_category']){
							case "yeast":
								echo " mielių:";
							break;
							case "malt":
								echo " salyklo:";
							break;
							case "hop":
								echo " apynių:";
							break;
							case "beer":
								echo " alaus:";
							break;
							case "other":
								echo ":";
							break;
						}
					break;
					case "sell":
						switch($item['market_sell_option']){
							case "sell":
								echo "parduoda";
							break;
							case "give":
								echo "dovanoja";
							break;
							case "exchange":
								echo "siūlo mainams";
							break;
						}
						switch($item['market_category']){
							case "yeast":
								echo " mieles:";
							break;
							case "malt":
								echo " salyklą:";
							break;
							case "hop":
								echo " apynius:";
							break;
							case "beer":
								echo " alų:";
							break;
							case "other":
								echo ":";
							break;
						}
					break;
				}
				?>
				<a href="/turgus/skelbimas/<?= $item['item_id']; ?>">
					<?= $item["market_title"] ?>
				</a>
			</div>
			<div class="post_content">
				<?php
				$fhtml = new Zend_Filter_StripTags(array("allowTags" => array("br", "p")));
				$f = new Entities_Filter_Excerpt();
				$item['market_text'] = str_replace("\n", "<br />", $item['market_text']);
				?>
				<a href="/turgus/skelbimas/<?= $item['item_id']; ?>" style="color: #666">
					<?=$f->filter($fhtml->filter($item['market_text']), 30); ?>
				</a>
			</div>
			<div class="post_stamp">
				<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>