<div class="new_block ico_vote">
	<div class="white">
		<div class="avatar">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
			</a>
		</div>
		<div class="post">
			<div class="post_action">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<?= $item["user_name"] ?>
				</a>
				įvertino receptą 
				<a href="/alus/receptas/<?= $item['vote_recipe_id']; ?>-<?= $this->urlMaker($item["vote_recipe_name"])?>">
					<?= $item["vote_recipe_name"] ?>
				</a>
			</div>
			<div class="post_content">
				<a href="/alus/receptas/<?= $item['vote_recipe_id']; ?>-<?= $this->urlMaker($item["vote_recipe_name"])?>" style="color: #666; font-size: 18px;">
					<?=$item['vote_value'];?>
				</a>
			</div>
			<div class="post_stamp">
				<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>