<?php
if (isset($this->data['recipe']['recipe_name'])){
	$this->headTitle()->headTitle($this->data['recipe']['recipe_name']);
} else {
	$this->headTitle()->headTitle("Skaičiuoklė");
}
?>
<div id="calculus_container" class="inner_container">
	<div class="inner_header">
		<span style="float: right;">
			<a href="/content/faq" title="Kaip naudotis skaičiuokle?" target="_blank">
				<img src="/public/images/help.png" />
			</a>
		</span>
		Skaičiuoklė
	</div>
	<div>
		<?=$this->beerCalculus($this->data);?>
	</div>
</div>