<style>
.new_right {
	float: right;
	margin-left: 10px;
	width: 240px;
}
.new_left {
	float: left;
	width: 610px;
}
.new_block {
	border-bottom: 1px solid #ccc;
}
.new_block .avatar {
	float: left;
	width: 50px;
	padding-top: 3px;
	overflow: hidden;
}
.new_block .post {
	float: left;
	margin-left: 20px;
	width: 460px;
	overflow: hidden;
}
.new_block .post .post_action {
	margin-bottom: 5px;
	font-size: 13px;
}
.new_block .post .post_action a {
	font-weight: bold;
}
.post_stamp {
	text-align: right;
	font-size: 10px;
	color: #666;
	margin-top: 8px;
}
.new_tweet-attachment {
	margin-top: 15px;
}
.new_tweet-attachment .wi-240 {
	width: 370px;
}
.new_tweet-attachment .wi-320 {
	width: 500px;
}
.white {
	background-color: #ffffff;
	padding-bottom: 10px;
	padding-top: 10px;
	padding-left: 10px;
}
.ico_idea_comment {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_idea_comment.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_idea {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_idea.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_food {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_food.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_food_comment {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_food_comment.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_event_comment {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_event_comment.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_forum_post {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_forum_post.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_article {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_article.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_article_comment {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_article_comment.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_session {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_session.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_event {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_event.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_recipe {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_recipe.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_recipe_comment {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_recipe_comment.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_tweet {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_tweet.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_user {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_user.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_rss {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_rss.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.ico_blog {
	background-color: #eee;
	padding-left: 40px;
	background-image: url("/public/images/new/ico_blog.png");
	background-repeat: no-repeat;
	background-position: 4px 22px;
}
.new_ublock {
	background-color: #ddd;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	margin-bottom: 10px;
	border: 1px solid #ccc;
}
.new_filter {
	background-color: #eee;
	padding: 4px;
}
.new_filter input#new_tweet {
	float: left;
	height: 28px;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	border: 1px solid #ccc;
	padding: 2px;
	background-color: #f5f5f5;
	cursor: pointer;
	padding-left: 15px;
	padding-right: 15px;
}
.new_filter input#new_tweet:hover {
	color: #A8582D;
}
.new_filter select {
	height: 28px;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	border: 1px solid #ccc;
	padding: 2px;
	background-color: #f5f5f5;
	cursor: pointer;
	float: right;
}
#tweet_form textarea {
	margin-top: 10px;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	border: 1px solid #ccc;
	padding: 10px;
	width: 545px;
	height: 60px;
	margin-left: 3px;
}
.tt_image {
	width: 70px;
	height: 70px;
}
.tt_images {
	float: left;
	width: 70px;
	overflow: hidden;
	text-align: center;
}
.tt_images a {
	display: inline-block;
	background-color: #ccc;
	text-align: center;
	line-height: 20px;
	height: 20px;
	width: 20px;
	margin-top: 5px;
	margin-bottom: 5px;
	font-weight: bold;
	color: #000;
}
.tt_info {
	float: left;
	margin-left: 20px;
	width: 440px;
}
.tt_title {
	font-weight: bold;
	margin-bottom: 5px;
}
#tweet_form {
	background-color: #eee;
	padding: 4px;
	text-align: right;
}
.home_more {
	text-align: center;
	margin-top: 10px;
}
.home_user_avatar {
	float: left;
	width: 50px;
	margin-right: 2px;
	margin-bottom: 2px;
	height: 50px;
}
.home_user_name {
	float: left;
	font-weight: bold;
	line-height: 50px;
	width: 150px;
	overflow: hidden;
	height: 50px;
}
.home_user {
	margin-bottom: 5px;
}
input, select, .editable-select-options, .ui-autocomplete {
	text-align: left;
}
.tweet_del {
	color: #666;
	display: inline-block;
	margin-right: 20px;
}
.index_events {
	background-color: #fff;
	border: none;
}
.new_updated_items .ico_idea_comment,
.new_updated_items .ico_idea,
.new_updated_items .ico_food,
.new_updated_items .ico_food_comment,
.new_updated_items .ico_forum_post,
.new_updated_items .ico_article,
.new_updated_items .ico_event_comment,
.new_updated_items .ico_article_comment,
.new_updated_items .ico_session,
.new_updated_items .ico_event,
.new_updated_items .ico_recipe,
.new_updated_items .ico_recipe_comment,
.new_updated_items .ico_tweet,
.new_updated_items .ico_user,
.new_updated_items .ico_rss,
.new_updated_items .ico_blog {
	background-color: #ddd;	
}
.pastlogin_line {
	height: 10px;
	overflow: hidden;
	background-color: #ccc;
}
</style>
<script type="text/javascript">
	$(document).ready(function() {
		$("#new_filter_select").change(function(){
			window.location.href = "/filter/"+$(this).val();
		});
		$(".tweet_del").click(function(){
			if (confirm('Ar tikrai norite ištrinti šį įrašą?')) {
				var item = $(this).attr("data-item");
				$.post("/tweet/removetweet/",{
					id: item
				}, function(msg){	
					if(parseInt(msg)!=0){
						$("#tweet-"+item).hide();
					}	
				});
			}
		});
	});
</script>
<script type="text/javascript">
	var timeOutIdle = null;
	var currentURL = null;
	var currentImage = null;
	var imageSize = null;
	function preview() {
		clearTimeout(timeOutIdle);
		timeOutIdle = setTimeout("getPreview()", 1000);
	}
	function getPreview() {
		var curl = getcURL($('#new_tweet_message').val());
		if (curl == null) {
			currentURL = curl;
			return false;
		} else if (curl != currentURL) {
			currentURL = curl;
			$('#loader').html('<img src="/public/images/load.gif">');
			$('#loader').show();
			$.getJSON("/tweet/getimages", {
				url: currentURL
			}, function (data) {
				$("#new_tweet_url").val("");
				$("#new_tweet_title").val("");
				$("#new_tweet_description").val("");
				$("#new_tweet_image").val("");
				if (data.images_count > 0){
					$("#tt .tt_images .tt_image_total").html("<span>1</span> / "+data.images_count);
					$("#tt .tt_images .tt_image").html("");
					$.each(data.images, function(key, val) {
						$("#tt .tt_images .tt_image").html($("#tt .tt_images .tt_image").html() + '<img src="'+val+'" style="width: 70px; max-heigt: 70px; display: none;" class="t_image t_image_'+key+'" />');
					});
					$("#tt .tt_images .tt_image .t_image_0").show();
					currentImage = 0;
					$("#new_tweet_image").val($("#tt .tt_images .tt_image .t_image_"+currentImage).attr("src"));
				} else {
					$("#tt .tt_images").hide();
				}
				imageSize = data.images_count;
				$("#tt .tt_info .tt_title").html(data.title);
				$("#tt .tt_info .tt_description").html(data.description);
				//$("#loader").html("");
				$("#loader").html($("#tt").html());
				$("#new_tweet_url").val(data.url);
				$("#new_tweet_title").val(data.title);
				$("#new_tweet_description").val(data.description);
				rebindlinks();
			});
		}
	}
	function rebindlinks(){
		$(".tt_link_next").click(function(){
			if (currentImage < imageSize - 1){
				$(".t_image").hide();
				currentImage = currentImage + 1;
				$("#loader .tt_images .tt_image_total span").html(currentImage + 1);
				$("#new_tweet_image").val($(".t_image_"+currentImage).attr("src"));
				$(".t_image_"+currentImage).show();
			}
		});
		$(".tt_link_prev").click(function(){
			if (currentImage > 0){
				$(".t_image").hide();
				currentImage = currentImage - 1;
				$("#loader .tt_images .tt_image_total span").html(currentImage + 1);
				$("#new_tweet_image").val($(".t_image_"+currentImage).attr("src"));
				$(".t_image_"+currentImage).show();
			}
		});
	}
	$(document).ready(function () {
		$('#new_tweet_message').bind("paste", preview);
		$('#new_tweet_message').bind("click", preview);
		$("#new_tweet").click(function(){
			if (!$("#tweet_form").is(":visible")){
				$("#tweet_form").show('slide', {direction: 'up'});
			}
		});
		rebindlinks2();
		$("#close_tweet").click(function(){
			$("#new_tweet_message").val("");
			$("#new_tweet_url").val("");
			$("#new_tweet_image").val("");
			$("#new_tweet_title").val("");
			$("#new_tweet_description").val("");
			$("#tweet_form").hide('slide', {direction: 'up'});
			$("#loader").hide();
		});
		window.setInterval(function(){
			$.getJSON("/index/getnew/last/"+$("#newest_id").val()+"/type/<?=$this->filter_type?>", {
				url: currentURL
			}, function (data) {
				if (data.last != 0){
					$("#home_items").prepend(data.content);
					$("#newest_id").val(data.last);
				}
			});
		}, 1000*60*2);
	});
	function rebindlinks2(){
		$(".home_more input").click(function(){
			$(".home_more").html('<img src="/public/images/load.gif">');
			var last_id = $(this).attr("data-last");
			var type_name = $(this).attr("data-type");
			$.ajax({
				url: "/index/more/last/"+last_id+"/type/"+type_name,
				success: function(data) {
					$(".home_more").hide();
					$("#home_items").append(data);
					rebindlinks2();
				}
			});
		});
	
	}
	function getcURL(url) {
		var RegExp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
		var cURL = RegExp.exec(url);
		if (cURL != null) {
			return cURL[0];
		} else {
			return null;
		}
	}
</script>
<div class="new_home">
	<div class="new_left">
		<div class="inner_container" style="padding-top: 20px;">
			<div class="new_filter">
				<div>
					<input type="button" name="new_tweet" id="new_tweet" value="Pranešk naujieną arba nuorodą" />
					<select id="new_filter_select" name="new_filter_select">
						<option value="all" <?=($this->filter_type == "all") ? 'selected="selected"' : ''?>>Visi įrašai</option>
						<optgroup label="Receptai">
							<option value="recipe" <?=($this->filter_type == "recipe") ? 'selected="selected"' : ''?>>Receptai</option>
							<option value="recipe_comment" <?=($this->filter_type == "recipe_comment") ? 'selected="selected"' : ''?>>Receptų komentarai</option>
							<option style="font-weight: bold;" value="session" <?=($this->filter_type == "session") ? 'selected="selected"' : ''?>>Virimai</option>
						</optgroup>
						<optgroup label="Forumas">
							<option value="forum_post" <?=($this->filter_type == "forum_post") ? 'selected="selected"' : ''?>>Forumo žinutės</option>
						</optgroup>
						<optgroup label="Įvykiai">
							<option value="event" <?=($this->filter_type == "event") ? 'selected="selected"' : ''?>>Įvykiai</option>
						</optgroup>
						<optgroup label="Idėjos">
							<option value="idea" <?=($this->filter_type == "idea") ? 'selected="selected"' : ''?>>Idėjos</option>
							<option value="idea_comment" <?=($this->filter_type == "idea_comment") ? 'selected="selected"' : ''?>>Idėjų komentarai</option>
						</optgroup>
						<optgroup label="Skaitykla">
							<option value="tweet" <?=($this->filter_type == "tweet") ? 'selected="selected"' : ''?>>Aludarių pranešimai</option>
							<option value="blog" <?=($this->filter_type == "blog") ? 'selected="selected"' : ''?>>Dienoraščiai</option>
							<option value="rss" <?=($this->filter_type == "rss") ? 'selected="selected"' : ''?>>Naujienos iš kitų svetainių</option>
							<option value="article" <?=($this->filter_type == "article") ? 'selected="selected"' : ''?>>Straipsniai</option>
							<option value="article_comment" <?=($this->filter_type == "article_comment") ? 'selected="selected"' : ''?>>Straipsnių komentarai</option>
						</optgroup>
						<optgroup label="Aludariai">
							<option value="user" <?=($this->filter_type == "user") ? 'selected="selected"' : ''?>>Nauji aludariai</option>
						</optgroup>
					</select>
					<div class="clear"></div>
				</div>
			</div>
			<div id="tweet_form" style="display: none;">
				<form action="/tweet/submitnew" method="post">
					<textarea id="new_tweet_message" name="new_tweet_message"></textarea>
					<input type="hidden" id="new_tweet_url" name="new_tweet_url" value="" />
					<input type="hidden" id="new_tweet_image" name="new_tweet_image" value="" />
					<input type="hidden" id="new_tweet_title" name="new_tweet_title" value="" />
					<input type="hidden" id="new_tweet_description" name="new_tweet_description" value="" />
					<div id="loader" style="text-align: left; padding: 10px 20px 10px 20px; display: none;"></div>
					<div>
						<input type="button" value="Atšaukti" id="close_tweet" class="ui-button">
						<input type="submit" value="Skelbti" class="ui-button">
					</div>
				</form>
			</div>
			<div id="tt" style="display: none;">
				<div class="tt_images">
					<div class="tt_image"></div>
					<div class="tt_image_links">
						<a href="javascript:void(0);" class="tt_link_prev">&lt;</a>
						<a href="javascript:void(0);" class="tt_link_next">&gt;</a>
					</div>
					<div class="tt_image_total"></div>
				</div>
				<div class="tt_info">
					<div class="tt_title"></div>
					<div class="tt_description"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div style="height: 1px;" id="new_visibility"></div>
			<div style="margin-top: 10px;" id="home_items">
				<?php
				$last_id = 0;
				$first = true;
				$old_time = "3000-01-01 01:01:01";
				foreach ($this->items as $item):
					if ($this->past_login < $old_time && $this->past_login > $item['posted']){
						?>
						<div class="pastlogin_line"></div>
						<?
					}
					$old_time = $item['posted'];
					if ($first === true){
						$first = false;
						?>
						<input type="hidden" id="newest_id" name="newest_id" value="<?=$item['id']?>" />
						<?php
					}
					$last_id = $item['id'];
					switch($item['type']){
						case "idea_comment":
							include("partials/idea_comment.phtml");
						break;
						case "idea":
							include("partials/idea.phtml");
						break;
						case "food":
							include("partials/food.phtml");
						break;
						case "food_comment":
							include("partials/food_comment.phtml");
						break;
						case "forum_post":
							include("partials/forum_post.phtml");
						break;
						case "article":
							include("partials/article.phtml");
						break;
						case "article_comment":
							include("partials/article_comment.phtml");
						break;
						case "session":
							$temp_rname = trim($item['session_recipe_name']);
							if ($item['session_recipe_publish'] == 1 && !empty($temp_rname))
								include("partials/session.phtml");
						break;
						case "event":
							if ($item['event_published'] == 1)
								include("partials/event.phtml");
						break;
						case "event_comment":
							include("partials/event_comment.phtml");
						break;
						case "recipe":
							include("partials/recipe.phtml");
						break;
						case "recipe_comment":
							include("partials/recipe_comment.phtml");
						break;
						case "tweet":
							include("partials/tweet.phtml");
						break;
						case "user":
							include("partials/user.phtml");
						break;
						case "rss":
							include("partials/rss.phtml");
						break;
						case "blog":
							include("partials/blog.phtml");
						break;
					}
				endforeach;
				?>
				<div class="home_more">
					<input type="button" value="Įkelti daugiau įrašų" id="load_more" class="ui-button" data-last="<?=$last_id?>" data-type="<?=$this->filter_type?>"/>
				</div>
			</div>
		</div>
	</div>
	<div class="new_right">
		<?php
		if (isset($this->unvoted) && $this->unvoted > 0){
			?>
			<div class="inner_container">
				Idėjų banke užregistruota <?=$this->unvoted?> <?=$this->plurify($this->unvoted, "idėja", "idėjos", "idėjų")?>, už kurias dar nebalsavote. 
				<a href="/idejos/balsavimas">Peržiūrėti idėjų sąrašą</a>
			</div>		
			<?
		}
		?>
		<!-- ĮVYKIAI -->
		<?php
		if (count($this->events) > 0): 
		?>
			<div class="index_block index_events">
				<div class="block_header">Įvykiai:</div>
				<div class="block_content">
					<?php
					foreach ($this->events as $event):
					?>
						<div>
							<a href="/ivykis/<?=$event['event_id']; ?>-<?=$this->urlMaker($event['event_name']); ?>">
								<?=$event['event_name']; ?>
							</a> - <i><?=$event['event_start']; ?></i>
						</div>
					<?php
					endforeach;
					?>
				</div>
			</div>
		<?php
		endif;
		?>
		<div class="index_block index_sitenews">
			<div class="block_content">
				<div style="margin-bottom: 10px;">
					Per mėnėsį 
					<b><?= $this->total_brewed['brewers_total']; ?></b>
					aludariai išvirė 
					<b><a href="http://www.atvirasalus.lt/stats?id=sessions"><?= (float)$this->total_brewed['beer_total']; ?></a></b>&nbsp;litrus alaus
				</div>
			</div>
		</div>
		<div class="index_block index_last_users">
			<div class="block_header">Paskutiniai prisijungę aludariai</div>
			<div class="block_content">
				<div class="home_user">
					<?php
					foreach($this->users as $user){
						?>
						<div class="home_user_avatar" style="background-image: url('http://www.gravatar.com/avatar/<?= md5($user['user_email']); ?>?rating=G&size=50&default=mm')">
							<?php
							if ($user['online_status'] == "2"){
									?>
									<a href="/brewers/<?= $user['user_id']; ?>" title="<?=$user['user_name']?>"><img src="/public/images/new/user_on.gif" /></a>
									<?php
							} else {
								if ($user['online_status'] == "1"){
									?>
									<a href="/brewers/<?= $user['user_id']; ?>" title="<?=$user['user_name']?>"><img src="/public/images/new/user_idle.gif" /></a>
									<?php
								} else {
									?>
									<a href="/brewers/<?= $user['user_id']; ?>" title="<?=$user['user_name']?>"><img src="/public/images/new/user_off.gif" /></a>
									<?php
								}
							}
							?>
						</div>
						<?php
					}
					?>
					<div class="clear"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>