<?php
$this->headMeta()->setName('keywords', 'alaus gamyba,naminis,receptai,receptas,alus,skaičiuoklė,ibu,ebc,abv');
$this->headTitle()->append(" - atvira namų aludarių bendruomenė ");
$this->headScript()->appendFile("/public/ui/external/jquery.zrssfeed.min.js");
?>

<div class="index_container">
	<?php
	if (isset($this->unvoted) && $this->unvoted > 0){
		?>
		<div class="inner_container" style="text-align: center;">
			Idėjų banke užregistruota <?=$this->unvoted?> <?=$this->plurify($this->unvoted, "idėja", "idėjos", "idėjų")?>, už kurias dar nebalsavote. 
			<a href="/idejos/balsavimas">Peržiūrėti idėjų sąrašą</a>
		</div>
		<?
	}
	?>
	<div id="index_left">
		<!-- RECEPTAI -->
		<div class="index_block index_recipes">
			<div class="block_header">Naujausi alaus receptai:</div>
			<div class="block_content">
				<?php
				foreach ($this->recipes as $recipe):
				?>
					<div>
						<a href="/alus/receptas/<?= $recipe['recipe_id']; ?>-<?= $this->urlMaker($recipe['recipe_name']); ?>">
							<?=$recipe['recipe_name']; ?>
						</a>
						<span><?=$recipe['style_name']; ?></span>	
					</div>
				<?php
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/recipes">Peržiūrėti visus</a> (<?=$this->total_recipes["count"] ?>) 
				<a href="/recipes/random">Atsitiktinis receptas</a>
			</div>
		</div>
		
		<!-- BURBULIATORIUS -->
		<div class="index_block index_tweet">
			<div class="block_header">Burbuliatorius:</div>
			<div class="block_content">
				<?php
				$tweet = $this->twitter();
				echo $tweet->tweetList(5, 0);
				?>
			</div>
		</div>

		<!-- ATVIRO ALAUS NAUJIENOS -->
		<div class="index_block index_sitenews">
			<div class="block_header">Atviro alaus naujienos:</div>
			<div class="block_content">
				<div style="margin-bottom: 10px;">
					Per mėnėsį 
					<b><?= $this->total_brewed['brewers_total']; ?></b>
					aludariai išvirė 
					<b><a href="http://www.atvirasalus.lt/stats?id=sessions"><?= $this->total_brewed['beer_total']; ?></b></a> 
					litrus alaus
				</div>
				<div>
					Sveikiname mūsų naująjį aludarį,
					<a href="/brewers/<?= $this->welcome['user_id']; ?>"><?= $this->welcome['user_name']; ?></a>
				</div>
			</div>
		</div>

		<!-- FORUMAS -->
		<div class="index_block index_forum">
			<div class="block_header">Forumas:</div>
			<div class="block_content">
				<?php
				for ($i = 0; $i < count($this->posts); $i++) {
				?>
					<div class="index_forum_block">
						<div class="avatar">
							<a href="/brewers/<?= $this->posts[$i]['poster_id']; ?>">
								<img  src="http://www.gravatar.com/avatar/<?= $this->posts[$i]['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
								<span><?= $this->posts[$i]["user_name"] ?></span>
							</a>
						</div>
						<div class="post">
							<a class="post_title" href="/forum/topic.php?id=<?= $this->posts[$i]['topic_id']; ?>&page=<?= (ceil($this->posts[$i]['post_position'] / 30)); ?>#post-<?= $this->posts[$i]['post_id']; ?>">
								<?= $this->posts[$i]["topic_title"] ?>
							</a>
							<?php
							$fhtml = new Zend_Filter_StripTags();
							$f = new Entities_Filter_Excerpt();
							?>
							<span class="quotes">“</span>
							<?php
							$page_num = ceil($this->posts[$i]['post_position'] / 30);
							if ($page_num < 2){
								$page_num_str = "";
							} else {
								$page_num_str = "&page=".$page_num;
							}
							?>
							<a class="post_link" href="/forum/topic.php?id=<?= $this->posts[$i]['topic_id']; ?><?= $page_num_str; ?>#post-<?= $this->posts[$i]['post_id']; ?>">
								<?=wordwrap($f->filter($fhtml->filter($this->posts[$i]['post_text']), 30), 62, '</br>', true); ?>
							</a>
							<span class="quotes">”</span>
						</div>
						<div class="clear"></div>
					</div>
				<?php
				}
				?>
			</div>
		</div>

		<!-- ĮDOMIAUSI -->
		<div class="index_block index_favorites">
			<div class="block_header">Įdomiausi receptai:</div>
			<div class="block_content">
				<?php
				foreach ($this->fav_recipes as $favorite): 
				?>
					<div>
						<a href="/brewers/<?= $favorite['brewer_id']; ?>">
							<?= $favorite["user_name"] ?>
						</a>
						receptas
						<a class="recipe_name" href="/alus/receptas/<?= $favorite['recipe_id']; ?>-<?= $this->urlMaker($favorite['recipe_name']); ?>">
							<?=$favorite["recipe_name"];?>
						</a>
					</div>
				<?php
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/recipes/favorites">Peržiūrėt visus</a>
			</div>
		</div>

		<!-- STATISTIKA -->
		<div class="index_block index_stats">
			<div class="block_header">Statistika:</div>
			<div class="block_content">
				<?=$this->randomStatistics();?>
			</div>
			<div class="block_footer">
				<a href="/stats" >Daugiau statistikos</a>
			</div>
		</div>

	</div>
	<div id="index_right">
		<!-- ĮVYKIAI -->
		<?php
		if (count($this->events) > 0): 
		?>
			<div class="index_block index_events">
				<div class="block_header">Įvykiai:</div>
				<div class="block_content">
					<?php
					foreach ($this->events as $event):
					?>
						<div>
							<a href="/ivykis/<?=$event['event_id']; ?>-<?=$this->urlMaker($event['event_name']); ?>">
								<?=$event['event_name']; ?>
							</a> - <i><?=$event['event_start']; ?></i>
						</div>
					<?php
					endforeach;
					?>
				</div>
			</div>
		<?php
		endif;
		?>

		<!-- ALUDARIAI -->
		<div class="index_block index_stats">
			<div class="block_header">Aludariai:</div>
			<div class="block_content">
				<?php
				$i = 0;
				foreach ($this->users as $user):
					$i++;
				?>
					<div class="index-user" <?=($i!=3) ? 'style="margin-right: 25px;"' : ""; ?>>
						<a href="/brewers/<?=$user['user_id'];?>" style="width: 50px; height: 50px; display: inline-block; background-image: url('http://www.gravatar.com/avatar/<?=md5($user['user_email']); ?>?rating=G&size=50&default=mm')">
							<?php
							if ($user['ping_time'] > date("Y-m-d H:i:s", strtotime("-40 second")) || $user['user_id'] == $this->me){
								if ($user['user_id'] == $this->me){
									?>
									<img src="/public/images/new/user_on.gif" />
									<?php
								} else {
									if ($user['last_action_time'] > date("Y-m-d H:i:s", strtotime("-10 min"))){
										?>
										<img src="/public/images/new/user_on.gif" />
										<?php
									} else {
										?>
										<img src="/public/images/new/user_idle.gif" />
										<?php
									}
								}
							} else {
								?>
								<img src="/public/images/new/user_off.gif" />
								<?php
							}
							?>
						</a>
						<span>
							<a href="/brewers/<?=$user['user_id'];?>">
								<?= $user['user_name'];?>
							</a>
							(<?=$user['count'];?>)
						</span>
					</div>
				<?php
					if ($i == 3){
						?>
						<div class="clear"></div>
						<?php
						$i = 0;
					}
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/brewer/list">Peržiūrėt visus</a> (<?= $this->users_total["count"]; ?>)
				<a href="/groups" >Grupės</a>
			</div>
		</div>
		
		<!-- KOMENTARAI -->
		<div class="index_block index_comments">
			<div class="block_header">Komentarai:</div>
			<div class="block_content">
				<?php
				foreach ($this->comments as $comment):
				?>
					<div>
						<a href="/brewers/<?= $comment['user_id'];?>">
							<?=$comment["user_name"];?>
						</a>
						komentavo
						<a class="recipe_name" href="/alus/receptas/<?=$comment['recipe_id']; ?>-<?= $this->urlMaker($comment['recipe_name']); ?>#comment-<?=$comment['comment_id']; ?>">
							<?=$comment["recipe_name"];?>
						</a>
					</div>
				<?php
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/comments" >Visi komentarai</a>
			</div>
		</div>
		
		<!-- KUBILUOSE GYVENA -->
		<div class="index_block index_sessions">
			<div class="block_header">Kubiluose gyvena:</div>
			<div class="block_content">
				<?php
				foreach ($this->brew_session as $session):
				?>
					<div>
						<a href="/brewers/<?=$session['user_id']; ?>">
							<?=$session["user_name"] ?>
						</a>
						bravoryja
						<a class="session_name" href="/alus/receptas/<?=$session['recipe_id']; ?>-<?= $this->urlMaker($session['recipe_name']); ?>">
							<?=$session["recipe_name"];?>
						</a>
					</div>
				<?php
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/brew-session/history" >Visi virimai</a>
			</div>
		</div>
		
		<!-- STRAIPSNIAI -->
		<div class="index_block index_articles">
			<div class="block_header">Straipsniai:</div>
			<div class="block_content">
				<?php
				foreach ($this->articles as $article):
				?>
					<div>
						<a href="/content/read/<?= $article['article_cat']; ?>/<?= $article['article_id']; ?>-<?= $article['article_title']; ?>">
							<?=$article['article_title']; ?>
						</a>
						(<?=intval($article['total']); ?>)
						<img src="/public/images/comments_icon.png" />
					</div>
				<?php
				endforeach;
				?>
			</div>
		</div>
		
		<!-- DIENORAŠČIAI -->
		<div class="index_block index_blogs">
			<div class="block_header">Iš aludarių dienoraščio:</div>
			<div class="block_content">
				<?php
				foreach ($this->blogs as $blog):
				?>
					<div>
						<a href="/brewers/<?= $blog['post_author'];?>">
							<?= $blog['user_name'];?>
						</a>
						-
						<a class="article_name" href="<?=$blog['guid'];?>">
							<?=$blog['post_title'];?>
						</a>
						(<?=intval($blog['comment_count']);?>)
						<img src="/public/images/comments_icon.png" border=0/>
					</div>
					<div class="article_summary">
						<a href="<?=$blog['guid'];?>">
							<?
							$fhtml = new Zend_Filter_StripTags();
							$f = new Entities_Filter_Excerpt();
							echo $f->filter($fhtml->filter($blog['post_content']), 30);
							?>
						</a>
					</div>
				<?php
				endforeach;
				?>
			</div>
			<div class="block_footer">
				<a href="/blog" >Visi dienoraščiai</a>
			</div>
		</div>
		
		<!-- ALAUS NAUJIENOS -->
		<div class="index_block index_news">
			<div class="block_header">Alaus naujienos:</div>
			<div class="block_content">
				<div id="tad_feed"></div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<script>
	$('#tad_feed').rssfeed('http://pipes.yahoo.com/pipes/pipe.run?_id=210aea0f65d951e98dc682a8136c4ee9&_render=rss', {
		limit: 15,header:false,date:false
	});
</script>