<? $this->headMeta()->setName('keywords', 'alaus gamyba,naminis,receptai,receptas,alus,skaičiuoklė,ibu,ebc,abv');?>
<? $this->headTitle()->append(" - atvira namų aludarių bendruomenė ");?>

<? $this->headLink()->appendStylesheet("/public/ui/external/jquery.zrssfeed.css"); ?>
<? $this->headScript()->appendFile("/public/ui/external/jquery.zrssfeed.min.js");?>
<style>
.left_col {
	padding-top:10px
}
.right_col {
	padding-top:10px}
h1 {
	font-family:Georgia;
	font-weight:bold;
	color:#666666;
}

</style>
<div>

<table>
<tr><td valign="top">
<!--COLUMN 1-->
<!--RECEPTAI-->
<div class="left_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:450;">
<h1 style="text-decoration:italic;font-size:12px">Naujausi alaus receptai:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table width="306">
<? for ($i=0;$i<count($this->recipes);$i++) {?>
	<tr><td><a style="font-size:15" href="/alus/receptas/<?=$this->recipes[$i]['recipe_id'];?>-<?=$this->escapeParam($this->recipes[$i]['recipe_name']);?>"><?=$this->recipes[$i]['recipe_name'];?></a> <span style="font-size:11"><?=$this->recipes[$i]['style_name'];?></span></td></tr>	
<?}?>
</table>
<div style="padding-top:10"> <a href="/recipes">Peržiūrėti visus</a> (<?=$this->total_recipes["count"]?>) <a href="/recipes/random" style="padding-left:10">Atsitiktinis receptas</a></div>
</div>
<? if (count($this->events)>0) {?>
<div class="left_col">
<!--IVYKIAI-->

<div class="ui-corner-all" style="background:#ffffff;padding:10;width:450"><h1 style="text-decoration:italic;font-size:12px">Įvykiai:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<? if (count($this->events)>0 ) {?> 
<table>
<? for ($i=0;$i<count($this->events);$i++) {?>
<tr>
<td><a href="/ivykis/<?=$this->events[$i]['event_id'];?>-<?=$this->escapeParam($this->events[$i]['event_name']);?>"><?=$this->events[$i]['event_name'];?></a> - <i><?=$this->events[$i]['event_start'];?></i></td>
</tr>
<?}?>


</table>
<?}else{?>
<div align="center">Nieko nevyksta</div>
<?}?>
</div>
</div>
<?}?>
<!--NAUJIENOS-->
<div class="left_col">
<div>

<div class="ui-corner-all" style="background:#ffffff;padding:10;width:450"><h1 style="text-decoration:italic;font-size:12px">Burbuliatorius:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<?$tweet=$this->twitter(); print $tweet->tweetList(5,0);?>
</div>
<!--NAUJIENOS-->
<div class="left_col">
<div>

<div class="ui-corner-all" style="background:#ffffff;padding:10;width:450"><h1 style="text-decoration:italic;font-size:12px">Atviro alaus naujienos:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<p>Per mėnėsį <b><?=$this->total_brewed['brewers_total'];?></b> aludariai išvirė <b><a href="http://www.atvirasalus.lt/stats?id=sessions"><?=$this->total_brewed['beer_total'];?></b></a> litrus alaus</p>
<p>Sveikiname mūsų naująjį aludarį, <a href="/brewers/<?=$this->welcome['user_id'];?>"><?=$this->welcome['user_name'];?></a></p>

</div>
</div><!--FORUMAS-->
<div class="left_col">
<div class="ui-corner-all" style="background:#ffffff;width:450;padding:10"><h1 style="text-decoration:italic;font-size:12px">Forumas:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->posts);$i++) {?>
<tr>
<td valign="top" style="border-bottom:1px dotted #DEDEDE"><? 
if ($i % 2 ==1) {
$c ="style='text-indent:20px;color:#666666;padding:5;clear:right;text-indent:20px;'"; 
}else{ 
$c = " color:#666666;style='text-indent:20px;padding:5;clear:right;text-indent:20px;'";
}
?><div style="float:left;padding:5;display:inline-box"><img  src="http://www.gravatar.com/avatar/<?=$this->posts[$i]['email_hash'];?>?rating=G&size=50&default=mm" border="0"/><div align="center"><a  href="/brewers/<?=$this->posts[$i]['poster_id'];?>"><?=$this->posts[$i]["user_name"]?></a></div></div>
<div ><div align="right" style="padding:5;"> <a href="/forum/topic.php?id=<?=$this->posts[$i]['topic_id'];?>&page=<?=(ceil($this->posts[$i]['post_position']/30));?>#post-<?=$this->posts[$i]['post_id'];?>"><?=$this->posts[$i]["topic_title"]?></a></div>

<div <?=$c;?>>


<? $fhtml= new Zend_Filter_StripTags();
$f=new Entities_Filter_Excerpt();
?>
<span style="font-size:17px;font-weight:bold;text-align:right">“</span><a style="color:#666;font-size:12px;word-wrap" href="/forum/topic.php?id=<?=$this->posts[$i]['topic_id'];?>&page=<?=(ceil($this->posts[$i]['post_position']/30));?>#post-<?=$this->posts[$i]['post_id'];?>">
<?
print wordwrap($f->filter($fhtml->filter($this->posts[$i]['post_text']),30),62,'</br>',true) ;?>

</a><span style="font-size:17px;font-weight:bold">”</span>
</div></div>
</td>
</tr>
<?}?>
</table>
</div>
</div>
<!--FAVORITAI-->
<div class="left_col">
<div class="ui-corner-all" style="background:#ffffff;width:450;padding:10">

<h1 style="text-decoration:italic;font-size:12px">Įdomiausi:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->fav_recipes);$i++) {?>
<tr>
<td><a href="/brewers/<?=$this->fav_recipes[$i]['brewer_id'];?>"><?=$this->fav_recipes[$i]["user_name"]?></a> receptas <a style="font-size:15" href="/alus/receptas/<?=$this->fav_recipes[$i]['recipe_id'];?>-<?=$this->escapeParam($this->fav_recipes[$i]['recipe_name']);?>"><?=$this->fav_recipes[$i]["recipe_name"]?></a></td>
</tr>
<?}?>
</table>
<div style="padding-top:5;text-align:right"><a href="/recipes/favorites">Peržiūrėt visus</a></div>
</div>
</div>
<!-- STATISTIKA-->
<div class="left_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:450;"><h1 style="text-decoration:italic;font-size:12px">Statistika:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<div>
<?print $this->randomStatistics();?>
</div>
<div style="margin-top:5" align="right"><a href="/stats" >Daugiau statistikos</a></div>
</div>
</div>
<!--END COLUMN 1-->
</td>
<td align="left" valign="top" style="padding-left:15">
<div class="right_col">
<!--COLUMN 2-->
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360">
<h1 style="text-decoration:italic;font-size:12px">Aludariai:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table width="346">

<?
$z=0;
for ($i=0;$i<count($this->users)/3;$i++) {
	?>
	<tr>
	<?
	for ($ii=0;$ii<3;$ii++) {
		
		if (isset($this->users[$z])) {
?>
<td width="100" align="center" height="75">
<a href="/brewers/<?=$this->users[$z]['user_id'];?>"><div><a href="/brewers/<?=$this->users[$z]['user_id'];?>"><img src="http://www.gravatar.com/avatar/<?=md5($this->users[$z]['user_email']);?>?rating=G&size=50&default=mm" border="0"/></a></div>
<a href="/brewers/<?=$this->users[$z]['user_id'];?>"><?=$this->users[$z]['user_name'];?> </a> (<?=$this->users[$z]['count'];?>)</td>
<?
		}
$z++;
}
?>
</tr>
<?
}
?>        
</table>
<div style="padding-top:5"><a href="/brewer/list">Peržiūrėt visus</a> (<?=$this->users_total["count"];?>)  &nbsp;| &nbsp;<a href="/groups" >Grupės</a></div>
</div>
</div>
</div>
<div class="right_col">
<!--KOMENTARAI-->
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360;">
<h1 style="text-decoration:italic;font-size:12px">Komentarai:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->comments);$i++) {?>
<tr>
<td><a href="/brewers/<?=$this->comments[$i]['user_id'];?>"><?=$this->comments[$i]["user_name"]?></a> komentavo <a style="font-size:15" href="/alus/receptas/<?=$this->comments[$i]['recipe_id'];?>-<?=$this->escapeParam($this->comments[$i]['recipe_name']);?>"><?=$this->comments[$i]["recipe_name"]?></a></td>
</tr>
<?}?>
</table>
<div style="margin-top:5" align="right"><a href="/comments" >Visi komentarai</a></div>
</div>
</div>
<!-- VIRIMAI -->
<div class="right_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360;">
<h1 style="text-decoration:italic;font-size:12px">Kubiluose gyvena:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->brew_session);$i++) {?>
<tr>
<td><a href="/brewers/<?=$this->brew_session[$i]['user_id'];?>"><?=$this->brew_session[$i]["user_name"]?></a> bravoryja <a style="font-size:15" href="/alus/receptas/<?=$this->brew_session[$i]['recipe_id'];?>-<?=$this->escapeParam($this->brew_session[$i]['recipe_name']);?>"><?=$this->brew_session[$i]["recipe_name"]?></a></td>
</tr>
<?}?>
</table>
<div style="margin-top:5" align="right"><a href="/brew-session/history" >Visi virimai</a></div>
</div>
</div>
<!-- STRAIPSNIAI-->
<div class="right_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360">
<h1 style="text-decoration:italic;font-size:12px">Straipsniai:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->articles);$i++) {?>
<tr>
<td>
<div><a  style="font-size:13;" href="/content/read/<?=$this->articles[$i]['article_cat'];?>/<?=$this->articles[$i]['article_id'];?>-<?=$this->articles[$i]['article_title'];?>"><?=$this->articles[$i]['article_title'];?></a> (<?=intval($this->articles[$i]['total']);?>)<img src="/public/images/comments_icon.png" border=0/> </div>

</td>
</tr>
<?}?>
</table>
</div>
</div>
<!--DIENORAŠTIS-->
<div class="right_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360;"><h1 style="text-decoration:italic;font-size:12px">Iš aludarių dienoraščio:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
<table>
<? for ($i=0;$i<count($this->blogs);$i++) {?>
<tr >
<td style="border-bottom:1px dotted #EEE;padding-top:5">
<div><a href="/brewers/<?=$this->blogs[$i]['post_author'];?>"><?=$this->blogs[$i]['user_name'];?></a> - <a  style="font-size:13;" href="<?=$this->blogs[$i]['guid'];?>"><?=$this->blogs[$i]['post_title'];?></a> (<?=intval($this->blogs[$i]['comment_count']);?>)<img src="/public/images/comments_icon.png" border=0/> <br/>
<div style="text-indent:20px;"> <a style="font-size:12px;color:#666666;" href="<?=$this->blogs[$i]['guid'];?>">
<? $fhtml= new Zend_Filter_StripTags();
$f=new Entities_Filter_Excerpt();
print $f->filter($fhtml->filter($this->blogs[$i]['post_content']),30);?>
</a>
</div>
</div>

</td>
</tr>
<?}?>
</table>
<div style="margin-top:5" align="right"><a href="/blog" >Visi dienoraščiai</a></div>
</div>
</div>
<div class="right_col">
<div class="ui-corner-all" style="background:#ffffff;padding:10;width:360"><h1 style="text-decoration:italic;font-size:12px">Alaus naujienos:</h1><hr style="background-color: #EEEEEE;height:1px;border:0"/>
    <div id="tad_feed"></div>
	</div>
</div>
</div>

<!--END COLUMN 2-->

</td></tr>
</table>
</div>
<script>
$('#tad_feed').rssfeed('http://pipes.yahoo.com/pipes/pipe.run?_id=210aea0f65d951e98dc682a8136c4ee9&_render=rss', {
		limit: 15,header:false,date:false
	});
</script>

