<script type="text/javascript">
	$(function(){
	});
</script>
<div id="style_info_container" class="inner_container">
	<div class="inner_header"><h1>Prisijungę naudotojai</h1></div>
	<div>
		<div class="as-table">
			<div class="as-row">
				<div class="as-cell"></div>
				<div class="as-cell">Naudotojas</div>
				<div class="as-cell">Statusas</div>
				<div class="as-cell">Ping time</div>
				<div class="as-cell">Action time</div>
				<div class="as-cell">Last URL</div>
			</div>
			<?php
			foreach($this->users as $user):
				?>
				<div class="as-row">
					<div class="as-cell">
						<img src="http://www.gravatar.com/avatar/<?= md5($user['user_email']); ?>?rating=G&size=30&default=mm" />
					</div>
					<div class="as-cell">
						<a href="/brewers/<?=$user['user_id']?>"><?=$user['user_name']?></a>
					</div>
					<div class="as-cell">
						<?php
						switch($user['online_status']){
							case "1":
								echo "<span style='color: orange;'>idle</span>";
								break;
							case "2":
								echo "<span style='color: green;'>online</span>";
								break;
							case "0":
								echo "<span style='color: red;'>offline</span>";
								break;
						}
						?>
					</div>
					<div class="as-cell"><?=$user['ping_time']?></div>
					<div class="as-cell"><?=$user['last_action_time']?></div>
					<div class="as-cell"><a href="<?=$user['last_url']?>"><?=  str_replace("http://www.atvirasalus.lt", "", $user['last_url'])?></a></div>
				</div>
				<?php
			endforeach;
			?>
		</div>
	</div>
</div>