<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="lt" lang="lt">
    <head>
        <title>Alaus receptas</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
			body {
				background-color: #fff;
				margin-left: 50px;
				font-family: Courier, "Courier New", monospace;
				font-size: 14px;
			}
		</style>
	</head>
	<body>
		<div style="margin-top: 40px; width: 800px;">
			<div style="font-weight: bold; text-align: center; font-size: 16px; margin-bottom: 10px;"><?= $_POST['beer_name']; ?></div>
			<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
				Alaus kiekis: <?= $_POST['bash_size']; ?><br />
				Efektyvumas: <?= $_POST['efficiency']; ?><br />
				Atenuacija: <?= $_POST['attenuation']; ?><br />
				Stilius: <?= $_POST['beer_style']; ?>
			</div>
			<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
				SG: <?= $_POST['recipe_sg']; ?><br />
				FG: <?= $_POST['recipe_fg']; ?><br />
				ABV: <?= $_POST['recipe_abv']; ?><br />
				IBU: <?= $_POST['recipe_ibu']; ?><br />
				EBC: <?= $_POST['recipe_ebc']; ?>
			</div>
			<?php
			if (isset($_POST['malt_list'])) {
				$total = 0;
				for ($i = 0; $i < count($_POST['malt_weight']); $i++) {
					$total+=floatval($_POST['malt_weight'][$i]);
				}
				?>
				<div style="margin-bottom: 10px; margin-top: 14px;"><b>Salyklas</b></div>
				<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
					<div style="float: left; width: 360px;">Salyklas</div>
					<div style="float: left; width: 160px;">Spalva (EBC)</div>
					<div style="float: left; width: 145px;">Kiekis (kg)</div>
					<div style="float: left; width: 115px;">Kiekis (%)</div>
					<div style="clear: both;"></div>
				</div>
				<?
				for ($i = 0; $i < count($_POST['malt_list']); $i++) {
					?>
					<div>
						<div style="float: left; width: 360px;"><?= $_POST['malt_list'][$i]; ?></div>
						<div style="float: left; width: 160px;"><?= $_POST['malt_color'][$i]; ?></div>
						<div style="float: left; width: 145px;"><?= $_POST['malt_weight'][$i]; ?></div>
						<div style="float: left; width: 115px;"><?= round($_POST['malt_weight'][$i] / $total * 100, 1); ?></div>
						<div style="clear: both;"></div>
					</div>
					<?
				}
			}
			if (isset($_POST['hop_list'])) {
				?>
				<div style="margin-bottom: 10px; margin-top: 14px;"><b>Apyniai</b></div>
				<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
					<div style="float: left; width: 360px;">Apynys</div>
					<div style="float: left; width: 160px;">Kartumas (AA%)</div>
					<div style="float: left; width: 145px;">Kiekis (g)</div>
					<div style="float: left; width: 115px;">Laikas</div>
					<div style="clear: both;"></div>
				</div>
				<?
				for ($i = 0; $i < count($_POST['hop_list']); $i++) {
					?>
					<div>
						<div style="float: left; width: 360px;"><?= $_POST['hop_list'][$i]; ?></div>
						<div style="float: left; width: 160px;"><?= $_POST['hop_alpha'][$i]; ?></div>
						<div style="float: left; width: 145px;"><?= $_POST['hop_weight'][$i]; ?></div>
						<div style="float: left; width: 115px;"><?= $_POST['hop_time'][$i]; ?></div>
						<div style="clear: both;"></div>
					</div>
					<?
				}
			}
			if (isset($_POST['yeast_list'])) {
				?>
				<div style="margin-bottom: 10px; margin-top: 14px;"><b>Mielės</b></div>
				<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
					<div style="float: left; width: 520px;">Mielės</div>
					<div style="float: left; width: 260px;">Kiekis (g)</div>
					<div style="clear: both;"></div>
				</div>
				<?
				for ($i = 0; $i < count($_POST['yeast_list']); $i++) {
					?>
					<div>
						<div style="float: left; width: 520px;"><?= $_POST['yeast_list'][$i]; ?></div>
						<div style="float: left; width: 260px;"><?= $_POST['yeast_weight'][$i]; ?></div>
						<div style="clear: both;"></div>
					</div>
					<?
				}
			}
			if (isset($_POST['comments'])) {
				?>
				<div style="margin-bottom: 10px; margin-top: 14px;"><b>Pastabos</b></div>
				<div><?= nl2br($_POST['comments']); ?></div>
				<?
			}
			?>
		</div>
	</body>
</html>