<?php
function translateform($form){
	switch ($form){
		case 'pelet':
			return "Granulės";
			break;
		case 'cone':
			return "Spurgai";
			break;
		default:
			return "-";
			break;
	}
}
function translateuse($use){
	switch ($use){
		case 'Boil':
			return "Virimui (kartumui)";
			break;
		case 'Dry Hop':
			return "Sausam apyniavimui";
			break;
		case 'Mash':
			return "Salinimui";
			break;
		case 'First Wort':
			return "Pirmam misos apyniavimui";
			break;
		case 'Aroma':
			return "Aromatui";
			break;
		default:
			return "-";
			break;
	}
}
if (isset($this->print_data['beer_name'])){
	$this->headTitle()->headTitle($this->print_data['beer_name']);
} else {
	$this->headTitle()->headTitle("Alaus receptas");
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="lt" lang="lt">
    <head>
        <title>Alaus receptas</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
			body {
				background-color: #fff;
				margin-left: 50px;
				font-family: Courier, "Courier New", monospace;
				font-size: 14px;
			}
		</style>
	</head>
	<body>
		<? if (isset($this->print_data['beer_name'])) { ?>
			<div style="margin-top: 40px; width: 800px;">
				<div style="font-weight: bold; text-align: center; font-size: 16px; margin-bottom: 10px;"><?= $this->print_data['beer_name']; ?></div>
				<div style="padding-bottom: 4px;">
					Alaus kiekis: <?= round($this->print_data['bash_size'], 1); ?> ltr.<br />
					Virimo laikas: <?= round($this->print_data['boil_time'], 1); ?> min.<br />
					Efektyvumas: <?= number_format(round($this->print_data['efficiency'], 2), 2, ".", ""); ?><br />
					Atenuacija: <?= number_format(round($this->print_data['attenuation'], 2), 2, ".", ""); ?><br />
					Stilius: <?= $this->print_data['beer_style']; ?>
				</div>
				<div style="margin-bottom: 20px; padding-bottom: 4px;">
					Pradinis tankis (OG): <?= $this->usePlato(number_format($this->print_data['recipe_sg'], 3, ".", ""), true); ?><br />
					Galutinis tankis (FG): <?= $this->usePlato(number_format($this->print_data['recipe_fg'], 3, ".", ""), true); ?><br />
					Alkoholio kiekis (ABV): <?= number_format($this->print_data['recipe_abv'], 1, ".", ""); ?> %<br />
					Kartumas (IBU): <?= $this->print_data['recipe_ibu']; ?><br />
					Spalva (EBC): <?= $this->print_data['recipe_ebc']; ?>
				</div>
				<?php
				if (isset($this->print_data['malt_list'])) {
					$total = 0;
					for ($i = 0; $i < count($this->print_data['malt_weight']); $i++) {
						$total+=floatval($this->print_data['malt_weight'][$i]);
					}
					?>
					<div style="margin-bottom: 10px; margin-top: 14px;"><b>Salyklas</b></div>
					<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
						<div style="float: left; width: 360px;">Salyklas</div>
						<div style="float: left; width: 160px;">Spalva (EBC)</div>
						<div style="float: left; width: 145px;">Kiekis (kg)</div>
						<div style="float: left; width: 115px;">Kiekis (%)</div>
						<div style="clear: both;"></div>
					</div>
					<?
					for ($i = 0; $i < count($this->print_data['malt_list']); $i++) {
						?>
						<div>
							<div style="float: left; width: 360px;"><?= $this->print_data['malt_list'][$i]; ?></div>
							<div style="float: left; width: 160px;"><?= $this->print_data['malt_color'][$i]; ?></div>
							<div style="float: left; width: 145px;"><?= $this->print_data['malt_weight'][$i]; ?></div>
							<div style="float: left; width: 115px;"><?= round($this->print_data['malt_weight'][$i] / $total * 100, 1); ?></div>
							<div style="clear: both;"></div>
						</div>
						<?
					}
					if (count($this->print_data['malt_list']) > 1) {
						?>
						<div>
							<div style="float: left; width: 360px;">&nbsp;</div>
							<div style="float: left; width: 160px;">&nbsp;</div>
							<div style="float: left; width: 125px;border-top: 1px solid #999;"><?= number_format($total, 3, '.', ''); ?></div>
							<div style="clear: both;"></div>
						</div>
						<?
					}
				}
				if (isset($this->print_data['hop_list'])) {
					$total = 0;
					for ($i = 0; $i < count($this->print_data['hop_weight']); $i++) {
						$total+=floatval($this->print_data['hop_weight'][$i]);
					}
					?>
					<div style="margin-bottom: 10px; margin-top: 14px;"><b>Apyniai</b></div>
					<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
						<div style="float: left; width: 220px;">Apynys</div>
						<div style="float: left; width: 90px;">Forma</div>
						<div style="float: left; width: 70px;">AA (%)</div>
						<div style="float: left; width: 105px;">Kiekis (g)</div>
						<div style="float: left; width: 115px;">Laikas (min)</div>
						<div style="float: left; width: 200px;">Paskirtis</div>
						<div style="clear: both;"></div>
					</div>
					<?
					for ($i = 0; $i < count($this->print_data['hop_list']); $i++) {
						?>
						<div>
							<div style="float: left; width: 220px;"><?= $this->print_data['hop_list'][$i]; ?></div>
							<div style="float: left; width: 90px;"><?= translateform($this->print_data['hop_form'][$i]); ?></div>
							<div style="float: left; width: 70px;"><?= $this->print_data['hop_alpha'][$i]; ?></div>
							<div style="float: left; width: 105px;"><?= $this->print_data['hop_weight'][$i]; ?></div>
							<div style="float: left; width: 115px;"><?= $this->print_data['hop_time'][$i]; ?></div>
							<div style="float: left; width: 200px;"><?= translateuse($this->print_data['hop_use'][$i]); ?></div>
							<div style="clear: both;"></div>
						</div>
						<?
					}
					if (count($this->print_data['hop_list']) > 1) {
						?>
						<div>
							<div style="float: left; width: 310px;">&nbsp;</div>
							<div style="float: left; width: 70px;">&nbsp;</div>
							<div style="float: left; width: 105px;border-top: 1px solid #999;"><?= $total; ?></div>
							<div style="clear: both;"></div>
						</div>
						<?
					}
				}
				if (isset($this->print_data['yeast_list'])) {
					?>
					<div style="margin-bottom: 10px; margin-top: 14px;"><b>Mielės</b></div>
					<div style="border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 4px;">
						<div style="float: left; width: 520px;">Mielės</div>
						<div style="float: left; width: 260px;">Kiekis (g)</div>
						<div style="clear: both;"></div>
					</div>
					<?
					for ($i = 0; $i < count($this->print_data['yeast_list']); $i++) {
						?>
						<div>
							<div style="float: left; width: 520px;"><?= $this->print_data['yeast_list'][$i]; ?></div>
							<div style="float: left; width: 260px;"><?= $this->print_data['yeast_weight'][$i]; ?></div>
							<div style="clear: both;"></div>
						</div>
						<?
					}
				}
				if (isset($this->print_data['comments']) && !empty($this->print_data['comments'])) {
					?>
					<div style="margin-bottom: 10px; margin-top: 14px;"><b>Pastabos</b></div>
					<div><?= nl2br($this->print_data['comments']); ?></div>
					<?
				}
				?>
			</div>
		<? } else { ?>
			<div style="margin-top: 40px; width: 800px;">Receptas nerastas</div>
		<? } ?>
	</body>
</html>