<div id="brewer_session_container" class="inner_container">
	<div class="inner_header"><?=$this->title;?></div>
	<div style="font-size: 14px;"><?=$this->message?></div>
	<div>
		<ul>
			<li>
				<a href="/">Grįžti į titulinį puslapį</a>
			</li>
			<li>
				<a href="h/tracker/bug_report_page.php">Pranešti apie klaidą</a>
			</li>
		</ul>
	</div>
	<div style="text-align: center"><img src="/public/images/new/404.jpg" /></div>
</div>
<?php
if (APPLICATION_ENV == 'development')
{
  echo '<h2>Exception information:</h2>';
  printf('<p><b>Message:</b> %s</p>', $this->exception->getMessage());
 
  echo '<h2>Stack trace:</h2>';
  printf('<p>%s</p>', $this->exception->getTraceAsString());
 
  echo '<h3>Request Parameters:</h3>';
  printf('<p>%s</p>', var_export($this->request->getParams(), 1));
}
