<div class="index_block">
	<div class="block_header">
		<?=($widget['limit'] == 1) ? "Naujausias receptas" : "Naujausi receptai";?>
	</div>
	<div class="block_content">
		<?php
		foreach($widget['items'] as $item){
			?>
			<div class="wg_new_recipes">
				<div class="wg_new_recipes_image">
					<img src="/public/images/glass_thumb.png" alt="" style="background-color: <?=$this->colorHex($item['recipe_ebc'])?>;" />
				</div>
				<div class="wg_new_recipes_content">
					<div class="wg_new_recipes_name">
						<a href="/alus/receptas/<?=$item['item_id']?>-<?=$this->urlMaker($item['recipe_name'])?>"><?=$item['recipe_name']?></a>
					</div>
					<div class="wg_new_recipes_style">
						<div><?=$item['recipe_style_name']?></div>
						<div>
							<a href="/brewers/<?=$item['user_id']?>"><?=$item['user_name']?></a>
						</div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<?
		}
		?>
		<div class="wg_more">
			<a href="/recipes">Visi receptai</a>
		</div>
	</div>
</div>
