<div id="brewer_info_container" class="inner_container">
	<div class="inner_header"><?=$this->user_info['user_name'];?></div>
	<div class="brewer_info_container">
		<div class="brewer_info_left">
			<div class="brewer_info_block">
				<div class="brewer_info_label">Narys nuo:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_created'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Paskutinį kartą lankėsi:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_lastlogin'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Vietovė:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_location'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Išvirė alaus:</div>
				<div class="brewer_info_text"><?=$this->user_info['total_brewed'];?> l.</div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Papildoma informacija:</div>
				<div class="brewer_info_text"><?= preg_replace('@(https?://([-\w\.]+)+(:\d+)?(/([\w/_\.%-]*(\?\S+)?)?)?)@','<a href="$1" rel="nofollow" target="blank">$1</a>',nl2br($this->user_info['user_about']));?></div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="brewer_info_avatar">
			<img src="http://www.gravatar.com/avatar/<?=md5($this->user_info['user_email']);?>?rating=G&size=80&default=mm" border="0"/>
			<div class="brewer_info_actions">
				<a href="/mail/compose?token=<? print base64_encode($this->user_info['user_name']);?>" rel="nofollow">
					Rašyti žinutę
				</a>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>

<div id="brewer_info_recipe_container" class="inner_container">
	<div class="inner_header">Alaus receptai (<?=$this->user_info['total_recipes'];?>) <a style="font-size: 12px" href="/brewer/recipes/<?=$this->user_info['user_id'];?>"> peržiūrėti</a></div>
	<div id="tags">
		<ul>
			<?
			for ($i=0;$i<count($this->user_info['recipes']);$i++) {
				?>
				<li class="tag<?=rand(1,10);?>" style="background-color:<?=$this->colorHex($this->user_info['recipes'][$i]['recipe_ebc']);?>"><a href="/alus/receptas/<?=$this->user_info['recipes'][$i]['recipe_id'];?>-<?=$this->urlMaker($this->user_info['recipes'][$i]['recipe_name']);?>"><?=trim($this->user_info['recipes'][$i]['recipe_name']);?></a></li>
				<?
			}
			?>
		</ul>
	</div>
</div>

<div id="brewer_info_tag_container" class="inner_container">
	<div class="inner_header">Žymos</div>
	<div id="tags">
		<ul>
			<?
			for ($i=0;$i<count($this->user_info['tags']);$i++) {
				?>
				<li style="font-size:<?=(80+min($this->user_info['tags'][$i]['weight']*20,200));?>%"><a href="/search/brewer:<?=$this->user_info['user_name'];?>|tags:<?=$this->user_info['tags'][$i]['tag_text'];?>" style="color:#333"><?=$this->user_info['tags'][$i]['tag_text'];?></a></li>
				<?
			}
			?>
		</ul>
	</div>
</div>

<div id="brewer_info_comments_container" class="inner_container">
	<div class="inner_header">Receptų komentarai</div>
	<div id="info_comments">
		<?
		for ($i=0;$i<count($this->user_info['recipes_comments']);$i++) {
			?>
			<div class="info_comment">
				<a href="/alus/receptas/<?=$this->user_info['recipes_comments'][$i]['recipe_id'];?>-<?=$this->urlMaker($this->user_info['recipes_comments'][$i]['recipe_name']);?>">
					<?=$this->user_info['recipes_comments'][$i]['recipe_name'];?>
				</a>
				<span><?=$this->user_info['recipes_comments'][$i]['comment_date'];?></span>
				<div><?=$this->user_info['recipes_comments'][$i]['comment_text'];?></div>
			</div>
			<?
		}
		?>
	</div>
</div>