<script>
	$(function() {
		$("#show_empty_recipes").change(function(){
			if ($("#show_empty_recipes").attr("checked") == true){
				window.location.href = "/show_empty_recipes_on";
			} else {
				window.location.href = "/show_empty_recipes_off";
			}
		});
	});
</script>
<div id="brewer_info_container" class="inner_container">
	<div class="inner_header"><?=$this->user_info['user_name'];?></div>
	<?php
	if (isset($this->awards) && is_array($this->awards) && sizeof($this->awards) > 0){
		?>
		<div class="brewer_awards2" style="margin-bottom: 10px;">
			<?php
			foreach($this->awards as $key=>$val){
				$title = "";
				if (!empty($val['recipe_name'])){
					$title .= $val['recipe_name'].", ";
				}
				$title .= $val['event_name'];
				if (!empty($val['category'])){
					$title .= ", ".$val['category'];
				}
				if (!empty($val['place'])){
					$title .= ", ".$val['place']." vieta";
				}
				if (!empty($val['points']) && $val['points'] != "0"){
					$title .= " (".$val['points']." tšk.)";
				}
				?>
				<img src="/public/images/<?= trim($val['icon']) ?>-32.gif" width="32" title="<?= trim($title) ?>" />
				<?php
			}
			?>
		</div>
		<?php
	}
	?>
	<div class="brewer_info_container">
		<div class="brewer_info_left">
			<div class="brewer_info_block">
				<div class="brewer_info_label">Narys nuo:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_created'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Paskutinį kartą lankėsi:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_lastlogin'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Vietovė:</div>
				<div class="brewer_info_text"><?=$this->user_info['user_location'];?></div>
				<div class="clear"></div>
			</div>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Pagamino alaus:</div>
				<div class="brewer_info_text"><?=$this->user_info['total_brewed'];?> l.</div>
				<div class="clear"></div>
			</div>
			<?php
			if ($this->user_info['total_brewed_kvass'] != 0){
				?>
				<div class="brewer_info_block">
					<div class="brewer_info_label">Pagamino giros:</div>
					<div class="brewer_info_text"><?=$this->user_info['total_brewed_kvass'];?> l.</div>
					<div class="clear"></div>
				</div>
				<?php
			}
			?>
			<?php
			if ($this->user_info['total_brewed_cider'] != 0){
				?>
				<div class="brewer_info_block">
					<div class="brewer_info_label">Pagamino sidro:</div>
					<div class="brewer_info_text"><?=$this->user_info['total_brewed_cider'];?> l.</div>
					<div class="clear"></div>
				</div>
				<?php
			}
			?>
			<?php
			if ($this->user_info['total_brewed_mead'] != 0){
				?>
				<div class="brewer_info_block">
					<div class="brewer_info_label">Pagamino midaus:</div>
					<div class="brewer_info_text"><?=$this->user_info['total_brewed_mead'];?> l.</div>
					<div class="clear"></div>
				</div>
				<?php
			}
			if ($this->user_info['total_brewed_unknown'] != 0){
				?>
				<div class="brewer_info_block">
					<div class="brewer_info_label">Pagamino kitų gėrimų:<br />(pagal pašalintus receptus)</div>
					<div class="brewer_info_text"><?=$this->user_info['total_brewed_unknown'];?> l.</div>
					<div class="clear"></div>
				</div>
				<?php
			}
			?>
			<div class="brewer_info_block">
				<div class="brewer_info_label">Papildoma informacija:</div>
				<div class="brewer_info_text"><?= preg_replace('@(https?://([-\w\.]+)+(:\d+)?(/([\w/_\.%-]*(\?\S+)?)?)?)@','<a href="$1" rel="nofollow" target="blank">$1</a>',nl2br($this->user_info['user_about']));?></div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="brewer_info_avatar">
			<img src="http://www.gravatar.com/avatar/<?=md5($this->user_info['user_email']);?>?rating=G&size=80&default=mm" border="0"/>
			<div class="brewer_info_actions">
				<a href="/mail/compose?token=<? print urlencode(base64_encode($this->user_info['user_name']));?>" rel="nofollow">
					Rašyti žinutę
				</a>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
<?php
if (sizeof($this->user_info['recipes']) > 0){
	?>
	<div id="brewer_info_recipe_container" class="inner_container">
		<div class="inner_header">Alaus receptai (<?=$this->user_info['total_recipes'];?>) <a style="font-size: 12px" href="/brewer/recipes/<?=$this->user_info['user_id'];?>"> peržiūrėti</a></div>
		<?php
		if ($this->hidden_recipes >0):
			?>
			<div style="margin-bottom: 10px;">
				<label><input type="checkbox" value="1" name="show_empty_recipes" id="show_empty_recipes" <?=(isset($_COOKIE['show_empty_recipes']) && $_COOKIE['show_empty_recipes'] == "1") ? 'checked="checked"' : ''; ?>> Rodyti receptus be užregistruotų virimų (<?=$this->hidden_recipes?> <?=$this->plurify($this->hidden_recipes, "receptas", "receptai", "receptų")?>)</label>
			</div>
			<?php
		endif;
		?>
		<div id="tags">
			<ul>
				<?
				for ($i=0;$i<count($this->user_info['recipes']);$i++) {
					?>
					<li class="tag<?=rand(1,10);?>" style="background-color:<?=$this->colorHex($this->user_info['recipes'][$i]['recipe_ebc']);?>"><a href="/alus/receptas/<?=$this->user_info['recipes'][$i]['recipe_id'];?>-<?=$this->urlMaker($this->user_info['recipes'][$i]['recipe_name']);?>"><?=trim($this->user_info['recipes'][$i]['recipe_name']);?></a></li>
					<?
				}
				?>
			</ul>
		</div>
	</div>
	<?php
}
if (sizeof($this->user_info['sessions']) > 0){
	?>
	<div id="brewer_info_sessions_container" class="inner_container">
		<div class="inner_header">Paskutiniai aludario virimai</div>
		<div class="as-table">
			<div class="as-row">
				<div class="as-cell"><b>Pavadinimas</b></div>
				<div class="as-cell"><b>Receptas</b></div>
				<div class="as-cell"><b>Recepto autorius</b></div>
				<div class="as-cell"><b>Kiekis</b></div>
				<div class="as-cell"><b>Virimo data</b></div>
			</div>
			<?
			foreach ($this->user_info['sessions'] as $session){
				?>
				<div class="as-row" style="<?=($session['recipe_publish'] == "1") ? "" : "color: #999999;"; ?>">
					<?php
					if ($session['recipe_publish'] == "1"){
						?>
						<div class="as-cell"><?=$session['session_name']?></div>
						<div class="as-cell">
							<a href="/alus/receptas/<?=$session['recipe_id']?>-<?=$this->urlMaker($session['recipe_name'])?>">
								<?=$session['recipe_name']?>
							</a>
						</div>
						<?php
						if ($session['recu_id'] == $session['user_id']){
							?>
							<div class="as-cell">
								<?=$session['recu_name']?>
							</div>
							<?
						} else {
							?>
							<div class="as-cell">
								<a href="/brewers/<?=$session['recu_id']?>">
									<?=$session['recu_name']?>
								</a>
							</div>
							<?
						}
					} else {
						if ($session['recipe_publish'] === "0"){
							?>
							<div class="as-cell">-</div>
							<div class="as-cell">Receptas nėra viešas</div>
							<div class="as-cell">-</div>
							<?php
						} else {
							?>
							<div class="as-cell">-</div>
							<div class="as-cell">Receptas ištrintas</div>
							<div class="as-cell">-</div>
							<?php
						}
					}
					?>
					<div class="as-cell"><?=$session['session_size']?></div>
					<div class="as-cell" style="white-space:nowrap;"><?=($session['session_primarydate'] == "0000-00-00") ? "-" : $session['session_primarydate']; ?></div>
				</div>
				<?php
			}
			?>
		</div>
		<?php
		if ($this->user_info['sessions_size'] > 10){
			?>
			<div class="inner_footer" style="text-align: right;">
				<a href="/brewer/sessions/<?=$this->user_info['user_id']?>">Peržiūrėti visus aludario virimus</a>
			</div>
			<?
		}
		?>
	</div>
	<?
}
if (sizeof($this->user_info['tags']) > 0) {
	?>
	<div id="brewer_info_tag_container" class="inner_container">
		<div class="inner_header">Žymos</div>
		<div id="tags">
			<ul>
				<?
				for ($i=0;$i<count($this->user_info['tags']);$i++) {
					?>
					<li style="font-size:<?=(80+min($this->user_info['tags'][$i]['weight']*20,200));?>%"><a href="/search/brewer:<?=$this->user_info['user_name'];?>|tags:<?=$this->user_info['tags'][$i]['tag_text'];?>" style="color:#333"><?=$this->user_info['tags'][$i]['tag_text'];?></a></li>
					<?
				}
				?>
			</ul>
		</div>
	</div>
	<?
}
if (sizeof($this->user_info['recipes_comments']) > 0){
	?>
	<div id="brewer_info_comments_container" class="inner_container">
		<div class="inner_header">Receptų komentarai</div>
		<div id="info_comments">
			<?
			for ($i=0;$i<count($this->user_info['recipes_comments']);$i++) {
				?>
				<div class="info_comment">
					<a href="/alus/receptas/<?=$this->user_info['recipes_comments'][$i]['recipe_id'];?>-<?=$this->urlMaker($this->user_info['recipes_comments'][$i]['recipe_name']);?>">
						<?=$this->user_info['recipes_comments'][$i]['recipe_name'];?>
					</a>
					<span><?=$this->user_info['recipes_comments'][$i]['comment_date'];?></span>
					<div><?=$this->user_info['recipes_comments'][$i]['comment_text'];?></div>
				</div>
				<?
			}
			?>
		</div>
	</div>
	<?
}
?>