<script type="text/javascript">
	$(function() {
		$("#brewer_search_form").submit(function(){
			window.location.href = "/brewer/list/"+$("#brewer_search").val();
			return false;
		});
	})
</script>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Aludariai</div>
	<div class="brewer_search">
		<form action="" id="brewer_search_form">
			<input type="text" value="<?=$this->search?>" id="brewer_search" name="brewer_search" />
			<input type="submit" value="Ieškoti" class="ui-button" />
			<div class="clear"></div>
		</form>
	</div>
	<div class="clear"></div>
	<div class="users_avatars">
		<?
		$z = 0;
		foreach ($this->content as $item) {
			$z++;
			?>
			<div class="userlist_block">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<img src="http://www.gravatar.com/avatar/<?= md5($item['user_email']); ?>?rating=G&size=50&default=mm" border="0" />
				</a>
				<span>
					<a href="/brewers/<?= $item['user_id']; ?>">
						<?= $item['user_name']; ?>
					</a>
					(<?= $item['count']; ?>)
				</span>
			</div>
			<?php
			if ($z == 8){
				$z = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		}
		?>
		<div class="clear"></div>
	</div>
	<div><?=$this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml');?></div>
</div>