<div id="brewer_info_container" class="inner_container">
	<div class="inner_header">Naudotojo paskyra</div>
	<div class="profile_avatar">
		<img src="http://www.gravatar.com/avatar/<?= md5($this->user_info->user_email); ?>?rating=G&size=50&default=mm" border="0"/>
		<span>Pseudoportretas registruotas e-paštu: <?= $this->user_info->user_email; ?> svetainėje <a href="http://www.gravatar.com">gravatar.com</a></span>
		<div class="clear"></div>
	</div>
	<?
	if ($this->errors) {
		?>
		<div class="ui-state-error ui-corner-all" style="margin-bottom: 20px;">
			<ul class="formError">
				<?
				for ($i = 0; $i < count($this->errors); $i++) {
					?>
						<li><?= $this->errors[$i]["message"]; ?></li>
					<?
				}
				?>
			</ul>
		</div>
		<?
	}
	if ($this->success) {
		?>
		<div style="margin-bottom: 20px; font-weight: bold;"><?=$this->success;?></div>
		<?php
	}
	$this->userAttributesForm->getElement('user_mail_comments')->setValue($this->user_attributes['user_mail_comments']);
	$this->userAttributesForm->getElement('user_about')->setValue($this->user_attributes['user_about']);
	if (strlen($this->user_attributes['user_location']) > 0) {
		$this->userAttributesForm->getElement('user_location')->setValue($this->user_attributes['user_location']);
		$this->userAttributesForm->getElement('use_other_location')->setValue('0');
		$this->userAttributesForm->getElement('user_other_location')->setValue("");
		
		if ($this->userAttributesForm->getElement('user_location')->getValue() != $this->user_attributes['user_location']) {
			$this->userAttributesForm->getElement('use_other_location')->setValue('1');
			$this->userAttributesForm->getElement('user_other_location')->setValue($this->user_attributes['user_location']);
		}
	}
	?>
	<div>
		<?=$this->userAttributesForm;?>
	</div>
</div>

<? 
if (count($this->user_groups) > 0):
	?>
	<div id="brewer_info_container" class="inner_container">
		<div class="inner_header">Mano grupės</div>
		<div class="inner_footer">Prisijungę prie grupės  galėsite dalyvauti grupės narių susirašinėjimuose</div>
		<div>
			<form action="/brewer/profile" method="post" target="_self" id="groups_form">
				<?
				for ($i = 0; $i < count($this->user_groups); $i++) {
					$selected = $this->user_groups[$i]['user_id'] > 0 ? "checked" : "";
					?>
					<dl>
						<dd>
							<label for="gr-<?= $this->user_groups[$i]['group_id']; ?>">
								<input type="checkbox" value="<?= $this->user_groups[$i]['group_id']; ?>" id="gr-<?= $this->user_groups[$i]['group_id']; ?>" name="group[]" <?= $selected; ?> />
								<?= $this->user_groups[$i]['group_name']; ?> (<?= $this->user_groups[$i]['group_description']; ?>)
							</label>
						</dd>
					</dl>
					<?
				}
				?>
				<dl>
					<dd>
						<input type="hidden" name="action" value="groups"/>
						<input type="submit" value="Saugoti" class="ui-button" />
					</dd>
				</dl>
			</form>
		</div>
	</div>
	<?php	
endif;
?>
<div id="brewer_info_container" class="inner_container">
	<div class="inner_header">Slaptažodžio keitimas</div>
	<div>
		<?=$this->changePasswordForm;?>
	</div>
</div>