
<div align="center" >

<h1> Profilis </span></h1>
<div class="ui-corner-all" style="background:#FFF;padding:20;">
 <table><tr><td>
<img src="http://www.gravatar.com/avatar/<?=md5($this->user_info->user_email);?>?rating=G&size=50&default=mm" border="0"/></td><td style="padding:10" valign="top">
Avataras registruotas e-paštu: <?=$this->user_info->user_email;?> svetainėje <a href="http://www.gravatar.com">gravatar.com</a></td></tr></table></br>

<? if($this->errors) {
?>
	<div class="ui-state-error ui-corner-all" style="margin-bottom:20px"><ul class="formError">
<?
	for ($i=0;$i<count($this->errors);$i++) {
?>
		<li><?=$this->errors[$i]["message"];?></li>
<?
	}
?>
</ul></div></div>
<?
}
?> 
<?
if ($this->success) {
print $this->success;
}
print $this->changePasswordForm;
?>

</div>
