<div id="style_recipes_container" class="inner_container">
	<div class="inner_header">Aludario <?= $this->brewer["user_name"]; ?> receptai</div>
	<div class="style_recipes">
		<?php
		$i = 0;
		foreach ($this->content as $item):
			$i++;
		?>
			<div class="style_recipe">
				<?= $this->recipeItem($item); ?>
			</div>
		<?php
			if ($i == 3){
				$i = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		endforeach;
		?>
		<div class="clear"></div>
	</div>
	<div>
		<?=$this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml');?>
	</div>
</div>