<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="lt" lang="lt">
	<head>
		<meta name="description" content="Atviras alus - naminio alaus aludarių bendruomenė. Alaus receptai. Stiliaus aprašymai. Alaus skaičiuoklė" />
		<meta name="alexaVerifyID" content="flj8CxyyfEenq5UbyH5vpBlz7DA" />
		<meta name="y_key" content="9421766f5e8b266a" />
		<meta name="google-site-verification" content="Q15UyxPCIq_du9gHO4mr1INQh_KzSx8YaB6XytiaO4M" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="/public/js/jquery-1.4.4.min.js"></script>
		<script type="text/javascript" src="/public/ui/ui/jquery-ui-1.8.7.custom.js"></script>
		<?=$this->headTitle()->prepend('Atviras alus ');?>
		<?=$this->headTitle();?>
		<?=$this->headMeta();?>
		<?=$this->headLink();?>
		<?=$this->headStyle();?>
		<link type="text/css" href="/public/css/pepper-grinder/jquery-ui-1.8.7.custom.css" rel="stylesheet" />	
		<link type="text/css" href="/public/css/style.css" rel="stylesheet" media="all" />
		<link type="text/css" href="/public/css/print.css" rel="stylesheet" media="print" />
		<link href="/public/css/userScreen.css" media="screen, projection" rel="stylesheet" type="text/css">
		<script type="text/javascript" src="/public/ui/ui/jquery.ui.widget.js"></script>
		<script type="text/javascript" src="/public/ui/ui/jquery.ui.dialog.js"></script>
		<script type="text/javascript" src="/public/ui/ui/jquery.ui.position.js"></script>
		<script type="text/javascript" src="/public/js/website.js"></script>
		<?= $this->headScript() ?>
		<?  $front = Zend_Controller_Front::getInstance();?>
		<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
			{lang: 'lt'}
		</script>
	</head>
	<body>
		<div id="header_container">
			<a href="/" id="logo" title="Atviras alus"></a>
			<div id="top_container">
				<div id="top">
					<div id="proverb"><?=$this->fortune();?></div>
					<div id="userinfo"><?=$this->loginScreen();?></div>
					<div class="clear"></div>
				</div>
				<div id="menu">
					<ul id="topmenu">
					<?php
					$this->navigation(new Zend_Navigation(new Zend_Config_Xml(APPLICATION_PATH."/configs/defaultNavigation.xml","nav")));
					$pages = $this->navigation()->getPages();
					foreach ($pages as $page):
						if ($page->isActive()) {
							$class = "active";
						} else {
							$class = "";
						}
						?>
						<li>
							<a href="<?=$page->getHref();?>" class="<?=$class?>">
								<?=$page->label;?>
							</a>
						</li>
						<?php
					endforeach;
					?>
					</ul>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div id="main_container">
			<div id="left">
				<div style="margin-bottom: 7px;">
					<a href="/parama">
						<img src="/public/images/new/donate.png" />
					</a>
				</div>
				<div class="banner">
					<a href="http://tikrasalus.lt" target="_blank">
						<img src="/public/images/TAD.png" width="120" border="0"/>
					</a>
				</div>
				<div class="banner">
					<a href="http://savasalus.lt" target="_blank">
						<img src="/public/images/savasalus.jpg" width="120" border="0"/>
					</a>
				</div>
				<div class="banner">
					<a href="http://www.akl.lt" target="_blank">
						<img src="/public/images/akl.jpg" width="120" border="0"/>
					</a>
				</div>
			</div>
			<div id="main_content">
				<?=$this->layout()->content;?>
			</div>
			<div class="clear"></div>
		</div>
		<div id="bugreport_link"><input type="button" id="bugreport_button" class="ui-button" value="Praneškite apie svetainėje pastebėtas klaidas" /></div>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-21270974-1']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</body>
</html>
