<form action="<?= $this->element->getAction(); ?>" method="<?= $this->element->getmethod(); ?>" target="_self" name="__attributesForm" id="__attributesForm">
	<dl>
		<dt><? echo $this->element->user_location->getLabel(); ?></dt>
		<dd><?= $this->element->user_location; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><? echo $this->element->use_other_location->getLabel(); ?></dt>
		<dd><?= $this->element->use_other_location; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><? echo $this->element->user_other_location->getLabel(); ?>&nbsp;</dt>
		<dd><?= $this->element->user_other_location; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><? echo $this->element->user_about->getLabel(); ?></dt>
		<dd><?= $this->element->user_about; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd>Galimos HTML žymės: &lt;p&gt;, &lt;b&gt;, &lt;br&gt;, &lt;strong&gt;</dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><?= $this->element->user_mail_comments; ?><?= $this->element->user_mail_comments->getLabel(); ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><?= $this->element->attributes_action; ?><?= $this->element->action; ?></dd>
		<div class="clear"></div>
	</dl>
</form>

