<form action="<?= $this->element->getAction(); ?>" method="<?= $this->element->getmethod(); ?>" target="_self" name="__profileForm" id="__profileForm">
	<dl>
		<dt><? echo $this->element->user_password_old->getLabel(); ?></dt>
		<dd><?= $this->element->user_password_old; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><? echo $this->element->user_password->getLabel(); ?></dt>
		<dd><?= $this->element->user_password; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt><? echo $this->element->user_password_repeat->getLabel(); ?></dt>
		<dd><?= $this->element->user_password_repeat; ?></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><?= $this->element->profile_action; ?></dd>
		<div class="clear"></div>
	</dl>
</form>