<?= $this->headScript()->appendFile("/public/ui/tinymce/jscripts/tiny_mce/tiny_mce.js"); ?>
<?= $this->headScript()->appendFile("/public/ui/tinymce/jscripts/tiny_mce/jquery.tinymce.js"); ?>
<div id="admin_container" class="inner_container">
	<div class="inner_header">Administravimas - straipsniai</div>
	<div>
		<div style="float: left; width: 700px;">
			<form  id="article_form">
				<div style="margin-bottom: 10px;">
					<input type="text" id="article_title" name="article_title" value="" style="width: 673px;" />
				</div>
				<div style="margin-bottom: 10px;">
					<textarea name="article_resume" id="article_resume" style="width: 672px; height: 80px;"></textarea>
				</div>
				<input type="hidden" id="article_id" name="article_id" value=""/>
				<div style="margin-bottom: 10px;">
					<textarea name="article_text" id="article_text"></textarea>
				</div>
			</form>
		</div>
		<div style="float: left; width: 100px;">
			<div style="margin-bottom: 10px;">
				<select name="article_cat" id="article_cat" onChange="loadArticlesList()" style="width: 138px;">
					<?
					for ($i = 0; $i < count($this->article_cats); $i++) {
						?>
						<option value="<?= $this->article_cats[$i]["cat_id"]; ?>"><?= $this->article_cats[$i]["cat_name"]; ?></option>
						<?
					}
					?>
				</select>
			</div>
			<div style="margin-bottom: 10px;">
				<select multiple="multiple" id="article_list" onChange="loadArticle()" style="width: 138px; height: 330px;"></select>
			</div>
		</div>
		<div style="clear: both;"></div>
	</div>
	<a href="javascript:;" onmousedown="alert($('#article_text').html());">[Get contents]</a>
</div>

<script type="text/javascript">
	$(function() {
		$('#article_text').tinymce({
			script_url : '../js/tinymce/jscripts/tiny_mce/tiny_mce.js',
			mode : "exact",
			elements : "article_text",
			theme : "advanced",
			plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
			theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,
			content_css : "css/content.css",
			template_external_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/template_list.js",
			external_link_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/link_list.js",
			external_image_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/image_list.js",
			media_external_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/media_list.js",
			execcommand_callback : "execcommand_callback",
			relative_urls : false,
			template_replace_values : {
				username : "Some User",
				staffid : "991234"
			}
		});   loadArticlesList()
	});
	function execcommand_callback(editor_id, elm, command, user_interface, value) {
		switch(command) {
			case "mceSave":
				saveArticle()
				return true;
				break
			case "mceSetContent":
				$('#article_form')[0].reset()
				$('#article_list').val(0)
				return true;
				break;
		}
	}
	function loadArticle() {
		var surl = "/admin/load-article";
		if ( $('#article_list').val()) {
			$.ajax({type:'POST', url:surl, data:{article_id:$('#article_list').val()}, success:function (d) {
					var data = jQuery.parseJSON(d);
					if (data) {
						if (data.status == "1") {
							if (data.errors[0].type == "authentication") {
								showLogin();
								return;
							}
						} else {
							if (data.data) {
								$('#article_text').html(data.data.article_text)
								$('#article_title').val(data.data.article_title)
								$('#article_id').val(data.data.article_id)
								$('#article_resume').val(data.data.article_resume)
							}
						}
					} else {
					}
				}});
		}
	}
	function saveArticle() {
		if ($('#article_title').val().length>0) {
			if ($('#article_id').val().length>0) {
				saveAction({article_id:$('#article_id').val(),article_title:$('#article_title').val(),article_resume:$('#article_resume').val(),article_text:$('#article_text').html()})
			}else{
				if (confirm("Ar norite sukurti naują straipsnį?")) {
					saveAction({article_title:$('#article_title').val(),article_resume:$('#article_resume').val(),article_text:$('#article_text').html()})
				}
			}
		}else{
			alert('Straipsni neturi  pavadinimo!')
		}
	}
	function saveAction(data) {
		var surl = "/admin/save-article";
		$.ajax({type:'POST', url:surl, data:data, success:function (d) {
				var data = jQuery.parseJSON(d);
				if (data) {
					if (data.status == "1") {
						if (data.errors[0].type == "authentication") {
							showLogin();
							return;
						}
					} else {
						if (data.data) {
							$('#article_text').html(data.data.article_text)
							$('#article_title').val(data.data.article_title)
							$('#article_id').val(data.data.article_id)
							$('#article_resume').val(data.data.article_resume)
						}
					}
				} else {
				}
			}});
	}
	function deleteArticle() {
	}
	function loadArticlesList() {
		var surl = "/admin/load-articles";
		$('#article_list').html("")
		if ($('#article_cat').val()) {
			$.ajax({type:'POST', url:surl, data:{article_cat:$('#article_cat').val()}, success:function (d) {
					var data = jQuery.parseJSON(d);
					if (data) {
						if (data.status == "1") {
							if (data.errors[0].type == "authentication") {
								showLogin();
								return;
							}
						} else {
							if (data.data) {
								for (var i=0;i<data.data.length;i++) {
							
									$('#article_list').append(
							 	
									$('<option></option>').val(data.data[i].article_id).html(data.data[i].article_title)
								);
								}
							}
						}
					} else {
					}
				}});
		}
	}

</script>


