
<?= $this->headScript()->appendFile("/public/ui/tinymce/jscripts/tiny_mce/tiny_mce.js");?>
<?= $this->headScript()->appendFile("/public/ui/tinymce/jscripts/tiny_mce/jquery.tinymce.js");?>






<table width="900"><tr><td>
<form  id="article_form">
<table>
<tr>
<td valign="top">
        <input type="text" id="article_title" name="article_title" style="width:100%" value=""/>
        </td>
</tr>
<tr>
<td valign="top">
<textarea name="article_resume" style="width:100%;height:80" id="article_resume"></textarea>
        </td>
</tr>
<tr>
<td valign="top">
	<input type="hidden" id="article_id" name="article_id" style="width:100%" value=""/>
        <textarea name="article_text" style="width:100%" id="article_text"></textarea>
        </td>
</tr>
</table>
</form>
</td>
<td width="250" valign="top">
<table>
<tr>
<td valign="top"><select name="article_cat" id="article_cat" style="width:230" onChange="loadArticlesList()">
<?
for ($i=0;$i<count($this->article_cats);$i++) {
	?>
	<option value="<?=$this->article_cats[$i]["cat_id"];?>"><?=$this->article_cats[$i]["cat_name"];?></option>
	<?
}
?></select></td>
</tr>

<tr>
<td><select style="width:230;height:100%" multiple="multiple" id="article_list" onChange="loadArticle()"></select></td>
</tr>
</table>
</td>
</tr>
</table>
  <a href="javascript:;" onmousedown="alert($('#article_text').html());">[Get contents]</a>

<script type="text/javascript">
        $(function() {
                $('#article_text').tinymce({
                        // Location of TinyMCE script
                        script_url : '../js/tinymce/jscripts/tiny_mce/tiny_mce.js',
                        	
                        // General options
                         mode : "exact",
                         elements : "article_text",

                        theme : "advanced",
                        plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

                        // Theme options
                        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
                        theme_advanced_toolbar_location : "top",
                        theme_advanced_toolbar_align : "left",
                        theme_advanced_statusbar_location : "bottom",
                        theme_advanced_resizing : true,

                        // Example content CSS (should be your site CSS)
                        content_css : "css/content.css",

                        // Drop lists for link/image/media/template dialogs
                        template_external_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/template_list.js",
                        external_link_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/link_list.js",
                        external_image_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/image_list.js",
                        media_external_list_url : "/public/ui/tinymce/jscripts/tiny_mce/lists/media_list.js",
                        execcommand_callback : "execcommand_callback",
                        relative_urls : false,

                        // Replace values for the template plugin
                        template_replace_values : {
                                username : "Some User",
                                staffid : "991234"
                        }
                });   loadArticlesList()
        }
     
        );
        function execcommand_callback(editor_id, elm, command, user_interface, value) {
        	
        	switch(command) {
        	case "mceSave":
        		 saveArticle()
        		 return true;
        		break
        	case "mceSetContent":
        		$('#article_form')[0].reset()
        		$('#article_list').val(0)
        		 return true;
        		break;
        	}
        }

        function loadArticle() {
        	var surl = "/admin/load-article";
	
	if ( $('#article_list').val()) {
		$.ajax({type:'POST', url:surl, data:{article_id:$('#article_list').val()}, success:function (d) {
			var data = jQuery.parseJSON(d);
			if (data) {
				if (data.status == "1") {
					if (data.errors[0].type == "authentication") {
						showLogin();
						return;
					}
				} else {
					if (data.data) {
						$('#article_text').html(data.data.article_text)
						$('#article_title').val(data.data.article_title)
						$('#article_id').val(data.data.article_id)
						$('#article_resume').val(data.data.article_resume)
					}
				}
			} else {
			}
		}});
	}
        }
        function saveArticle() {
        	if ($('#article_title').val().length>0) {
        	if ($('#article_id').val().length>0) {
        		saveAction({article_id:$('#article_id').val(),article_title:$('#article_title').val(),article_resume:$('#article_resume').val(),article_text:$('#article_text').html()})
        	}else{
        		if (confirm("Ar norite sukurti naują straipsnį?")) {
        			saveAction({article_title:$('#article_title').val(),article_resume:$('#article_resume').val(),article_text:$('#article_text').html()})
        		}
        	}
        	}else{
        		alert('Straipsni neturi  pavadinimo!')
        	}
        }
        function saveAction(data) {
        	var surl = "/admin/save-article";
        	$.ajax({type:'POST', url:surl, data:data, success:function (d) {
			var data = jQuery.parseJSON(d);
			if (data) {
				if (data.status == "1") {
					if (data.errors[0].type == "authentication") {
						showLogin();
						return;
					}
				} else {
					if (data.data) {
						$('#article_text').html(data.data.article_text)
						$('#article_title').val(data.data.article_title)
						$('#article_id').val(data.data.article_id)
						$('#article_resume').val(data.data.article_resume)
					}
				}
			} else {
			}
		}});
        }
        function deleteArticle() {
        }
        function loadArticlesList() {
	var surl = "/admin/load-articles";
	 $('#article_list').html("")
	if ($('#article_cat').val()) {
		$.ajax({type:'POST', url:surl, data:{article_cat:$('#article_cat').val()}, success:function (d) {
			var data = jQuery.parseJSON(d);
			if (data) {
				if (data.status == "1") {
					if (data.errors[0].type == "authentication") {
						showLogin();
						return;
					}
				} else {
					if (data.data) {
						for (var i=0;i<data.data.length;i++) {
							
							 $('#article_list').append(
							 	
									$('<option></option>').val(data.data[i].article_id).html(data.data[i].article_title)
							 );
						}
					}
				}
			} else {
			}
		}});
	}
}

</script>


