<div id="style_info_container" class="inner_container">
	<div class="inner_header">Administravimas - alaus stiliai</div>
	<div>
		Išversta <?= $this->total_translated["count"];?> iš <?= count($this->beer_styles)?> (<?= round($this->total_translated["count"]/count($this->beer_styles)*100)?> %)
		<div>
			<b><span style="color:brown">Vertėjų dėmesiui!</span></b> prie verčiamo stiliaus nurodykite, kategoriją kuriai stilius priklauso. Bei įveskite angliško teksto variantą. <br />
			<b>Dėkui! :)</b>
		</div>
	</div>
	<div>
		<div style="float: left; width: 300px;">
			<ul>
				<?
				for ($i=0;$i<count($this->beer_styles);$i++) {
					?>
					<li>
						<a href="?style_id=<?=$this->beer_styles[$i]['style_id'];?>">
							<?=$this->beer_styles[$i]['style_name'];?>
						</a>
					</li>
					<?
				}
				?>
			</ul>
		</div>
		<div style="float: left; width: 530px;">
			<? if ($this->current_style) { ?>
				<form id="styles_form" action="/admin/mod-styles" method="POST">
					<div style="font-weight: bold; font-size: 14px;">Stilius:</div>
					<div>
						<input style="width: 250px;" type="text" id="style_name" name="style_name" value="<?= addslashes($this->current_style["style_name"]);?>" />
						<input style="width: 250px;" type="text" id="style_name_en" name="style_name_en" value="<?= addslashes($this->current_style["style_name_en"]);?>">
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Kategorija:</div>
					<div>
						<select style="width: 510px;" id="style_cat" name="style_cat">
							<option value="0"></option>
							<?
							for ($i=0;$i<count($this->beer_cats);$i++) {
								?>
								<option value="<?=$this->beer_cats[$i]["cat_id"];?>" <?= ($this->current_style["style_cat"]==$this->beer_cats[$i]["cat_id"]) ? "selected" : "";?>>
									<?=$this->beer_cats[$i]["cat_name_en"];?>
								</option>
								<?
							}
							?>
						</select>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Aromatas:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_aroma" name="style_aroma">
							<?= $this->current_style["style_aroma"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_aroma_en" name="style_aroma_en">
							<?= $this->current_style["style_aroma_en"];?>
						</textarea>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Burnos pojūtis:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_mouthfeel" name="style_mouthfeel">
							<?= $this->current_style["style_mouthfeel"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_mouthfeel_en" name="style_mouthfeel_en">
							<?= $this->current_style["style_mouthfeel_en"];?>
						</textarea>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Išvaizda:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_appearance" name="style_appearance">
							<?= $this->current_style["style_appearance"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_appearance_en" name="style_appearance_en">
							<?= $this->current_style["style_appearance_en"];?>
						</textarea>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Skonis:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_flavor" name="style_flavor">
							<?= $this->current_style["style_flavor"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_flavor_en" name="style_flavor_en">
							<?= $this->current_style["style_flavor_en"];?>
						</textarea>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Sudėtis:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_ingredients" name="style_ingredients">
							<?= $this->current_style["style_ingredients"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_ingredients_en" name="style_ingredients_en">
							<?= $this->current_style["style_ingredients_en"];?>
						</textarea>
					</div>
					<div style="font-weight: bold; font-size: 14px; margin-top: 10px;">Istorija:</div>
					<div>
						<textarea style="width: 250px; height: 100px;" id="style_history" name="style_history">
							<?= $this->current_style["style_history"];?>
						</textarea>
						<textarea style="width: 250px; height: 100px;" id="style_history_en" name="style_history_en">
							<?= $this->current_style["style_history_en"];?>
						</textarea>
					</div>
					<input type="submit" class="ui-button" value="Saugoti">
					<input type="hidden" name="style_id" value="<?=$this->current_style["style_id"];?>"/>
				</form>
			<?}?>			
		</div>
		<div class="clear"></div>
	</div>
</div>
