# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 23 Nov 2012 15:19:40 +0000
*               @ALL          1
*               @user         8
*               @admin        16
