<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Fri, 23 Nov 2012 15:19:40 +0000
 */
$conf['title'] = 'Atviras Alus';
$conf['lang'] = 'lt';
$conf['license'] = 'cc-by-nc-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
