<?php
$this->headTitle()->headTitle("Alaus stiliai");
?>
<div class="inner_container" id="beer_styles_container">
	<?php
	$style_cat = -1;
	$yeasts_cat = -1;
	for ($i = 0; $i < count($this->beer_styles); $i++) {
		if ($yeasts_cat != $this->beer_styles[$i]["yeast_cat"]) {
			?>
			<div class="style_category">
				<h1>
					<?= $this->beer_styles[$i]["yeast_cat_name"]; ?>
				</h1>
			</div>
			<?php
		}
		$yeasts_cat = $this->beer_styles[$i]["yeast_cat"];
		if ($style_cat != $this->beer_styles[$i]["style_cat"]) {
			?>
			<div class="style_name">
				<h2>
					<?= $this->beer_styles[$i]["cat_name"]; ?>
				</h2>
			</div>
			<div class="style_subs">
		<?php
		}
		$style_cat = $this->beer_styles[$i]["style_cat"];
		?>
		<div class="subcat_name">
			<h3>
				<a href="/stilius/<?= $this->beer_styles[$i]['style_id']; ?>-<?= urlencode(implode("_", explode("/", $this->beer_styles[$i]['style_name']))); ?>">
				<?= $this->beer_styles[$i]['style_name']; ?> 
				</a>
			</h3> 
			(<?= $this->beer_styles[$i]['count']; ?>)
		</div>
		<?
		if (isset($this->beer_styles[$i + 1])) {
			if ($this->beer_styles[$i + 1]["style_cat"] != $style_cat) {
				?>
			</div>
				<?
			}
		}
	}
?> 
</div>