<?php
$this->headTitle()->append(" Stilius: " . $this->current_style['style_name']);
$this->headMeta()->setName('keywords', 'alaus stilius, skonis, apyniai, mielės, salyklas,alaus gamyba,naminis,receptai,receptas,alus,skaičiuoklė,ibu,ebc,abv,' . $this->current_style['style_name']);
$dfields = array(
	"style_aroma",
	"style_appearance",
	"style_flavor",
	"style_mouthfeel",
	"style_ingredients",
);
$description = false;
foreach ($dfields as $dfield) {
	if (strlen($this->current_style[$dfield]) > 0) {
		$description = true;
		break;
	}
}
?>
<script type="text/javascript">
	$(function(){
		$(".ttip_og").simpletip({
			content: '<b>Pradinis tirštumas</b> (angl. <i>original gravity</i>, <i>OG</i>). Misos specifinis tirštumas prieš fermentaciją. Šis matas nurodo cukringųjų medžiagų, būsiančių perdirbtų į alkoholį, kiekį – kuo tirštesnė misa, tuo stipresnis alus gausis.',
			fixed: false
		});
		$(".ttip_fg").simpletip({
			content: '<b>Galutinis tirštumas</b> (angl. <i>final gravity</i>, <i>FG</i>). Misos specifinis tirštumas fermentacijos pabaigoje.',
			fixed: false
		});
		$(".ttip_abv").simpletip({
			content: '<b>Alkoholio kiekis pagal tūrį</b> (angl. <i>Alcohol By Volume</i>, <i>ABV</i>, <i>v/v</i>). Alaus stiprumas išreiškiamas procentais.',
			fixed: false
		});
		$(".ttip_ibu").simpletip({
			content: '<b>Kartumo vienetai</b> (angl. <i>International Bittering Units</i>, <i>IBU</i>). Standartinis alaus kartumo matavimo skalės vienetas, žymintis apynių apimtį ir intensyvumą.',
			fixed: false
		});
		$(".ttip_ebc").simpletip({
			content: '<b>Spalva</b> (angl. <i>EBC</i>). Šiuo atveju alaus spalvos standartas pagal European Brewery Convention (Europos Aludarių Konvencija)',
			fixed: false
		});
	})
</script>
<div id="style_info_container" class="inner_container">
	<div class="inner_header">
		<h1>
			<?= $this->current_style['style_name']; ?>
		</h1>
	</div>
	<?php
	if ($description):
	?>
		<div id="style_description">
			<?php
			if (!empty($this->current_style["style_aroma"])):
			?>
				<div class="description_block">
					<div class="description_title">Aromatas</div>
					<div class="description_content"><?= $this->current_style["style_aroma"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			if (!empty($this->current_style["style_appearance"])):
			?>
				<div class="description_block">
					<div class="description_title">Išvaizda</div>
					<div class="description_content"><?= $this->current_style["style_appearance"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			if (!empty($this->current_style["style_flavor"])):
			?>
				<div class="description_block">
					<div class="description_title">Skonis</div>
					<div class="description_content"><?= $this->current_style["style_flavor"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			if (!empty($this->current_style["style_mouthfeel"])):
			?>
				<div class="description_block">
					<div class="description_title">Burnos pojūtis</div>
					<div class="description_content"><?= $this->current_style["style_mouthfeel"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			if (!empty($this->current_style["style_ingredients"])):
			?>
				<div class="description_block">
					<div class="description_title">Sudedamosios dalys</div>
					<div class="description_content"><?= $this->current_style["style_ingredients"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			if (!empty($this->current_style["style_history"])):
			?>
				<div class="description_block">
					<div class="description_title">Istorija</div>
					<div class="description_content"><?= $this->current_style["style_history"]; ?></div>
					<div class="clear"></div>
				</div>
			<?php
			endif;
			?>
		</div>
	<?php
	endif;
	?>
	<div id="style_params">
		<div class="params_block">
			<div class="params_title"><span class="ttip ttip_og"><b>OG:</b></span></div>
			<div class="params_content"><?= $this->current_style["style_oglow"]; ?> - <?= $this->current_style["style_oghigh"]; ?></div>
			<div class="clear"></div>
		</div>
		<div class="params_block">
			<div class="params_title"><span class="ttip ttip_fg"><b>FG:</b></span></div>
			<div class="params_content"><?= $this->current_style["style_fglow"]; ?> - <?= $this->current_style["style_fghigh"]; ?></div>
			<div class="clear"></div>
		</div>
		<div class="params_block">
			<div class="params_title"><span class="ttip ttip_abv"><b>ABV (%):</b></span></div>
			<div class="params_content"><?= round(Entities_BrewCalc::abv($this->current_style["style_oglow"] * 100, $this->current_style["style_fglow"] * 100), 1); ?> - <?= round(Entities_BrewCalc::abv($this->current_style["style_oghigh"] * 100, $this->current_style["style_fglow"] * 100), 1); ?></div>
			<div class="clear"></div>
		</div>
		<div class="params_block">
			<div class="params_title"><span class="ttip ttip_ibu"><b>Kartumas:</b></span></div>
			<div class="params_content"><?= $this->current_style["style_ibulow"]; ?> - <?= $this->current_style["style_ibuhigh"]; ?> IBU</div>
			<div class="clear"></div>
		</div>
		<div class="params_block">
			<div class="params_title"><span class="ttip ttip_ebc"><b>Spalva:</b></span></div>
			<div class="params_content">
				<?php
				$step = $this->current_style["style_srmhigh"] / $this->current_style["style_srmlow"] / 10;
				$color = $this->current_style["style_srmlow"];
				for ($i = 0; $i < 10; $i++) {
					?>
					<div class="color_palette" style="background-color:<?= $this->colorHex($color, false);?>"></div>
					<?
					$color+=$step;
				}
				?>
				<div class="styles_color"><?= round($this->current_style["style_srmlow"] * 1.97); ?> - <?= round($this->current_style["style_srmhigh"] * 1.97); ?> EBC </div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<div id="style_recipes_container" class="inner_container">
	<div class="inner_header">Stiliaus receptai</div>
	<div class="style_recipes">
		<?php
		$i = 0;
		foreach ($this->content as $item):
			$i++;
		?>
			<div class="style_recipe">
				<?= $this->recipeItem($item); ?>
			</div>
		<?php
			if ($i == 3){
				$i = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		endforeach;
		?>
		<div class="clear"></div>
	</div>
	<div class="style_recipes_footer">
		<a href="/style/<?= $this->current_style['style_id']; ?>">
			Visi stiliaus "<?= $this->current_style['style_name']; ?>" receptai
		</a>
	</div>
</div>