<?php
$this->headTitle()->headTitle("Skaičiuoklės");
?>
<div id="calc1_container" class="inner_container">
	<div class="inner_header">Vandens temperatūros skaičiuoklė</div>
	<dl>
		<dt>Vandens salyklo santykis (l/kg):</dt>
		<dd><input type="text" name="mash_ratio" id="mash_ratio" value="2.5" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Pageidaujama salinimo temperatūra (C):</dt>
		<dd><input type="text" name="mash_temp" id="mash_temp" value="65" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Salyklo temperatūra (C):</dt>
		<dd><input type="text" name="grain_temp" id="grain_temp" value="20" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><input type="button" value="Skaičiuoti" onClick="strikeCalc()" class="ui-button" /></dd>
		<div class="clear"></div>
	</dl>
	<div id="strike_temp" style="display: none;">&nbsp </div>
</div>

<div id="calc2_container" class="inner_container">
	<div class="inner_header">Verdančio vandens kiekio skaičiuoklė temperatūrai pasiekti</div>
	<dl>
		<dt>Salyko kiekis (kg):</dt>
		<dd><input type="text" name="bw_mash_weight" id="bw_mash_weight" value="5" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Vandens salyklo santykis (l/kg):</dt>
		<dd><input type="text" name="bw_mash_ratio" id="bw_mash_ratio" value="2.5" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Dabartinė mentalo temperatūra (C):</dt>
		<dd><input type="text" name="bw_cur_mash_temp" id="bw_cur_mash_temp" value="65" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Pageidaujama temperatūra (C):</dt>
		<dd><input type="text" name="bw_wanted_mash_temp" id="bw_wanted_mash_temp" value="78" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><input type="button" value="Skaičiuoti" onClick="restCalc()" class="ui-button" /></dd>
		<div class="clear"></div>
	</dl>
	<div id="bw_result" style="display: none;">&nbsp </div>
</div>

<div id="calc3_container" class="inner_container">
	<div class="inner_header">Alkoholio procento tūryje skaičiuoklė (ABV)</div>
	<dl>
		<dt>Pradinis tankis (OG):</dt>
		<dd><input id="sg" name="sg" onchange="display_ABV()" style="width: 60px;" value="1040" type="text" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Galutinis tankis (FG):</dt>
		<dd><input id="fg" name="fg" onchange="display_ABV()" style="width: 60px;" type="text" value="1008" /></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><input type="button" value="Skaičiuoti" onClick="display_ABV()" class="ui-button" /></dd>
		<div class="clear"></div>
	</dl>
	<div id="abv" style="display: none;">&nbsp </div>
</div>

<div class="ui-corner-all" style="background:#ffffff;width:800;padding:10">


<script type="text/javascript">
	function strikeCalc(strike) {
		var m_r=parseFloat($('#mash_ratio')[0].value)
		var m_t=parseFloat($('#mash_temp')[0].value)
		var g_t=parseFloat($('#grain_temp')[0].value)

		if (m_r<=0 | isNaN(m_r)) {
			$('#strike_temp')[0].innerHTML="<span class='cErr'>Vandens ir salyklo santykis turi būti didesnis už 0!</span>";
			return
		}
		if (m_t<=0 | isNaN(m_t)) {
			$('#strike_temp')[0].innerHTML="<span class='cErr'>Mentalo temperatūra turi būti aukštesnė už 0!</span>";
			return
		}
		if (g_t<=0 | isNaN(g_t)) {
			$('#strike_temp')[0].innerHTML="<span class='cErr'>Salyklo temperatūra turi būti aukštesnė už 0!</span>"
			return
		}

		if (m_t>100) {
			$('#strike_temp')[0].innerHTML="<span class='cErr'>Mentalo temperatūra turi būti žemesnė už virimo (100C)!</span>"
			return
		}
		if (g_t>100) {
			$('#strike_temp')[0].innerHTML="<span class='cErr'>Salyklo temperatūra turi būti žemesnė už virimo  (100C)!</span>"
			return
		}
		var Ts=m_t+.4*(m_t-g_t)/m_r+1.7
		$('#strike_temp')[0].innerHTML= "<span class='cResult'>Užpilamo vandens temperatūra turi būti "+Math.round(Ts)+"C.</span>";
		$('#strike_temp').show();
	}
	
	function restCalc(rest) {
		var Wg=parseFloat($('#bw_mash_weight')[0].value)
		var MWR=parseFloat($('#bw_mash_ratio')[0].value)
		var Tm=parseFloat($('#bw_cur_mash_temp')[0].value)
		var Tn=parseFloat($('#bw_wanted_mash_temp')[0].value)

		if (Wg<=0 | isNaN(Wg)) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Salyklo kiekis turi būti didesnis už 0 kg!</span>"
			return
		}
		if (MWR<=0 | isNaN(MWR)) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Vandens ir salyklo santykis turi būti didesnis už 0!</span>"
			return
		}
		if (Tm<=0 | isNaN(Tm)) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Dabartinė mentalo temperatūra turi būti aukštesnė už 0!</span>"
			return
		}
		if (Tn<=0 | isNaN(Tn)) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Pageidaujama mentalo temperatūra turi būti aukštesnė už 0!</span>"
			return
		}
		if (Tm>=Tn) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Pageidaujama mentalo temperatūra turi būti aukštesnė už dabartinę temperatūra</span>"
			return
		}
	
		if (Tm>100) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Dabartinė temperatūra turi būti žemesnė už virimo (100C)!</span>"
			return
		}
		if (Tn>100) {
			$('#bw_result')[0].innerHTML= "<span class='cErr'>Pageidaujama temperatūra turi būti žemesnė už virimo (100C)!</span>"
			return
		}
		var Vm=Wg*(.4+MWR)
		var Vs=Vm*(Tn-Tm)/(100-Tn)
		$('#bw_result')[0].innerHTML= "<span class='cResult'>Pasiekti "+Tn+"C. temperatūrą reikės "+(Math.round(Vs)*100/100)+" litrų verdančio (100C) vandens</span>"
		$("#bw_result").show();
	}
	function calc_ABV(sg,fg) {
		return  (sg - fg )  * 0.131
	}

	function display_ABV() {

		var sg=parseFloat($("#sg")[0].value);

		var fg=parseFloat($("#fg")[0].value);

		if (Number(sg) && Number(fg) ) {

			$("#abv")[0].innerHTML="<span class='cResult'>ABV: "+(Math.round(calc_ABV(sg,fg)*100)/100) + " %</span>";

		}else{
			$("#abv")[0].innerHTML="<span class='cErr'>Neteisingai įvesti laukai</span>";
		}
		$("#abv").show();

	}
	function display_DrinkUnits() {
		var ml=parseFloat($("#drink_ml")[0].value);

		var abv=parseFloat($("#drink_abv")[0].value);

		if (Number(ml) && Number(abv) ) {
			$("#drink_units")[0].innerHTML="<span class='cResult'>"+(Math.round(ml*abv/1000*100)/100) + " </span>";
		}else{
			$("#drink_units")[0].innerHTML="<span class='cErr'>Neteisingai įvesti laukai</span>";
		}
	}
</script>