<form action="/idejos/nauja" method="post" target="_self" name="__ideaForm" id="__ideaForm" enctype="multipart/form-data">
	<dl>
		<dt>Antraštė <span>*</span></dt>
		<dd>
<input type="text" name="title" id="title" value=""></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Santrauka <span>*</span></dt>
		<dd>
<textarea name="description" id="description" rows="24" cols="80"></textarea></dd>
		<div class="clear"></div>
	</dl>
	<dl>
		<dt>Detalus aprašymas</dt>
		<dd class="large">
<textarea name="full_text" id="full_text" rows="24" cols="80"></textarea></dd>
		<div class="clear"></div>
	</dl>
	
	<dl>
		<dt>&nbsp;</dt>
		<dd>
<input type="submit" name="attributes_action" id="attributes_action" value="Saugoti" type="submit" class="ui-button"></dd>
		<div class="clear"></div>
	</dl>
</form>