<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Aludarių grupės</div>
	<div>
		<?
		for ($i = 0; $i < count($this->groups); $i++) {
			?>
			<div class="usergroup_title"><?= $this->groups[$i]["group_name"]; ?></div>
			<div class="usergroup_avatars">
				<?
				$z = 0;
				for ($ii = 0; $ii < count($this->groups[$i]["users"]); $ii++) {
					$z++;
					?>
					<a href="/brewers/<?= $this->groups[$i]['users'][$ii]['user_id']; ?>">
						<img src="http://www.gravatar.com/avatar/<?= md5($this->groups[$i]['users'][$ii]['user_email']); ?>?rating=G&size=50&default=mm" border="0"/>
						<span><?= $this->groups[$i]['users'][$ii]['user_name']; ?>
					</a>
					<?
					if ($z == 8) {
						$z = 0;
						?>
						<div class="clear"></div>
						<?php
					}
				}
				?>
				<div class="clear"></div>
			</div>
			<div class="usergroup_actions">
				<a href="/mail/compose?token=<? print urlencode(base64_encode($this->groups[$i]['group_name'])); ?>" rel="nofollow">
					Rašyti grupei žinutę
				</a>
			</div>
			<?
		}
		?>
	</div>
	<div class="inner_footer">* prie grupės prisijungti galite, savo paskyros nustatymuose</div>
</div>