<div id="brewer_session_container" class="inner_container">
    <div class="usergroup_title"><?= $this->group["group_name"]; ?></div>
        <div class="usergroup_avatars">
                    <?
                    $z = 0;
                    for ($ii = 0; $ii < count($this->group_users); $ii++) {
                            $z++;
                            ?>
                            <a href="/brewers/<?= $this->group_users[$ii]['user_id']; ?>">
                                    <img src="http://www.gravatar.com/avatar/<?= md5($this->group_users[$ii]['user_email']); ?>?rating=G&size=50&default=mm" border="0"/>
                                    <span><?= $this->group_users[$ii]['user_name']; ?>
                            </a>
                            <?
                            if ($z == 8) {
                                    $z = 0;
                                    ?>
                                    <div class="clear"></div>
                                    <?php
                            }
                    }
                    ?>
                    <div class="clear"></div>
            </div>
            <div class="event_list_container">
		<?
		$z = 0;
		foreach ($this->group_events as $item) {
			$z++;
			?>
			<div class="event_block" onclick="window.location.href='/ivykis/<?= $item["event_id"]; ?>-<?= urlencode($item["event_name"]); ?>'">
				<div class="event_title">
					<?= $item["event_name"]; ?>
				</div>
				<div class="event_resume">
					<?= $item["event_resume"]; ?>
				</div>
				<div class="event_date">
					Data: <span><?= $item["event_start"]; ?></span>
				</div>
			</div>
			<?
			if ($z == 3){
				$z = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		}
		?>
		<div class="clear"></div>
	</div>
            <div class="usergroup_actions">
                    <a href="/mail/compose?token=<? print base64_encode($this->group['group_name']); ?>" rel="nofollow">
                            Rašyti grupei žinutę
                    </a>
                
                 <a href="/events/create-event?group_id=<?=$this->group["group_id"];?>" rel="nofollow">
                            Sukurti grupės įvykį
                    </a>
          </div>
</div>
