<?php
$this->headTitle()->headTitle("Kaip naudotis alaus recepto skaičiuokle");
?>
<div id="help_container" class="inner_container">
	<div class="inner_header">Kaip naudotis "Atviras alus" alaus recepto skaičiuokle</div>
	<div style="font-size: 14px;">
		<p style="text-align: center"><img src="/public/images/faq/1.jpg" style="border: 1px solid #ccc;" /></p>
		<p>
			Pirmą kartą pamačius atrodo baisiai, nesuprantamai ar ne? Pamėginsim
			trumpai apžvelgti šitą "įrankį", kad nebūtų taip baisu pačiam 
			surikiuot alaus receptą.
		</p>
		<p>
			Pirmiausiai reiktų nusistatyti matavimo sistemą, naudojamą Jūsų 
			hidrometro, jei tokį turite. Jei nenaudojate hidrometro, tiesiog 
			palikite matavimo sistemos nustatymus kaip yra. Kitu žingsniu 
			pasirinkite norimo virti alaus kiekį, išreikštą litrais, bei 
			nusistatykite virimo laiką (minutėmis). Virimo laiką pradžiai 
			palikite 60 minučių. Kitus du parametrus, "Efektyvumas" ir 
			"Atenuacija", kolei kas ignoruokite, apie juos paaiškinsime vėliau. 
			Tiesa, dar yra laukelis "Pritaikyti". Jis reikalingas tik tuomet, 
			kai Jūs norite savo, jau sudarytą ir išmėgintą receptą, pritaikyti 
			kitokiam alaus kiekiui. Tiesiog įveskite norimą kiekį (litrais) ir 
			spustelėkite "Pritaikyti".
		</p>
		<p style="text-align: center"><img src="/public/images/faq/2.jpg" style="border: 1px solid #ccc;" /></p>
		<p>
			Dabar reiktų apsispręsti, kokio stiliaus alų Jūs norėtumėte išvirti.
			Ko gero tai pats sunkiausias momentas, neskaitant pavadinimo, kurį 
			privalomai reiktų įrašyti raudonai pažymėtame laukelyje. Trumpai 
			apie alaus stilius galite <a href="/styles">pasiskaityti čia</a>. Jei ir paskaičius nesate
			tikri, kokio stiliaus yra Jūsų norimas išvirti alus, pasirinkite 
			"Kitoks alus", neapsiriksite.
		</p>
		<p>
			Jūs paklausite: negi aš namie (bute) galiu išsivirti mano taip 
			mėgstamo ..... alaus? Tyčia palikome daugtaškį, mes gi nežinome, 
			kokį alų Jūs mėgstate. O atsakymas į klausimą: TAIP! Tik viskas 
			priklauso nuo Jūsų noro išsivirti alų, Jūsų kruopštumo ir.... be 
			abejo sėkmės.
		</p>
		<p>
			Na bet gana, žygiuojam toliau.
		</p>
		<p style="text-align: center"><img src="/public/images/faq/3.jpg" style="border: 1px solid #ccc;" /></p>
		<p>
			Dabar gi Jūs turite pasirinkti salyklą, kurį naudosite, bei jo 
			kiekį. Ekstraktingumo ir spalvos laukelį kol kas palikime ramybėje. 
			Kiekvieną norimą salyklo rūšį įrašysite atskira eilute paspaudę 
			mygtuką "Pridėti salyklą".
		</p>
		<p>
			Kuo daugiau salyklo naudosite, tuo alus bus stipresnis. Tik nereikia
			persistengt ir daryt 20 litrų alaus pavyzdžiui iš 5 kg karamelinio 
			CaraPils salyklo. Paprastai alaus pagrindui naudojamas taip vadinami
			pagrindiniai salyklai su protingu kiekiu karamelinių ar skrudintų 
			salyklų. Taip pat gali būti pridedama įvairių dribsnių ar cukraus, 
			bet vėlgi protingais kiekiais.
		</p>
		<p>
			Pagrindiniai salyklai tai visi skaičiuoklėje esantys "pale ale", 
			pilsnerio salyklai, "Vienos" bei "Miuncheno" salyklai. Prie 
			pagrindinių galima priskirti ir kvietinį salyklą, jei formuosite 
			kvietinio alaus receptą. Įrašas "Bazinis salyklas" – paprastai 
			naudojamas receptuose, kai nėra tiksliai žinoma kas tai per salyklas
			arba kai nėra jokio skirtumo, kurį iš pagrindinių salyklų naudoti. 
			Kaip pagrindinis salyklas gali būti traktuojamas ir skystas salyklo
			ekstraktas. Taigi su salyklais išsiaiškinome, žygiuojam toliau.
		</p>
		<p style="text-align: center"><img src="/public/images/faq/4.jpg" style="border: 1px solid #ccc;" /></p>
		<p>
			Čia Jūs turite pasirinkti norimus naudoti apynius, jų kiekį, 
			nurodyti "Alfa %", bei kiek laiko žadate virti minėtus apynius. 
			Principas toks pat kaip ir su salyklais: kiekviena apynių rūšis su 
			norimu virti laiku įtraukiama atskira eilute paspaudus mygtuką 
			"Pridėti apynius".
		</p>
		<p>
			"Alfa %" – tai alfa rūgšties kiekis apyniuose, išreikštas 
			procentais. Paprastai perkant apynius jis būna nurodytas ant 
			pakuotės.
		</p>
		<p>
			Kiek laiko virti apynius bendros taisyklės nėra. Kuo ilgesnį laiką 
			virsite apynius, tuo alus bus kartesnis. Sąlyginis alaus kartumas 
			atsispindi parametre IBU, kurį skaičiuoklė apskaičiuoja priklausomai
			nuo apynių "Alfa %", kiekio ir virimo laiko. Kitaip sakant daugiau 
			"Alfa%" – daugiau kartumo, didesnis apynių kiekis – daugiau kartumo, 
			ilgiau virsit – daugiau kartumo.
		</p>
		<p>
			Apyniai naudojami virimo pabaigoje (15-0 min) suteikia alui daugiau 
			aromato.
		</p>
		<p>
			Su apyniais išsiaiškinom, liko paskutinis punktas – mielės.
		</p>
		<p style="text-align: center"><img src="/public/images/faq/5.jpg" style="border: 1px solid #ccc;" /></p>
		<p>
			Čia viskas labai paprasta. Tiesiog išsirinkite Jūsų norimas naudoti 
			mieles ir tiek.
		</p>
		<p>
			Štai ir viskas, receptas suformuotas. Išsaugokite receptą, paspaudę 
			mygtuką "Saugoti". Tik neužmirškite receptui suteikti pavadinimą. 
			Ką gi, beliko išvirti alų, naudojantis Jūsų sukurtu receptu.
		</p>
		<p style="text-align: center">
			<b>!!!!Geros Jums alaus putos!!!!</b>
		</p>
	</div>
</div>