<div id="help_container" class="inner_container">
	<div class="inner_header">Pagalba</div>
	<div><a href="/auth/remember">Pamiršau slaptažodį</a></div>
	<div style="margin-top: 10px; color: brown">
		Pastebėta, jog registruojantis @gmail pašto adresu, nautotojai negauna el. pašto patvirtinančio jų registracijos.
		Gmail pašto sistema šiuos laiškus traktuoja kaip spam'ą, todėl prašome pastitkrinti savo spam folderį.
		Atsiprašome už nepatogumus. Tikimes, jog perkelus svetainę į naują serverį šios problemos išvengti
	</div>
	<div style="margin-top: 10px;">
		Klausimams ir pasiūlymams 
		<a href="mailto:%69%6e%66%6f%40%61%74%76%69%72%61%73%61%6c%75%73%2e%6c%74">
			info<!-- --><!-- --><!-- --><!-- --><!-- -->@<!-- -->atvirasalus.lt<!-- -->
		</a>
	</div>
</div>