<div id="articles_container" class="inner_container">
	<div class="inner_header">Skaitykla</div>
	<?php
	foreach ($this->content as $item) {
		?>
		<div class="article_title_url">
			<a href="/content/read/<?=$item['article_cat'];?>/<?=$item['article_id'];?>-<?=$item['article_title'];?>">
				<?=$item['article_title'];?>
			</a>
			<span style="font-size: 12px;">(<?=intval($item['total']);?>)</span>
			<img src="/public/images/comments_icon.png" />
		</div>
		<div class="article_content">
			<?=$item['article_resume'];?>
		</div>
		<?
	}
	?>
	<div><?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?></div>
</div>