
<div class="ui-corner-all" style="background:#ffffff;display: inline-block; padding:10;width:750">
<div align="center"><h2>Skaitykla</h2></div>
<table>
<?
$z=0;
$r=0;
$u_per_row=5;
foreach ($this->content as $item) {?>
<tr>
<td style="padding-bottom:20">
<div><a  style="font-size:13;font-weight:bold" href="/content/read/<?=$item['article_cat'];?>/<?=$item['article_id'];?>-<?=$item['article_title'];?>"><?=$item['article_title'];?></a> (<?=intval($item['total']);?>)<img src="/public/images/comments_icon.png" border=0/> </div>
<div><?=$item['article_resume'];?></div>

</td>
</tr>
<?
}   
?>  
   
</table>

<?php echo $this->paginationControl($this->content,
                                    'Sliding',
                                    'paginator/item.phtml'); ?>
</div>
