<div id="help_container" class="inner_container">
	<div class="inner_header">Parama</div>
	<div>
		<p>Ši interneto svetainė veikia nuomojamame serveryje, kuris mums kas mėnesį kainuoja po 80 Lt + PVM = 96.80 Lt.</p>
		<p>Jūs galite prisidėti prie svetainės išlaikymo siūsdami SMS žinutes. 100% SMS vertės patenka į serveriai.lt sąskaitą, o tuos pinigėlius galime panaudoti (TIK) esamų paslaugų pratęsimui.</p>
		<p>Kiekvieną mėnesį įsipareigojame pateikti kiek pinigų buvo paaukota ir kiek jų liko po paslaugų pratęsimo (jei liks)</p>
		<p>Norėdami paremti atvirasalus.lt svetainę:</p>
		<ol>
			<li>Parašykite SMS žinutę su kodu <b>IV STYXAS</b>. Tarp žodžių IV ir STYXAS palikite tarpą, rašyti galite didžiosiomis arba mažosiomis raidėmis (pvz., iv styxas).</li>
			<li>Nusiųskite šią žinutę kuriuo nors iš žemiau nurodytų numerių.<br /><br />
				<b>1679</b> -	3 Lt<br />
				<b>1654</b> -	2 Lt<br />
				<b>1656</b> -	1 Lt<br />&nbsp;
			</li>
			<li>Štai ir viskas! Jūsų sumokėti pinigai (3 Lt, 2 Lt arba 1 Lt) bus iš karto padovanoti projektui, o jūs gausite patvirtinimą, kad žinutė sėkmingai pasiekė tikslą.</li>
		</ol>
		<p>Jūsų paramą 100% galėsime panaudoti projekto išlaikymui (jokia dalis neatitenka operatoriams ar pan.).</p>
		<p>Paramos ataskaitoje matysime jūsų telefono numerį ir padovanotą lėšų sumą. Jei pageidaujate, SMS žinutėje galite papildomai įrašyti savo naudotojo vardą - ne anoniminius remėjus paskelbsime kas mėnesį (pvz., <b>IV STYXAS naudotojas</b>).</p>
		<p>Puslapyje atvaizduojama surinkta paramos suma atnaujinama 10-ies minučių intervalu.</p>
		<p>Mokėjimas už serverį atliekamas kiekvieno mėnesio 10 d.</p>
	</div>
</div>