<?php
$this->headTitle()->headTitle("Parama");
?>
<div id="help_container" class="inner_container">
	<div class="inner_header">Parama</div>
	<div>
		<p>Ši interneto svetainė veikia nuomojamame serveryje, kuris mums kas mėnesį kainuoja po 80 Lt + PVM = 96.80 Lt.</p>
		<p>Jūs galite prisidėti prie svetainės išlaikymo siūsdami SMS žinutes. 100% SMS vertės patenka į serveriai.lt sąskaitą, o tuos pinigėlius galime panaudoti (TIK) esamų paslaugų pratęsimui.</p>
		<p>Panaudojus sukauptus pinigus paslaugų pratęsimui įsipareigojame pateikti kiek pinigų buvo paaukota ir kiek jų liko.</p>
		<p>Norėdami paremti atvirasalus.lt svetainę parašykite žinutę vienu iš šių numerių:</p>
		<table border="1" cellspacing="0" cellpadding="4">
			<tr>
				<td><b>Numeris</b></td>
				<td><b>Žinutės tekstas</b></td>
				<td><b>Kaina</b></td>
			</tr>
			<tr>
				<td>1656</td>
				<td>IV STYXAS</td>
				<td>1 Lt</td>
			</tr>
			<tr>
				<td>1654</td>
				<td>IV STYXAS</td>
				<td>2 Lt</td>
			</tr>
			<tr>
				<td>1679</td>
				<td>IV STYXAS</td>
				<td>3 Lt</td>
			</tr>
			<tr>
				<td>1679</td>
				<td>IV10 STYXAS</td>
				<td>10 Lt</td>
			</tr>
			<tr>
				<td>1679</td>
				<td>IV15 STYXAS</td>
				<td>15 Lt</td>
			</tr>
		</table>
		<p><b>Tarp žodžių IV ir STYXAS palikite tarpą, rašyti galite didžiosiomis arba mažosiomis raidėmis</b></p>
		<p>Štai ir viskas! Jūsų sumokėti pinigai (15 Lt, 10 Lt, 3 Lt, 2 Lt arba 1 Lt) bus iš karto padovanoti projektui, o jūs gausite patvirtinimą, kad žinutė sėkmingai pasiekė tikslą.</p>
		<p>Jūsų paramą 100% galėsime panaudoti projekto išlaikymui (jokia dalis neatitenka operatoriams ar pan.).</p>
		<p>Paramos ataskaitoje matysime jūsų telefono numerį ir padovanotą lėšų sumą. Jei pageidaujate, SMS žinutėje galite papildomai įrašyti savo naudotojo vardą - ne anoniminius remėjus paskelbsime kas mėnesį (pvz., <b>IV STYXAS naudotojas</b>).</p>
		<p>Puslapyje atvaizduojama surinkta paramos suma atnaujinama 10-ies minučių intervalu.</p>
	</div>
</div>