<?php
$this->headTitle()->headTitle("Naudojimosi sąlygos");
?>
<div id="help_container" class="inner_container">
	<div class="inner_header">"Atviras alus" svetainės naudojimosi sąlygos</div>
	<div class="policy_list">
		<p>Naudodamiesi „Atviras alus“ bendruomenės svetaine Jūs sutinkate su žemiau pateiktomis taisyklėmis, priešingu atveju nerekomenduojame registruotis šioje svetainėje bei naudotis jos turiniu.</p>
		<ol>
			<li>
				Privatumas, dalinimasis informacija bei turiniu
				<ol>
					<li>
						Jūs sutinkate, kad visa Jūsų talpinama informacija atitinka <a href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)</a> licencijos sąlygas. Pagrindinės licencijos nuostatos
						<ol>
							<li>kiti asmenys turi teisę naudotis Jūsų informacija, ja dalintis bei platinti</li>
							<li>kiti asmenys turi teisę kopijuoti ir keisti Jūsų informaciją</li>
							<li>kiti asmenys turi teisę naudoti Jūsų informaciją komerciniais tikslais</li>
							<li>jei kiti asmenys kuria informaciją ar turinį Jūsų informacijos pagrindu, jie privalo savo kūrinį platinti tos pačios licencijos pagrindu</li>
						</ol>
					</li>
					<li>Jūs patvirtinate, kad suprantate, jog Jūsų pačių ištrinta informacija gali būti ir toliau saugoma atsarginėse sistemos kopijose (neprieinamose tretiesiems asmenims).</li>
					<li>Talpindami viešą informaciją Jūs patvirtinate, kad suprantate jog ji bus prieinama visiems, įskaitant ir svetainės lankytojus neregistruotus šioje sistemoje.</li>
					<li>„Atviras alus“ administracija labai vertina Jūsų pastangas siekiant plėtoti bendruomenę bei mielai priima pasiūlymus ir idėjas jos tobulinimui. Jūs patvirtinate, jog suprantate, kad svetainės administracija pasilieka sau teisę naudotis šiais pasiūlymais be įsipareigojimo už juos atsilyginti bet kokia forma (Jūs nesate įpareigoti teikti tokius siūlymus)</li>
				</ol>
			</li>
			<li>
				Saugumas
				<ol>
					<li>
						„Atviras alus“ administratoriai siekia užtikrinti saugų naudojimąsi bendruomenės svetaine, tačiau negali garantuoti visiško saugumo. Tuo pačiu svarbus ir Jūsų indėlis, todėl Jūs įsipareigojate:
						<ol>
							<li>Be administratorių leidimo neskelbti komercinės informacijos, tokios kaip brukalas (angl. spam)</li>
							<li>Jūs nerinksite informacijos apie naudotojus, o taip pat naudotojų pateikiamos informacijos automatinėmis priemonėmis (tokiomis kaip robot'ai, bot'ai, spider'iai arba scraper'iai) be atskiro administratorių leidimo.</li>
							<li>Jūs netalpinsite informacijos galinčios pakenti svetainės lankytojams ar jų naudojamai įrangai (pvz. virusais užkrėstus failus).</li>
							<li>Jūs neprašysite svetimų prisijungimo duomenų bei nesinaudosite svetimomis naudotojų paskyromis.</li>
							<li>Jūs netalpinsite įžeidžiančios, nešvankios, vulgarios, šmeižiančios, grasinančios ar kitokios Lietuvos Respublikos bei Europos Sąjungos įstatymus pažeidžiančios informacijos.</li>
							<li>Jūs nenaudosite „Atviras alus“ svetainės Lietuvos Respublikos bei Europos Sąjungos įstatymus pažeidžiančiais tikslais.</li>
							<li>Jūs nedarysite veiksmų kurie galėtų sutrikdyti „Atviras alus“ sistemos veikimą</li>
							<li>Jūs sutinkate, kad Jūsų kompiuteryje gali būti saugomi slapukai (angl. Cookies)</li>
						</ol>
					</li>
					<li>
						Registruodamiesi „Atviras alus“ svetainėje Jūs patvirtinate, kad:
						<ol>
							<li>Jūs nekursite sau daugiau nei vienos paskyros</li>
							<li>Jūs nesinaudosite svetaine jei jums nėra 18-os metų</li>
							<li>Jūs nesinaudosite svetaine jei buvote teistas dėl Lietuvos Respublikos Alkoholio kontrolės įstatymo pažeidimų</li>
							<li>Jūs neplatinsite savo prisijungimo duomenų kitiems asmenims bei nesuteiksite galimybės kitiems asmenims naudotis sistema Jūsų vardu</li>
						</ol>
					</li>
					<li>
						Siekiant užtikrinti kitų naudotojų teisių apsaugą, Jūs patvirtinate, kad:
						<ol>
							<li>Jūs netalpinsite turinio kuris gali pažeisti kitų asmenų teises</li>
							<li>Administratoriai pasilieka teisę pašalinti bet kokią informaciją, kuri jų nuomone pažeidžia arba gali pažeisti šiuos reikalavimus.</li>
							<li>Jūs nenaudosite „Atviras alus“ ženklų, simbolikos ar kitų bendruomenės identifikavimo priemonių (tokių kaip pavadinimas „Atviras alus“, logotipas ir pan.) bet administratorių sutikimo.</li>
						</ol>
					</li>
				</ol>
			</li>
			<li>
				Pakeitimai
				<ol>
					<li>Administratoriai pasilieka teisę keisti šias taisykles, apie tai pranešę įrašu svetainėje arba elektroniniu paštu.</li>
					<li>Bet kokie sąlygų pakeitimai įsigalioja ne anksčiau kaip per 7 kalendorines dienas nuo jų paskelbimo.</li>
				</ol>
			</li>
		</ol>
		<p style="font-style: italic">Šios taisyklės paskelbtos 2012 metų lapkričio 22 dieną ir įsigalioja nuo 2013 metų sausio 1 dienos.</p>
	</div>
</div>