<?php
$this->headTitle()->headTitle("Pagalba");
?>
<div id="help_container" class="inner_container">
	<div class="inner_header">Pagalba</div>
	<div>
		<p><a href="/content/faq">Kaip naudotis "Atviras alus" alaus recepto skaičiuokle?</a></p>
		<p><a href="/auth/remember">Pamiršau slaptažodį</a></p>
	</div>
	<div style="margin-top: 10px; color: brown">
		Pastebėta, jog registruojantis @gmail pašto adresu, nautotojai negauna el. pašto patvirtinančio jų registracijos.
		Gmail pašto sistema šiuos laiškus traktuoja kaip spam'ą, todėl prašome pastitkrinti savo spam folderį.
		Atsiprašome už nepatogumus. Tikimes, jog perkelus svetainę į naują serverį šios problemos išvengti
	</div>
	<div style="margin-top: 10px;">
		Klausimams ir pasiūlymams 
		<a href="mailto:%61%74%76%69%72%61%73%61%6C%75%73%2E%6C%74%40%67%6D%61%69%6C%2E%63%6F%6D">
			atvirasalus.lt<!-- --><!-- --><!-- --><!-- --><!-- -->@<!-- -->gmail.com<!-- -->
		</a>
	</div>
</div>