<p>
<h2>Pagalba</h2>
<div><a href="auth/remember">Pamiršau slaptažodį</a></div>
<div>Kaip pasikeist slaptažodį (tekstas kuriamas)</div>
<div>Kaip sukurti receptą (tekstas kuriamas)</div>
<div style="padding-top:20;width:800;color:#922C12"><i>
Pastebėta, jog registruojantis @gmail pašto adresu, vartotojai negauna el. pašto patvirtinančio jų registracijos.
Gmail pašto sistema šiuos laiškus traktuoja kaip spam'ą, todėl prašome pastitkrinti savo spam folderį.
Atsiprašome už nepatogumus. Tikimes, jog perkelus svetainę į naują serverį šios problemos išvengti</i>
</div>
</p>
