<?
$this->headScript()->appendFile("/public/ui/external/jqcloud-0.1.8.min.js");
$this->headLink()->appendStylesheet("/public/ui/external/jqcloud.css");
?>
<style type="text/css">
      
      #wordcloud {
        margin: 30px auto;
        width: 800px;
        height: 600px;
        border: none;
      }
      #wordcloud span.w10, #wordcloud span.w9, #wordcloud span.w8, #wordcloud span.w7 {
        text-shadow: 0px 1px 1px #ccc;
      }
      #wordcloud span.w3, #wordcloud span.w2, #wordcloud span.w1 {
        text-shadow: 0px 1px 1px #fff;
      }
      #footer {
        font-size: 13px;
        color: #aaa;
        text-align: center;
        width: 600px;
        margin: 30px auto;
        padding: 0.5em;
        text-shadow: 0px 1px 1px #fff;
        border-top: 1px dotted #ddd;
      }
      #footer a {
        color: #0af;
        text-decoration: none;
      }
    </style>

<script>
 
 word_list=[];   
<?
for ($i=0;$i<count($this->words);$i++) {
?>
word_list.push({text: "<?=addslashes($this->words[$i]['recipe_name']);?>", weight: Math.random(1,5), url: ""});
<?
}
?>  
$(document).ready(function() {
        $("#wordcloud").jQCloud(word_list);
      });
</script>
<div id="wordcloud"></div>
