<?php
if (isset($this->content)) {
	?>
	<div class="inner_container" id="favorites_container">
		<div class="inner_header">Įdomiausi alaus receptai</div>
		<?
		$z=0;
		foreach ($this->content as $item) {
			$z++;
			?>
			<div class="favorites_list_item">
					<?=$this->recipeItem($item,"thumb");?>
			</div>
		<?
		}
		?>
		<?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?>
	</div>
<?
}
?>