<script type="text/javascript">
	$(function(){
	});
</script>
<div id="style_info_container" class="inner_container">
	<div class="inner_header"><h1>Alaus galerija</h1></div>
	<div class="beer_images">
		<?php
		foreach ($this->content as $img) {
			?>
			<div class="beer_image">
				<div>
					<a title="<?=$img['recipe_name']?>, <?=$img['user_name']?>, <?=$img['postedf']?>" rel="gallery" class="fancybox" href="/recipe_images/<?=$img['recipe_id']?>/<?=$img['file_name']?>.jpg"><img src="/recipe_images/<?=$img['recipe_id']?>/t_<?=$img['file_name']?>.jpg" alt="" /></a>
				</div>
			</div>
			<?
		}
		?>
		<div class="clear"></div>
	</div>
	<?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?>
</div>