<?php
$this->headTitle()->append(" - Receptai ");
$this->headMeta()->setName('keywords', 'alaus gamyba,naminis,receptai,receptas,alus');
if (isset($this->content)) {
	?>
	<div class="inner_container" id="favorites_container">
		<?php
		if (isset($this->beer_style)) {
			?>
			<div class="inner_header">Kategorijos <a href="/stilius/<?=$this->beer_style['style_id'];?>">"<?=$this->beer_style['style_name'];?>"</a> receptai</div>
			<?
		} else {
			?>
			<div class="inner_header">Alaus receptai</div>
			<div class="recipe_list_tags">
				<ul>
					<?
					for ($i=0;$i<count($this->tags);$i++) {
						?>
						<li style="font-size:<?=(80+min($this->tags[$i]['weight']*20,200));?>%">
							<a href="/search/tags:<?=$this->tags[$i]['tag_text'];?>">
								<?=$this->tags[$i]['tag_text'];?>
							</a>
						</li>
						<?
					}
					?>
				</ul>
			</div>
			<?
		}
		$z=0;
		foreach ($this->content as $item) {
			$z++;
			?>
			<div class="favorites_list_item">
					<?=$this->recipeItem($item,"thumb");?>
			</div>
		<?
		}
		?>
		<?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?>
	</div>
<?
}
?>
