<script type="text/javascript">
	$(function(){
		$("#recipe_order").change(function(){
			$("#recipe_order_form").submit();
		});
	});
</script>
<?php
$this->headTitle()->append(" - Receptai ");
$this->headMeta()->setName('keywords', 'alaus gamyba,naminis,receptai,receptas,alus');
if (isset($this->content)) {
	?>
	<div class="inner_container" id="favorites_container">
		<?php
		if (isset($this->beer_style)) {
			?>
			<div class="inner_header">Kategorijos <a href="/stilius/<?=$this->beer_style['style_id'];?>">"<?=$this->beer_style['style_name'];?>"</a> receptai</div>
			<?
		} else {
			?>
			<div class="inner_header">Alaus receptai</div>
			<div class="recipe_list_tags">
				<ul>
					<?
					for ($i=0;$i<count($this->tags);$i++) {
						?>
						<li style="font-size:<?=(80+min($this->tags[$i]['weight']*20,200));?>%">
							<a href="/search/tags:<?=$this->tags[$i]['tag_text'];?>">
								<?=$this->tags[$i]['tag_text'];?>
							</a>
						</li>
						<?
					}
					?>
				</ul>
			</div>
			<?
		}
		?>
		<div class="recipe_order_block">
			<form id="recipe_order_form" method="post" action="">
				Rikiuoti receptus pagal
				<select name="recipe_order" id="recipe_order">
					<option value="posted" <?=($this->order == "posted") ? "selected='selected'" : "v"; ?>>sukūrimo datą</option>
					<option value="title" <?=($this->order == "title") ? "selected='selected'" : "v"; ?>>pavadinimą</option>
					<option value="sessions" <?=($this->order == "sessions") ? "selected='selected'" : "v"; ?>>virimų kiekį</option>
					<option value="lastsession" <?=($this->order == "lastsession") ? "selected='selected'" : "v"; ?>>paskutinio virimo datą</option>
					<option value="likes" <?=($this->order == "likes") ? "selected='selected'" : "v"; ?>>"patinka" kiekį</option>
					<option value="awards" <?=($this->order == "awards") ? "selected='selected'" : "v"; ?>>apdovanojimų kiekį</option>
					<option value="comments" <?=($this->order == "comments") ? "selected='selected'" : "v"; ?>>komentarų kiekį</option>
				</select>
			</form>
		</div>
		<?php
		$z=0;
		foreach ($this->content as $item) {
			$z++;
			?>
			<div class="favorites_list_item">
					<?=$this->recipeItem($item,"thumb");?>
			</div>
		<?
		}
		?>
		<?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?>
	</div>
<?
}
?>
