<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="lt" lang="lt">
    <head>
        <title>Alaus receptas</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
                      @page 
        {
            size: auto;   /* auto is the initial value */
            margin: 0mm;  /* this affects the margin in the printer settings */
        }
			@media print {
body { background:white; margin:0px }
}
		</style>

<meta name="description" content="Atviras alus - Atsispausk savo alaus etiketę" />
<script type="text/javascript" src="/public/js/jquery-1.4.4.min.js"></script>
<script src="/public/jcanvas/jcanvas.js"></script>
<link type="text/css" href="/public/css/main.css" rel="stylesheet" />
<link type="text/css" href="/public/css/pepper-grinder/jquery-ui-1.8.7.custom.css" rel="stylesheet" />	
<script src="/public/jcanvas/qr.js"></script>
<style>
.ptr td{ border-bottom:1px dotted #666666;
         border-left:1px dotted #666666;
        vertical-align: top;
        
}
#printTable {
    border-top:1px dotted #666666;
    border-right:1px dotted #666666;
}

input {border:1px solid #ededed; font-size:11px}
select {border:1px solid #ededed;font-size:11px}
button {border:1px solid #ededed;font-size:11px}
label {vertical-align: top}

#canvasControlsTable tr {height:50}
#canvasControlsTable tr td label {color:#666}
#canvasControlsTable tr td  {width:200px;text-align:right}
#canvasControlsTable tr td input {width:200px}
</style>
<script>
$.jCanvas.extend({
  name: "wrapText",
  props: {
    prop: true
  },
  fn: function(ctx, params) {
   var words = params.text.split(" ");
	
    var line = "";
	ctx.fillStyle = params.fillStyle;
	ctx.strokeStyle = params.strokeStyle;
	ctx.textBaseline = params.baseline;
	ctx.textAlign = params.align;
	ctx.font = params.font;
    for (var n = 0; n < words.length; n++) {
        var testLine = line + words[n] + " ";
        var metrics = ctx.measureText(testLine);
        var testWidth = metrics.width;
        if (testWidth > params.maxWidth) {
            ctx.fillText(line, params.x, params.y);
            line = words[n] + " ";
            params.y += params.lineHeight;
        }
        else {
            line = testLine;
        }
    }
    ctx.fillText(line, params.x, params.y);
  }
});
function addNull(_str) {
_str=String(_str)
if (_str.length<2) {
return "0"+_str
}
return _str
}
function getCurrentDate() {
var dt=new Date();
return [dt.getFullYear(),addNull(dt.getMonth()+1),addNull(dt.getDate())].join(".")
}
function drawCircle(x, y, radius, fill) {
	$("canvas").drawArc({fillStyle:fill, x:x, y:y, radius:radius, start:0, end:Math.PI, ccw:true, inDegrees:false});
	$("canvas").drawArc({fillStyle:fill, x:x, y:y, radius:radius, start:Math.PI, end:0, ccw:true, inDegrees:false});
}
function drawPattern(color, scolor,x, y, width, height) {
	$("canvas").drawRect({strokeStyle:scolor, fillStyle:color, strokeWidth:1, x:x, y:y, width:width, height:height, fromCenter:false,cornerRadius:10});
}
function drawTitle() {
  	COLOR_SCHEME_ID= COLOR_SCHEME_ID==undefined ? 0 : COLOR_SCHEME_ID
	
	var x = 0;
	var y = 0;
	var cW = $("canvas").width();
	var cH = $("canvas").height();
	
	
	var cmargin = 8;
	
	var cheight = 82
	var cstroke = COLOR_SCHEME[COLOR_SCHEME_ID].colors[0]

	//_qrbbit = cstroke.split("#").join("0x")
	
	var cx = cmargin, cy = cH-cheight-cmargin*7;
	
	drawPattern("#fff",cstroke, cx, cy, cheight, cheight);
	$("canvas").drawText({fillStyle:cstroke, strokeWidth:1, x:cx+cheight/2, y:cy+cheight/2, text:recipe_data.recipe_abv + "%", align:"center", baseline:"middle", font:"15pt Courier New, Courier, monospace"});
	var cx = cmargin*2+cheight
	drawPattern(cstroke,cstroke, cx, cy, cheight, cheight);
        $("canvas").drawText({fillStyle:"#fff", strokeWidth:1, x:cx+cheight/2, y:cy+cheight/2, text:recipe_data.recipe_ibu + "ibu", align:"center", baseline:"middle", font:"15pt Courier New, Courier, monospace"});
	var cx = cmargin*3+cheight*2
	drawPattern("#fff", cstroke,cx, cy, cheight, cheight);
	$("canvas").drawText({fillStyle:cstroke, strokeWidth:1, x:cx+cheight/2, y:cy+cheight/2, text:recipe_data.recipe_ebc + "ebc", align:"center", baseline:"middle", font:"15pt Courier New, Courier, monospace"});
	//data
	$("canvas").rotateCanvas({
	  angle: -90,
	  x: cW/2, y: cH/2
	})
	textSize=8;
	tx = cH*0.6
      
	ty =cW - 83
	$("canvas").drawText({fillStyle:cstroke, strokeWidth:0, x:tx, y:ty, text:recipe_data.recipe_date, align:"start", baseline:"middle", font:textSize + "pt Calibri, monospace"}).restoreCanvas();
       
	var cx = cmargin*4+cheight*3
	_blackBit=cstroke;
	
	<? if ($this->recipe['recipe_id']>0) {?>
	var rurl="http://www.atvirasalus.lt/alus/receptas/<?=$this->recipe['recipe_id'];?>";
	<?}else {?>
	var rurl="http://www.atvirasalus.lt/";
	<?}?>

	$("canvas").drawImage({source:create_qrcode(rurl), x:cx, y:cy, width:82, height:82, fromCenter:false});
	drawPattern("", cstroke,cx, cy, cheight, cheight);
	textSize = Math.max(16, Math.round($("canvas").width() * 80 / 100 / recipe_data.recipe_name.length));
	textSize=Math.min(25,textSize)
	var tx = $("canvas").width() * 50 / 100, ty = $("canvas").height() * 15 / 100;
	var lineHeight=textSize*105/100
	$("canvas").wrapText({fillStyle:cstroke,lineHeight:lineHeight+5,maxWidth:$("canvas").width()*80/100, strokeWidth:0, x:tx, y:ty, text:recipe_data.recipe_name, align:"center", baseline:"middle", font:textSize + "pt Calibri, monospace"});
	
	ty = cH - cmargin*3
	tx = cmargin*2;
	textSize=8;
	$("canvas").wrapText({fillStyle:cstroke, strokeWidth:0, x:tx, y:ty, text:recipe_data.recipe_style, align:"start", baseline:"middle", font:textSize + "pt Calibri, monospace"});
	
	
}
function drawFrame(patt) {
$("canvas").drawRect({fillStyle:"#fff",strokeStyle:"#fff",  strokeWidth:1, x:0, y:0, width:$("canvas").width(), height:$("canvas").height(), fromCenter:false});
drawTitle();
	//
	
}
create_qrcode = function (text, typeNumber, errorCorrectLevel) {
	
	var qr = qrcode(typeNumber || 4, errorCorrectLevel || 'M');
	qr.addData(text);
	qr.make();
	
	//	return qr.createTableTag();
	return qr.createImgData();
};
function paintCanvas() {
	$("canvas").clearCanvas();
	drawFrame();
}
function initCanvas() {
	
	for (var z in recipe_data) {
		$('#' + z).val(recipe_data[z]);
	}
	
	for (var i=0;i<COLOR_SCHEME.length;i++) {
    $("#label_color").append("<option value='"+i+"'>"+COLOR_SCHEME[i].label+"</option>");
	}
	paintCanvas();
}
COLOR_SCHEME_ID=0
COLOR_SCHEME = [];
//rusva

COLOR_SCHEME.push({label:"Juoda", colors:["#000000"]});
COLOR_SCHEME.push({label:"Šviesiai ruda", colors:[ "#A67A00"]});
COLOR_SCHEME.push({label:"Žalia", colors:["#7F9F00"]});
COLOR_SCHEME.push({label:"Melsva", colors:["#008787"]});

var recipe_data = {recipe_date:getCurrentDate(),recipe_ibu:"<?=$this->recipe["recipe_ibu"];?>", recipe_abv:"<?=$this->recipe["recipe_abv"];?>", recipe_ebc:"<?=$this->recipe["recipe_ebc"];?>", recipe_name:"<?=addslashes($this->recipe["recipe_name"]);?>", recipe_style:"<?=addslashes($this->recipe["style_name"]);?>"};
$(initCanvas);
function refreshCanvas() {
	for (var z in recipe_data) {
		recipe_data[z] = $('#' + z).val();
	}
	COLOR_SCHEME_ID= $("#label_color").val();
	paintCanvas();
}
function getCanvasURL() {
	return $("canvas")[0].toDataURL("image/png", true);
}
function generatePrint() {
	img = getCanvasURL();
	$("#canvasTable").remove();
	t = $("body").append("<table id='printTable' celppading='0' cellspacing='0'>");
	for (var i = 0; i < 4; i++) {
		$('#printTable').append("<tr  class='ptr' id='ptr" + i + "' height='"+$("canvas").height()+"'>");
		for (var ii = 0; ii < 2; ii++) {
			$('#ptr' + i).append("<td valign='top'><img src='" + img + "'></td>");
		}
	}
}
</script>
</head>
<body style="background:#fff;margin: 0px;vertical-align:top;">
<div id="canvasTable" style="padding:50px" align="center">
<table  class="ui-corner-all" style="background:#F1F0ED;border:1px solid #666" ><tr><td  width="400" align="center"> <canvas width="380" height="230" id="canvas"></canvas></td>
<td align="right">
<table width="200" id="canvasControlsTable" class="ui-corner-all">
<tr>
<td>
<label for="label_color">Spalvų schema</label>
<select id="label_color"></select>
</td>
</tr>
<tr>
<td>
<label for="recipe_name">Alaus pavadinimas</label>
<input type="text" value="recipe_name" id="recipe_name"/>
</td>
</tr>
<tr>
<td>
<label for="recipe_style">Alaus stilius</label>
<input type="text" value="recipe_style" id="recipe_style"/>
</td>
</tr>
<tr>
<tr>
<td>
<label for="recipe_date">Data</label>
<input type="text" value="recipe_date" id="recipe_date"/>
</td>
</tr>
<td>
<label for="recipe_abv">ABV</label>
<input type="text" value="recipe_abv" id="recipe_abv"/>
</td>
</tr>
<tr>
<td>
<label for="recipe_ibu">IBU</label>
<input type="text" value="recipe_ibu" id="recipe_ibu"/>
</td>
</tr>
<tr>
<td>
<label for="recipe_ebc">EBC</label>
<input type="text" value="recipe_ebc" id="recipe_ebc"/>
</td>
</tr>
<tr>
<td>
<button onClick="refreshCanvas()">Atnaujinti</button>
<button onClick="generatePrint()">Spausdint</button></td>
</tr>
</table>
</td>
</tr></table>
</div>
</body>
</html> 
