<?php
$this->headTitle()->headTitle($this->data['recipe']['recipe_name']);
?>
<script src="/public/colorbox/colorbox/jquery.colorbox.js"></script>
<link rel="stylesheet" href="/public/colorbox/colorbox.css" />
<script>
	$(function(){
		$("#recipe_share").click(function(){
			$("#recipe_share_dialog").dialog({ modal: true, width: 430, title: "Nuoroda į receptą", buttons: { "Uždaryti": function() { $(this).dialog("close"); } } });
			$("#recipe_share_dialog textarea").select();
			return false;
		});
		$("#recipe_image_form").submit(function(){
			if ($("#recipe_image").val() != ""){
				var ext = $('#recipe_image').val().split('.').pop().toLowerCase();
				if($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
					alert('Draudžiama įkelti "'+ext+'" tipo failus');
					return false;
				}
			} else {
				alert('Nepasirinkote failo');
				return false;
			}
			return true;
		});
		$(".del_image").click(function(){
			if (confirm("Ar tikrai norite ištrinti nuotrauką?")) { 
				return true;
			}
			return false;
		});
		$(".fancybox").colorbox({
			maxWidth: "80%",
			maxHeight: "80%",
			scrolling: false,
			current: "{current}/{total}"
		});
		$(".ttip_efektyvumas").simpletip({
			content: '<b>Efektyvumas</b> (angl. <i>Efficiency</i>; <i>Extraction efficiency</i>). Cukringų medžiagų "išplovimo" iš salyklo efektyvumas. Tai yra santykis cukraus, kurį iš tikrųjų "išplovėt" , su teoriškai didžiausiu įmanomu "išplauti" cukraus kiekiu.',
			fixed: false
		});
		$(".ttip_atenuacija").simpletip({
			content: '<b>Atenuacija</b>, <b>silpimas</b> (angl. <i>Attenuation</i>). Misos tirštumo mažėjimas, joje esančias cukringąsias medžiagas fermentacijos būdu perdirbant į alkoholį ir angliarūgštę. Alus laikomas pasiekęs galutinę atenuaciją, kai mielės daugiau nebegali fermentuoti saldžiųjų medžiagų.<br /><br /><b>Tariama atenuacija</b> (angl. <i>Apparent attenuation</i>). Paprastas fermentacijos, kurią patyrė misa virsdama alumi, lygio išraiškos būdas. Naudojant Gravity Units (GU), Balling (B) arba Plato (P) vienetus išreikšti tirštumui, tariama atenuacija yra lygi iš pradinio tirštumo atėmus galutinį tirštumą ir padalinus iš pradinio tirštumo. Rezultatas išreiškiamas procentais ir daugumai alaus rūšių yra lygus 65-80%.',
			fixed: false
		});
		$(".ttip_matavimosistema").simpletip({
			content: '<b>Matavimo systema</b>. Misos tirštumo, potencialaus alaus stiprumo po fermentacijos, matavimo sistema.<br /><br /><b>°Plato</b>, <b>Balingas</b>, <b>°Balling</b>. Misos tirštumo, taigi ir potencialaus alaus stiprumo po fermentacijos, mato vienetas. Balling matavimo sistema buvo sukurta čeko aludarystės mokslininko Carl Joseph Napoleon Balling. Vėliau patobulinta į °Plato.<br /><br /><b>Specifinis tirštumas</b>, <b>cukringumas</b> (angl. <i>specific gravity</i>, <i>SG</i>). Misos matas, nurodantis jos tirštumą (kietųjų medžiagų kiekį).',
			fixed: false
		});
		$(".ttip_og").simpletip({
			content: '<b>Pradinis tirštumas</b> (angl. <i>original gravity</i>, <i>OG</i>). Misos specifinis tirštumas prieš fermentaciją. Šis matas nurodo cukringųjų medžiagų, būsiančių perdirbtų į alkoholį, kiekį – kuo tirštesnė misa, tuo stipresnis alus gausis.',
			fixed: false
		});
		$(".ttip_fg").simpletip({
			content: '<b>Galutinis tirštumas</b> (angl. <i>final gravity</i>, <i>FG</i>). Misos specifinis tirštumas fermentacijos pabaigoje.',
			fixed: false
		});
		$(".ttip_abv").simpletip({
			content: '<b>Alkoholio kiekis pagal tūrį</b> (angl. <i>Alcohol By Volume</i>, <i>ABV</i>, <i>v/v</i>). Alaus stiprumas išreiškiamas procentais.',
			fixed: false
		});
		$(".ttip_ibu").simpletip({
			content: '<b>Kartumo vienetai</b> (angl. <i>International Bittering Units</i>, <i>IBU</i>). Standartinis alaus kartumo matavimo skalės vienetas, žymintis apynių apimtį ir intensyvumą.',
			fixed: false
		});
		$(".ttip_ebc").simpletip({
			content: '<b>Spalva</b> (angl. <i>EBC</i>). Šiuo atveju alaus spalvos standartas pagal European Brewery Convention (Europos Aludarių Konvencija)',
			fixed: false
		});
		$(".ttip_ibuog").simpletip({
			content: '<b>IBU/OG balansas</b> (angl. <i>IBU/Gravity ratio</i>). Kartumo ir pradinio tirštumo santykis. Išskaičiuojamas, sąlyginis vienetas apsprendžiantis tariamą burnos kartumo pojūtį.',
			fixed: false
		});
		$(".ttip_ekstraktingumas").simpletip({
			content: '<b>Ekstraktingumas</b> (tech) (angl. <i>extraction rate</i>). Kramolingųjų medžiagų kiekio, paverstų į fermentuojamąsias cukringąsias medžiagas salinimo metu, matas.',
			fixed: false
		});
		$(".ttip_alfa").simpletip({
			content: '<b>Alfa rūgštys</b> (angl. <i>alpha acids</i>, <i>AA</i>). Esminis kartumo šaltinis, gaunamas iš apynių, izomerizuojant juos virimo būdu.',
			fixed: false
		});
		
		$("#vote_up_button").click(function(){
			$("#vote_icon").html("<img src='/public/images/spinner.gif'/>");
			$("span#votes_count").fadeOut("fast");
			$.ajax({
				type: "POST",
				data: "action=vote_up&id=<?=$this->data['recipe']['recipe_id'];?>",
				url: "/recipes/vote",
				success: function(msg){
					$("#vote_icon").html('<img src="/public/images/thumb_up.png">');
					var data = jQuery.parseJSON(msg);
					if (data) {
						$("span#votes_count").html(data.data.votes);
						$("span#votes_count").fadeOut();
						$("span#votes_count").fadeIn();
					}
					$("#vote_button").html("Nepatinka");
					$("#vote_down_button").css("display","inline");
					$("#vote_up_button").css("display","none");
				}
			});
		});

		$("#vote_down_button").click(function(){
			the_id = $(this).attr('id');
			$("#vote_icon").html("<img src='/public/images/spinner.gif'/>");
			$.ajax({
				type: "POST",
				data: "action=vote_down&id=<?=$this->data['recipe']['recipe_id'];?>",
				url: "/recipes/vote",
				success: function(msg){
					var data = jQuery.parseJSON(msg);
					$("#vote_icon").html('<img src="/public/images/thumb_up.png">');
					$("#vote_up_button").css("display","inline");
					$("#vote_down_button").css("display","none");
					if (data) {
						$("span#votes_count").html(data.data.votes);
						$("span#votes_count").fadeOut();
						$("span#votes_count").fadeIn();
					}
				}
			});
		});
	});
</script>

<?php
function i_bu($ibu,$og) {
	$bu = round($ibu/(($og*1000)-1000),2);
	if ($bu >= 0 && $bu <= 0.19) {
		return "kartumo nėra, dominuoja salyklas";
	} else if ($bu >= 0.2 && $bu <= 0.39) { 
		return "jaučiami apyniai, dominuoja salyklas";
	} else if ($bu >= 0.4 && $bu <= 0.59) { 
		return "kartumas ir salyklo skonis subalansuotas";
	} else if ($bu >= 0.6 && $bu <= 0.79) {
		return "ryškus apynių skonis";
	} else if ($bu >= 0.8 && $bu <= 100) {
		return "dominuoja apynių skonis";
	}
}
?>
<div id="style_info_container" class="inner_container">
	<div class="inner_header"><h1><?=$this->data['recipe']['recipe_name'];?></h1></div>
	<div class="recipe_tools_container">
		<? if ($this->data['recipe']['recipe_total_awards'] > 0) :?>
			<div class="recipe_awards">
				<?
				$awards = $this->awards[$this->data['recipe']['recipe_id']];
				foreach ($awards as $key=>$val):
					$title = $val['event_name'];
					if (!empty($val['category'])){
						$title .= ", ".$val['category'];
					}
					if (!empty($val['place'])){
						$title .= ", ".$val['place']." vieta";
					}
					if (!empty($val['points']) && $val['points'] != "0"){
						$title .= " (".$val['points']." tšk.)";
					}
					?>
					<img src="/public/images/<?= trim($val['icon']) ?>-32.gif" width="32" title="<?= trim($title) ?>" />
					<?
				endforeach;
				?>
			</div>
		<? endif; ?>
		<div class="recipe_tools">
			<?php
			if (isset($this->user_info->user_id) && $this->user_info->user_id == $this->data['recipe']['brewer_id']){
				?>
				<a href="#" id="recipe_share">Dalintis nuoroda</a>
				<div id="recipe_share_dialog" style="display: none;">
					<textarea style="width: 400px; height: 50px;">http://<?=$_SERVER['SERVER_NAME']?>/recipes/view/<?=$this->data['recipe']['recipe_id']?>-<?=$this->urlMaker($this->data['recipe']['recipe_name']);?>?auth_key=<?=md5($this->data['recipe']['recipe_id'].$this->data['recipe']['recipe_created'])?></textarea>
				</div>
				<?php
			}
			?>
			<a href="/recipes/print-label/?recipe_id=<?=$this->data['recipe']['recipe_id'];?>" target="_blank">Spausdinti etiketę</a>
			<a href="/brew-session/recipe/<?=$this->data['recipe']['recipe_id'];?>">Virimai (<?=$this->data['brew_session']['count'];?>)</a>
			<a href="/index/calculus/<?=$this->data['recipe']['recipe_id'];?><?=(isset($_GET['auth_key'])) ? "?auth_key=".$_GET['auth_key'] : ""; ?>">
				<?php
				if (isset($this->user_info->user_id) && $this->user_info->user_id == $this->data['recipe']['brewer_id']){
					echo "Redaguoti";
				} else {
					echo "Į skaičiuoklę";
				}
				?>
			</a>
			<a href="/index/print-recipe/?recipe_id=<?=$this->data['recipe']['recipe_id'];?><?=(isset($_GET['auth_key'])) ? "&auth_key=".$_GET['auth_key'] : ""; ?>" target="_blank">Spausdinti receptą</a>
			<?php
			if (isset($this->user_info)) {
				 /*
				?>
				<a href="/order/savasalus/<?=$this->data['recipe']['recipe_id']?>">Užsakyti ingridientus</a>
				<?php
				 */
				if ($this->recipe_votes["user_vote"]) {
					?>
					<a href='javascript:void(0);' id='vote_up_button' style="display:none">Patinka</a>
					<a href='javascript:void(0);' id='vote_down_button'>Nebepatinka</a>
					<?php 
				} else {
					?>
					<a href='javascript:void(0);' id='vote_down_button' style="display:none">Nebepatinka</a>
					<a href='javascript:void(0);' id='vote_up_button'>Patinka</a>
					<?
				}
            }
			?>
			<span id='votes_count'><?=$this->recipe_votes["total"];?></span>
			<div id='vote_icon'><img src="/public/images/thumb_up.png"  border="0" /></div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="recipe_info_container">
		<div class="recipe_info">
			<div class="recipe_info_block">
				<div class="recipe_info_label">Alaus kiekis:</div>
				<div class="recipe_info_text"><?=round($this->data['recipe']['recipe_batch'],1);?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label"><span class="ttip ttip_efektyvumas">Efektyvumas</span>:</div>
				<div class="recipe_info_text"><?=round($this->data['recipe']['recipe_efficiency'],2);?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label">Virimo laikas:</div>
				<div class="recipe_info_text"><?=$this->data['recipe']['recipe_boiltime'];?> min.</div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label"><span class="ttip ttip_atenuacija">Atenuacija</span>:</div>
				<div class="recipe_info_text"><?=round($this->data['recipe']['recipe_attenuation'],2);?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label">Stilius:</div>
				<div class="recipe_info_text"><h2><a href="/stilius/<? print $this->data['recipe']['recipe_style'];?>"><?=$this->data['recipe']['style_name'];?></a></h2></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label">Aludaris:</div>
				<div class="recipe_info_text"><a href="/brewers/<? print $this->data['recipe']['brewer_id'];?>"><?=$this->data['recipe']['user_name'];?></a></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_info_block">
				<div class="recipe_info_label">Receptas sukurtas:</div>
				<div class="recipe_info_text"><?=$this->data['recipe']['recipe_created'];?></div>
				<div class="clear"></div>
			</div>
			<?php
			if ($this->data['recipe']['recipe_modified'] != "0000-00-00 00:00:00"):
				?>
				<div class="recipe_info_block">
					<div class="recipe_info_label">Receptas modifikuotas:</div>
					<div class="recipe_info_text"><?=$this->data['recipe']['recipe_modified'];?></div>
					<div class="clear"></div>
				</div>
				<?php
			endif;
			if ($this->data['recipe']['recipe_publish'] != "1"):
				?>
				<div class="recipe_info_block">
					<div class="recipe_info_label">&nbsp;</div>
					<div class="recipe_info_text" style="margin-top: 5px; font-weight: bold; color: #ee0000">Receptas nėra viešas!</div>
					<div class="clear"></div>
				</div>
				<?php
			endif;
			?>
		</div>
		<div class="recipe_image">
			<div style="background-color:<?=$this->colorHex($this->data['recipe']['recipe_ebc']);?>"><img src="/public/images/glass_s.png" alt="<?=$this->data['recipe']['recipe_name'];?>" /></div>
		</div>
		<div class="clear"></div>
	</div>
	<div>
		<div class="recipe_ingridients_container">
			<div class="recipe_malts">
				<div class="ingridient_category">Salyklas</div>
				<?
				$total=0;
				foreach ($this->data['malt'] as $malt) {
					$total += floatval($malt['malt_weight']);
				}
				?>
				<div class="malt_item">
					<div class="title"><b>Pavadinimas</b></div>
					<div class="color"><span class="ttip ttip_ebc"><b>Spalva (EBC)</b></span></div>
					<div class="amount_w"><b>Kiekis (kg)</b></div>
					<div class="amount_p"><b>Kiekis (%)</b></div>
					<div class="clear"></div>
				</div>
				<?php 
				foreach ($this->data['malt'] as $malt) :
					?>
					<div class="malt_item">
						<div class="title"><?=$malt['malt_name'];?></div>
						<div class="color"><?=$malt['malt_ebc'];?></div>
						<div class="amount_w"><?=$malt['malt_weight'];?></div>
						<div class="amount_p"><?=round(floatval ($malt['malt_weight'])/$total*100,1);?></div>
						<div class="clear"></div>
					</div>
					<?php
				endforeach;
				?>
				<div class="malt_item">
					<div class="title">&nbsp;</div>
					<div class="color">&nbsp;</div>
					<div class="amount_w" style="border-top: 1px solid #999; padding-top: 5px;"><?=number_format($total, 3, '.', '');?></div>
					<div class="amount_p">&nbsp;</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="recipe_hops">
				<div class="ingridient_category2">Apyniai</div>
				<?
				$total=0;
				foreach ($this->data['hops'] as $hop) {
					$total += floatval($hop['hop_weight']);
				}
				?>
				<div class="hop_item">
					<div class="title"><b>Pavadinimas</b></div>
					<div class="alpha"><span class="ttip ttip_alfa"><b>Kartumas (AA%)</b></span></div>
					<div class="amount_w"><b>Kiekis (g)</b></div>
					<div class="time"><b>Laikas</b></div>
					<div class="clear"></div>
				</div>
				<?php 
				foreach ($this->data['hops'] as $hop) :
					?>
					<div class="hop_item">
						<div class="title"><?=$hop['hop_name'];?></div>
						<div class="alpha"><?=$hop['hop_alpha'];?></div>
						<div class="amount_w"><?=$hop['hop_weight'];?></div>
						<div class="time"><?=$hop['hop_time'];?></div>
						<div class="clear"></div>
					</div>
					<?php
				endforeach;
				?>
				<div class="hop_item">
					<div class="title">&nbsp;</div>
					<div class="alpha">&nbsp;</div>
					<div class="amount_w" style="border-top: 1px solid #999; padding-top: 5px;"><?=$total;?></div>
					<div class="time">&nbsp;</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="recipe_yeast">
				<div class="ingridient_category2">Mielės</div>
				<div class="yeast_item">
					<div class="title"><b>Pavadinimas</b></div>
					<div class="amount"><b>Kiekis (g)</b></div>
					<div class="clear"></div>
				</div>
				<?php 
				foreach ($this->data['yeast'] as $hop) :
					?>
					<div class="yeast_item">
						<div class="title"><?=$hop['yeast_name'];?></div>
						<div class="amount"><?=$hop['yeast_weight'];?></div>
						<div class="clear"></div>
					</div>
					<?php
				endforeach;
				?>
			</div>
			<div class="recipe_notes">
				<div class="ingridient_category2">Pastabos</div>
				<div><?=nl2br($this->data['recipe']['recipe_comments']);?></div>
			</div>
			<div class="recipe_tags">
				<? $this->headLink()->appendStylesheet("/public/ui/external/jquery.tagsinput.css"); ?>
				<? $this->headScript()->appendFile("/public/ui/external/jquery.tagsinput.min.js");  ?>
				<script>
				$(function() {
					$('#tags_input_field').tagsInput({
						width: 'auto',defaultText:'Nauja žyma',
						autocomplete_url:'/recipes/find?tags' // jquery ui autocomplete requires a json endpoint
					})
				});
				function showInput() {
					$("#tag_cloud").hide();
					$("#tag_input").show();
				}
				function hideInput() {
					$("#tag_cloud").show();
					$("#tag_input").hide();
				}
				function saveTags() {
					$("#tag_cloud").show();
					$("#tag_input").hide();
					$.ajax({type:"POST", data:"tags=" + $('#tags_input_field').val() + "&recipe_id=<?=$this->data['recipe']['recipe_id'];?>", url:"/recipes/mod-tags", success:function (msg) {
						var data = jQuery.parseJSON(msg);
						if (data) {
							var tags = data.tags.split(",");
							$("#tag_cloud").html('');
							$("#tags_input_field").val(data.tags);
							for (var i = 0; i < tags.length; i++) {
								$("#tag_cloud").append('<a href="/search/tags:' + tags[i] + '"><span style="font-weight:normal;padding:5;color:#7B4A12">' + tags[i] + '</span></a>');
							}
						}
					}});
				}
				</script>
				<?php
				$is_owner = false;
				if (isset($this->user_info)) {
					$is_owner = $this->user_info->user_id == $this->data['recipe']['brewer_id'];
				}
				if ($is_owner) {
					?>
					<div class="ingridient_category2">Žymos <a href="javascript:showInput()" style="font-size: 11px"> redaguoti </a></div>
					<?
				} else {
					?>
					<div class="ingridient_category2">Žymos</div>
					<?
				}
				?>
				<div id="tag_cloud">
					<?php
					$tags = explode(",", $this->tags);
					foreach ($tags as $value) {
						?>
						<a href="/search/tags:<?=$value;?>"><?=$value;?></a>
						<?php
					}
					?>
				</div>
				<div id="tag_input" style="display:none">
					<input id="tags_input_field" type="text" class="tags" value="<?=$this->tags;?>" />
					<div align="right">
						<input type="button" onClick="saveTags()" class="ui-button" value="saugoti" />
						<input type="button" onClick="hideInput()" class="ui-button" value="atšaukti" />
					</div>
				</div>
			</div>
			<div class="beer_images">
				<div class="ingridient_category2">Nuotraukos</div>
				<div>
					<?php
					foreach($this->images as $img){
						?>
						<div class="beer_image">
							<div>
								<a title="<?=$img['user_name']?>, <?=$img['postedf']?>" rel="gallery" class="fancybox" href="/recipe_images/<?=$this->data['recipe']['recipe_id']?>/<?=$img['file_name']?>.jpg"><img src="/recipe_images/<?=$this->data['recipe']['recipe_id']?>/t_<?=$img['file_name']?>.jpg" alt="" /></a>
							</div>
							<?php
							if (isset($this->user_info->user_id) && $this->user_info->user_id!=0 && ($this->user_info->user_id == $this->data['recipe']['brewer_id'] || $this->user_info->user_id == $img['user_id'])){
								?>
								<div>
									<a href="/alus/trinti_nuotrauka/<?=$img['id']?>" class="del_image">Trinti</a>
								</div>
								<?php
							} else {
								?>
								<div>&nbsp;</div>
								<?php
							}
							?>
						</div>
						<?php
					}
					?>
					<div class="clear"></div>
				</div>
				<?php
				if (isset($this->user_info->user_id) && $this->user_info->user_id!=0){
					?>
					<div>
						<form id="recipe_image_form" method="post" action="/recipes/upload_image" enctype="multipart/form-data">
							<dl>
								<dt>Įkelti nuotrauką:</dt>
								<dd><input name="recipe_image" id="recipe_image" type="file" /></dd>
								<div class="clear"></div>
							</dl>
							<dl>
								<dt>&nbsp;</dt>
								<dd>
									<input name="submit" type="submit" value="Įkelti" class="ui-button" />
									<input name="recipe_id" type="hidden" value="<?=$this->data['recipe']['recipe_id']?>" />
								</dd>
								<div class="clear"></div>
							</dl>
						</form>
					</div>
					<?php
				}
				?>
			</div>
			<div class="recipe_comments">
				<div class="ingridient_category2">Komentarai</div>
				<div><?=$this->recipeComments($this->data['recipe']['recipe_id']);?></div>
			</div>
		</div>
		<div class="recipe_result">
			<div class="recipe_result_block">
				<div class="recipe_result_label"><span class="ttip ttip_og"><b>OG:</b></span></div>
				<div class="recipe_result_text"><?=$this->usePlato($this->data['recipe']['recipe_sg'], true);?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_result_block">
				<div class="recipe_result_label"><span class="ttip ttip_fg"><b>FG:</b></span></div>
				<div class="recipe_result_text"><?=$this->usePlato($this->data['recipe']['recipe_fg'], true);?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_result_block">
				<div class="recipe_result_label"><span class="ttip ttip_abv"><b>ABV:</b></span></div>
				<div class="recipe_result_text"><?=$this->data['recipe']['recipe_abv'];?> %</div>
				<div class="clear"></div>
			</div>
			<div class="recipe_result_block">
				<div class="recipe_result_label"><span class="ttip ttip_ebc"><b>EBC:</b></span></div>
				<div class="recipe_result_text"><?=$this->data['recipe']['recipe_ebc'];?></div>
				<div class="clear"></div>
			</div>
			<div class="recipe_result_block">
				<div class="recipe_result_label"><span title="Kalorijų kiekis litre"><b>CAL/L:</b></span></div>
				<div class="recipe_result_text"><?=Entities_BrewCalc::calories($this->data['recipe']['recipe_sg'],$this->data['recipe']['recipe_fg']);?></div>
				<div class="clear"></div>
			</div>
			<?php
			if (count($this->data['hops'])>0){
				?>
				<div class="recipe_result_block">
					<div class="recipe_result_label"><span class="ttip ttip_ibu"><b>IBU:</b></span></div>
					<div class="recipe_result_text"><?=$this->data['recipe']['recipe_ibu'];?></div>
					<div class="clear"></div>
				</div>
				<div class="recipe_result_block">
					<div class="recipe_result_label"><span class="ttip ttip_ibuog"><b>IBU/OG:</b></span></div>
					<div class="recipe_result_text"><?=round($this->data['recipe']['recipe_ibu']/(($this->data['recipe']['recipe_sg']*1000)-1000),2);?></div>
					<div class="clear"></div>
				</div>
				<div class="recipe_result_block">
					<div class="recipe_i_bu"><?= i_bu($this->data['recipe']['recipe_ibu'],$this->data['recipe']['recipe_sg']);?></div>
				</div>
				<?php
			}
			?>
		</div>
		<div class="clear"></div>
	</div>
</div>