<?php
$this->headTitle()->headTitle("Įvykiai");
?>
<div id="events_container" class="inner_container">
	<div class="inner_header">Įvykiai</div>
	<?php if ($this->editable) : ?>
		<div class="events_tools">
			<a href="/events/create-event">Sukurti įvykį</a>
		</div>
	<?php endif;?>
	<div class="event_list_container">
		<?
		$z = 0;
		foreach ($this->content as $item) {
			$z++;
			$class = "event_block";
			if ($item["event_start"] > date("Y-m-d H:i")){
				$class = "event_block_future";
			}
			if ($item['event_published'] == 0){
				$class = "deleted_event";
			}
			?>
			<div class="<?=$class;?>" onclick="window.location.href='/ivykis/<?= $item["event_id"]; ?>-<?= urlencode($item["event_name"]); ?>'">
				<div class="event_title">
					<?= $item["event_name"]; ?>
						<span style="font-size: 12px;">(<?=intval($item['total']);?>)</span>
			<img src="/public/images/comments_icon.png" />
				</div>
				<div class="event_resume">
					<?= $item["event_resume"]; ?>
				</div>
				<div class="event_date">
					Data: <span><?= $item["event_start"]; ?></span>
				</div>
			</div>
			<?
			if ($z == 3){
				$z = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		}
		?>
		<div class="clear"></div>
	</div>
	<div><?=$this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml');?></div>
</div>
