<? $this->headTitle()->append(" - Įvykiai ");?>
<? $this->headMeta()->setName('keywords', 'alaus gamyba,naminis,įvykis,renginys,degustacija,receptas,alus');?>
<div style="width:800">
<table>
<?
$z=0;
$r=0;
$u_per_row=2;
foreach ($this->content as $item) {?>
<? if ($r==0){?>
	
	<tr>
	<?}?>
	<?
	$r++;
	?>
<td width="280" align="left" style="padding:3">
<a href="/ivykis/<?=$item["event_id"];?>-<?=urlencode($item["event_name"]);?>"><div class="ui-corner-all" style="background:#eeeeee;height:300;" onmouseover="$(this).css('cursor','hand'); $(this).css('background','#ffffff');" onmouseout="$(this).css('background','#eeeeee');">

<table style="padding:7">
<tr><td>
<h1><?=$item["event_name"];?></h1>
</td>
</tr>
<tr><td >
<span style="color:#666666">
<?=$item["event_resume"];?></span>
</td></tr>
<tr><td style="padding-top:10"><span style="color:#666666">Data: </span><b><?=$item["event_start"];?></b>
</td></tr>
</table>
</div>
</a>
</td>
<?
		
$z++;

if ($r==$u_per_row) {?>
</tr>
<?
$r=0;
}
}
if ($r>0) {
?>
</tr>
<?
}   
?>  
   
</table>

<?php echo $this->paginationControl($this->content,
                                    'Sliding',
                                    'paginator/item.phtml'); ?>
</div>
