<?php
$this->headTitle()->append(" - Įvykiai ");
$this->headMeta()->setName('keywords', 'alaus gamyba,naminis,įvykis,renginys,degustacija,receptas,alus'); 
?>
<div id="events_container" class="inner_container">
	<div class="inner_header">Įvykiai</div>
	<div class="event_list_container">
		<?
		$z = 0;
		foreach ($this->content as $item) {
			$z++;
			?>
			<div class="event_block" onclick="window.location.href='/ivykis/<?= $item["event_id"]; ?>-<?= urlencode($item["event_name"]); ?>'">
				<div class="event_title">
					<?= $item["event_name"]; ?>
				</div>
				<div class="event_resume">
					<?= $item["event_resume"]; ?>
				</div>
				<div class="event_date">
					Data: <span><?= $item["event_start"]; ?></span>
				</div>
			</div>
			<?
			if ($z == 3){
				$z = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		}
		?>
		<div class="clear"></div>
	</div>
	<div><?=$this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml');?></div>
</div>
