<h3 style="margin:0 0 5px 0;">Mano pateikti receptai</h3>
<div id="entries">
	<?php if(empty($this->beer_recipes)){ ?>
	<div>Jūs kol kas nepateikėte jokių receptų.</div>
	<?php } ?>
	<div class="col">
	<?php foreach(array_slice($this->beer_recipes, 0, (count($this->beer_recipes)  / 2)) as $key => $value){ ?>
		<p class="ui-corner-all  <?php if(in_array($value['recipe_id'], $this->beer_competition_entries_recipes)) echo 'selected' ?>">
			<input type="checkbox" name="recipe_ids[]" value='{"recipe_id":<?php echo $value['recipe_id'] ?>, "style_id":<?php echo $value['style_id'] ?>, "event_user_id":<?=$this->user_id;?>, "event_id":<?=$this->event_id;?>}' id="recipe_<?php echo $value['recipe_id'] ?>"  <?php if(in_array($value['recipe_id'], $this->beer_competition_entries_recipes)) echo 'checked="checked"' ?> />
			<label for="recipe_<?php echo $value['recipe_id'] ?>"><?php echo $this->recipeItem($value,"thumb", array('without_brewer' => true)); ?></label>
		</p>
	<?php } ?>
	</div>
	<div class="col">
	<?php foreach(array_slice($this->beer_recipes, (count($this->beer_recipes)  / 2), count($this->beer_recipes)) as $key => $value){ ?>
		<p class="ui-corner-all <?php if(in_array($value['recipe_id'], $this->beer_competition_entries_recipes)) echo 'selected' ?>">
			<input type="checkbox" name="recipe_ids[]" value='{"recipe_id":<?php echo $value['recipe_id'] ?>, "style_id":<?php echo $value['style_id'] ?>, "event_user_id":<?=$this->user_id;?>, "event_id":<?=$this->event_id;?>}' id="recipe_<?php echo $value['recipe_id'] ?>" <?php if(in_array($value['recipe_id'], $this->beer_competition_entries_recipes)) echo 'checked="checked"' ?> />
			<label for="recipe_<?php echo $value['recipe_id'] ?>"><?php echo $this->recipeItem($value,"thumb", array('without_brewer' => true)); ?></label>
		</p>
	<?php } ?>
	</div>
	<br style="clear:left;">
</div>