<?
for ($ii=0;$ii<count($this->registered_users);$ii++) {
	

?>
<div style="display:inline-block;padding:3;" align="center">
<div style="float:left;padding:5;background:#FFFFFF;"><a href="/brewers/<?=$this->registered_users[$ii]['user_id'];?>"><img src="http://www.gravatar.com/avatar/<?=md5($this->registered_users[$ii]['user_email']);?>?rating=G&size=50&default=mm" border="0"/></a><br/>
<a href="/brewers/<?=$this->registered_users[$ii]['user_id'];?>"><?=$this->registered_users[$ii]['user_name'];?> </a></div>
</div>

<?}?>