<?php
$this->headTitle()->append(" - Įvykis - " . $this->event['event_name']);
$this->headMeta()->setName('keywords', 'alaus gamyba,naminis,įvykis,renginys,degustacija,receptas,alus');
?>
<div id="events_container" class="inner_container">
	<div class="inner_header"><?= $this->event['event_name']; ?>


	</div>
	<div>
		<div class="event_i_date">
			Data: <span><?= $this->event['event_start']; ?></span>
		</div>
		<? if (isset($this->event_group)) { ?>
			<div> Renginio grupė: <?= $this->event_group['group_description']; ?></div>
		<? } ?>
		<div style="margin-bottom: 20px;">
			<?= $this->event['event_description']; ?>
		</div>
		<? if ($this->editable) { ?>
			<div class="usergroup_actions">
				<a href="/events/mod-event?event_id=<?= $this->event['event_id']; ?>" rel="nofollow">
					Redaguoti įvykį
				</a>
			</div>
		<? } ?>
		<?php
		if ($this->event['event_type'] == 'competition') {
			$evInfo = $this->eventInfo();
			echo $evInfo->showCompetitionDetails($this->event['event_id'], "Pateikti alūs:");
		}else if ($this->event['event_type'] == 'exhibition'){
      $evInfo = $this->eventInfo();
			echo $evInfo->showExhibitionDetails($this->event['event_id'], "Pateikti alūs:");
		}
		switch ($this->registration_status) {
			case 0:
				?>
				Norint prisiregistruoti reikia prisijungti prie sistemos
				<?
				break;
			case 1:
				?>
				<span id="preloader_place"></span>
				<input type="button" id='register_to_event' style="display:block;" value="Dalyvausiu" class="ui-button" />
				<input type="button" id='register_out_event' style="display:none;" value="Nedalyvausiu" class="ui-button" />
				<?
				break;
			case 2:
				?>
				<span id="preloader_place"></span>
				<input type="button" id='register_to_event' style="display:none;" value="Dalyvausiu" class="ui-button" />
				<input type="button" id='register_out_event' style="display:block;" value="Nedalyvausiu" class="ui-button" />
				<?
				break;
		}
		?>
	</div>

</div>

<div id="events_participants_container" class="inner_container">
	<div class="inner_header">Dalyviai</div>
	<div class="participants_list" id="registered">
		<?
		$z = 0;
		for ($ii = 0; $ii < count($this->registered_users); $ii++) {
			$z++;
			?>
			<a href="/brewers/<?= $this->registered_users[$ii]['user_id']; ?>">
				<img src="http://www.gravatar.com/avatar/<?= md5($this->registered_users[$ii]['user_email']); ?>?rating=G&size=50&default=mm" border="0"/>
				<span><?= $this->registered_users[$ii]['user_name']; ?></span>
			</a>
			<?
			if ($z == 8) {
				$z = 0;
				?>
				<div class="clear"></div>
				<?php
			}
		}
		?>		
		<div class="clear"></div>
		
	</div>


</div>
<?
if (($this->event['event_type'] == 'competition' || $this->event['event_type'] == 'exhibition' ) && count($this->beer_recipes)) {
	?>
	<div id="entries_container" class="inner_container" style="<?= ($this->registration_status != 2) ? "display: none;" : ""; ?>">
		<div class="inner_header">Mano receptai</div>
		<div style="margin-bottom: 20px; margin-left: 10px;">
			Pažymėkite receptus kuriuos norite pateikti konkursui
		</div>
		<div class="selectable_recipes" style="max-height:200px;overflow:auto">
			<?php
			$z = 0;
			foreach ($this->beer_recipes as $key => $value) {
				$z++;
				?>
				<div class="style_recipe <?= (!empty($value['event_id'])) ? "recipe_selected" : ""; ?>" data-recipe="<?= $value['recipe_id'] ?>" data-style="<?= $value['style_id'] ?>" data-eventuser="<?= $this->user_id; ?>" data-event="<?= $this->event['event_id']; ?>">
					<?php echo $this->recipeItem($value, "large", array('without_brewer' => true, 'without_awards' => true, 'plain' => true)); ?>
				</div>
				<?php
				if ($z == 3) {
					$z = 0;
					?>
					<div class="clear"></div>
					<?php
				}
			}
			?>
			<div class="clear"></div>

		</div>
	</div>
	<?php
}
?>
<div class="clear"></div>
<div id="comments_container" class="inner_container">
	<div class="recipe_comments">
		<div class="ingridient_category">Komentarai</div>
		<div><?=$this->eventComments($this->event['event_id']);?></div>
	</div>
</div>
<script>
	$(function(){

		//registruojame alu
		$('.selectable_recipes .style_recipe').live('click',function(){
			var event_id = $(this).attr("data-event");
			var recipe_id = $(this).attr("data-recipe");
			var event_user_id = $(this).attr("data-eventuser");
			var style_id = $(this).attr("data-style");
			if ($(this).hasClass("recipe_selected")){
				$(this).removeClass("recipe_selected");
				var actionas = 'remove';
			} else {
				$(this).addClass("recipe_selected");
				var actionas = 'add';
			}

			$.ajax({
				type: "POST",
				data: {
					'event_id': event_id,
					'recipe_id': recipe_id,
					'event_user_id': event_user_id,
					'style_id': style_id,
					'action': actionas
				},
				url: "/events/entry-registration",
				success: function(resp){
					//alert(resp);
				}
			});

		});

		$("#register_to_event").click(function(){
			$("#preloader_place").html("<img src='/public/images/spinner.gif'/>");
			$("#register_to_event").css("display","none");

			$.ajax({
				type: "POST",
				data: "action=in&id=<?= $this->event['event_id']; ?>",
				url: "/events/register",
				success: function(html)
				{
					$("#preloader_place").html('');
					$("#register_out_event").css("display","inline");
					$("#register_to_event").css("display","none");
					$("#registered").html('')
					if (html.length>0) {
						$("#registered").html(html);
						$('#entries_container').fadeIn();
					}
				}
			});
		});

		$("#register_out_event").click(function(){
			//get the id


			// show the spinner
			$("#preloader_place").html("<img src='/public/images/spinner.gif'/>");

			//the main ajax request
			$("#register_out_event").css("display","none");

			$.ajax({
				type: "POST",
				data: "action=out&id=<?= $this->event['event_id']; ?>",
				url: "/events/register",
				success: function(html)
				{

					$("#preloader_place").html('');

					$("#register_to_event").css("display","inline");
					$("#register_out_event").css("display","none");
					$("#registered").html('')
					if (html.length>0) {
						$("#registered").html(html);
						$('#entries_container').fadeOut();
					}



				}
			});
		});
	});
</script>
