<? $this->headTitle()->append(" - Įvykis - ".$this->event['event_name']);?>
<? $this->headMeta()->setName('keywords', 'alaus gamyba,naminis,įvykis,renginys,degustacija,receptas,alus');?>

<style>

#entries .col{
	float:left;
	width:50%;
}
#entries p{
  clear:left;
  min-height:60px;
  width:350px;
  margin:5px 0;
}
#entries p.selected{
  background:#f6f6f6 !important;
}

#entries label{
	font-size:14px;
	line-height:18px;
	float:left;
	margin-left:15px;
	display:block;
	width:300px;
	
}
#entries input[type=checkbox]{
	float:left;
	margin:25px 0 0 5px;
}
#entries small{
	display:block;
	
}
.spinner{
  position:absolute;
  margin:5px 0 0 -9px;
}
</style>

<script>
$(function(){
  
  //registruojame alu
  $('#entries input[type=checkbox]').live('click',function(){
    var data = jQuery.parseJSON($(this).val());
    
    if($(this).is(':checked')){
      $(this).parents('p').addClass('selected');
      data['action'] = 'add';
    }else{
      $(this).parents('p').removeClass('selected');
      data['action'] = 'remove';
    }
    $(this).parents('p').append("<img src='/public/images/spinner.gif'/ class='spinner'>");
    var entry =  $(this).parents('p');

    $.ajax({
      type: "POST",
			data: data,
			url: "/events/entry-registration",
			success: function(){
			  //Pavelinam loaderio panaikinima, taip vartotojas supras, kad veiksmas atliktas
			  window.setTimeout(function(){
			    entry.fadeOut();
			  }, 1500);
			  
			}
    });
    
  });
  
	$("#register_to_event").click(function(){
	//get the id
	
	
	// show the spinner
	$("#preloader_place").html("<img src='/public/images/spinner.gif'/>");
	
	//fadeout the vote-count 
	
	
	//the main ajax request
	$("#register_to_event").css("display","none");
	
		$.ajax({
			type: "POST",
			data: "action=in&id=<?=$this->event['event_id'];?>",
			url: "/events/register",
			success: function(msg)
			{
				$("#preloader_place").html('');
				 var data = jQuery.parseJSON(msg);
				
				
				$("#register_out_event").css("display","inline");
				$("#register_to_event").css("display","none");
				$("#registered").html('')
				if (data.data.length>0) {
					$("#registered").html(data.data);
					$('#competition_entries').fadeIn();
				}
			}
		});
	});
	
	$("#register_out_event").click(function(){
	//get the id
	
	
	// show the spinner
	$("#preloader_place").html("<img src='/public/images/spinner.gif'/>");
	
	//the main ajax request
	$("#register_out_event").css("display","none");
	
		$.ajax({
			type: "POST",
			data: "action=out&id=<?=$this->event['event_id'];?>",
			url: "/events/register",
			success: function(msg)
			{
				 var data = jQuery.parseJSON(msg);
				 $("#preloader_place").html('');
				
				$("#register_to_event").css("display","inline");
				$("#register_out_event").css("display","none");
				$("#registered").html('')
				if (data.data.length>0) {
					$("#registered").html(data.data);
					$('#competition_entries').fadeOut();
				}
				
				
				
			}
		});
	});

	$('#competition_entries').tabs();
});
</script>
<div style="width:800;background:#ffffff;padding:10" class="ui-corner-all"><h1><?=$this->event['event_name'];?></h1>
<div class="ui-corner-all" style="background:#eeeeee;min-height:300;border:1px solid #dedede">

<div style="padding:15">



<div style="padding-bottom:12"><span style="color:#666666">Data: </span><?=$this->event['event_start'];?></div>
<div><?=$this->event['event_description'];?></div>
<?php if($this->event['event_type'] == 'competition') { ?>
<div align="center" style="padding:10px">
<div style="width:400;background:#ffffff;padding:10px" class="ui-corner-all">

<? 
$evInfo=$this->eventInfo();
print $evInfo->showCompetitionDetails($this->event['event_id'],"Ketegorijoms registruoti alūs");
?>
</div>
</div>
<?}?>

<div style="display:inline;float:left;position:relative;padding-top:10">
<?

switch ($this->registration_status) {
case 0:
	?>
	<span style="color:#666666">Norint prisiregistruoti reikia prisijungti prie sistemos
	<?
	break;
case 1:
	?>
	
	<span id="preloader_place"></span>
	
	<a href='javascript:;'  id='register_to_event' style="display:block;font-weight:bold">Dalyvausiu</a>
	<a href='javascript:;'  id='register_out_event' style="display:none;font-we		t:bold">Nedalyvausiu</a>
	
	<?
	break;
case 2:
	?>
	
	<span id="preloader_place"></span>
	
	<a href='javascript:;'  id='register_to_event' style="display:none;font-weight:bold">Dalyvausiu</a>
	<a href='javascript:;'  id='register_out_event' style="display:block;font-weight:bold">Nedalyvausiu</a>

	<?
	break;
	
}
?></div>
<div style="padding-top:50;padding-bottom:5">
Dalyviai:<br/>
<div id="registered" class="ui-corner-all" style="background:#ffffff;padding:15">
<?
if (strlen($this->registered_users['user_name'])) {
	print  $this->registered_users['user_name'];
}
?>
</div>
</div>



  
<br>
<?php if($this->event['event_type'] == 'competition' && count($this->beer_recipes) > 1){ ?>
<div id="competition_entries" <?php if($this->registration_status != 2) echo 'style="display:none;"'; ?>>
<ul>
	<li><a href="/events/my-entries?event_id=<?=$this->event['event_id'];?>">Mano pateikti receptai</a></li>
	<li><a href="/events/my-all-recipes?event_id=<?=$this->event['event_id'];?>">Mano visi receptai</a></li>
</ul>
<div id="ui-tabs-1" class="ui-corner-all" style="background:#ffffff;padding:15"></div>
<div id="ui-tabs-2" class="ui-corner-all" style="background:#ffffff;padding:15"></div>

</div>
<?php } ?>
</div>
</div>
