<script type="text/javascript">
ROWS_COUNT=15;
REM_TWEET_URL = "/tweet/removetweet/";
ITEM_TWEET_URL= "/tweet/itemtweet/";
function removeTweet(id) {
$.post(REM_TWEET_URL,{id:id}, function(msg){	
	if(parseInt(msg)!=0){
		$('#tw-'+id).remove();
		$.post(ITEM_TWEET_URL,{sid:15}, function(msg){
			if(parseInt(msg)!=0){
				$('ul.statuses li:last-child').after(msg);
			}
		});
		
	}	
	});
}
</script>
<div class="inner_container" id="bubl_container">
	<div class="inner_header">Burbuliatorius</div>
	<?php
	if (count($this->content)): 
		?>
		<div id="twitter-container">
			<div id="tweet-timeline">
				<ul class="statuses">
					<?
					$curdate="";
					foreach ($this->content as $item) :
						print $this->twitter()->tweetItem($item);
					endforeach;
					?>
				</ul>
			</div>
		</div>
		<?
	endif;
	?>
	<div>
	<?php echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml'); ?>	
	</div>
</div>