<div class="ui-corner-all" style="background:#ededed;padding:5;owerflow:hidden;margin-top:10px">
<input type="hidden" name="link_title" value="<?=htmlentities($this->title,ENT_QUOTES,'UTF-8');?>">
<input type="hidden" name="link_description" value="<?=htmlentities($this->description,ENT_QUOTES,'UTF-8');?>">
<input type="hidden" name="link_url" value="<?=htmlentities($this->url,ENT_QUOTES,'UTF-8');?>">
<input type="hidden" name="http_status" value="<?=$this->http_status;?>">

<?if ($this->http_status==200) {?>
<table>
  <tr>
  <td valign="top"><div id="imagesContainer">&nbsp;</div></td>
	<td valign="top">
     <div id="info">
        <label class="title">
        <?php  echo $this->title; ?>
        </label>
        <br clear="all" />
        <label class="desc">
        <?php  echo $this->description; ?>
        </label>
      </div>
      </td>
    </tr>
	</table>
<script>getImages(['<?=implode("','",$this->images); ?>']) </script>
<?}else{?> 
		 <h3>404</h3> Puslapis nerastas 
</div>
<?}?>
