<script type="text/javascript">
	$(function() {
		$("#mail_search_form").submit(function(){
			window.location.href = "/mail/inbox/"+$("#mail_search").val();
			return false;
		});
	})
</script>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Gautieji laiškai</div>
	<div class="mail_tools">
		<div class="mail_search">
			<form action="" id="mail_search_form">
				<input type="text" value="<?=$this->search?>" id="mail_search" name="mail_search" />
				<input type="submit" value="Ieškoti" class="ui-button" />
				<div class="clear"></div>
			</form>
		</div>
		<a href="/mail/outbox">Išsiųsti laiškai</a>
		<a href="/mail/compose">Rašyti laišką</a>
		<a href="/mail/inbox"><b>Gautieji</b></a>
		<div class="clear"></div>
	</div>
	<? if (isset($_GET["succes"])) { ?>
		<div class="mail_success">
			Laiškas sėkmingai išsiųstas
		</div>
	<? } ?>
	<form action="/mail/delete" method="POST" id="inboxForm">
		<input type="hidden" name="type" value="inbox">
		<input type="hidden" name="redirect" value="<?= $_SERVER['REQUEST_URI']; ?>">
		<div class="as-table">
			<div class="as-row">
				<div class="as-cell">
					<input type="checkbox" style="border:1 solid #333333" onclick="checkAll($(this)[0].checked)"/>
				</div>
				<div class="as-cell"><b>Siuntėjas</b></div>
				<div class="as-cell"><b>Tema</b></div>
				<div class="as-cell"><b>Data</b></div>
			</div>
			<?php
			$total = 0;
			foreach ($this->content as $item) {
				$total++;
				$class = $item["mail_read"] == '0' ? "t-unread" : "";
				?>
				<div class="as-row mail_row <?= $class; ?>">
					<div class="as-cell" style="width: 23px;">
						<input type="checkbox" style="border:1 solid #333333" name="mail_id[]" id="chMail" value="<?= $item["mail_id"]; ?>"/>
					</div>
					<div class="as-cell" style="width: 150px;" onclick="window.location.href='/mail/read?id=<?= $item["mail_id"]; ?>'">
						<?= $item["user_name"]; ?>
					</div>
					<div class="as-cell" onclick="window.location.href='/mail/read?id=<?= $item["mail_id"]; ?>'">
						<?= $item["mail_subject"]; ?>
					</div>
					<div class="as-cell" style="width: 120px;" onclick="window.location.href='/mail/read?id=<?= $item["mail_id"]; ?>'">
						<?= $item["mail_date"]; ?>
					</div>
				</div>
				<?
			}
			?>  
		</div>
	</form>	
	<? if ($total == 0) { ?>
		<div style="margin: 20px; font-size: 14px;">Žinučių nėra</div>
	<? } ?>
	<div style="margin-top: 10px; text-align: right;">
		<input type="button" id="markAsReadButton" value="Pažymėti kaip skaitytus" class="ui-button" />
		<input type="button" id="deleteButton" value="Trinti pažymėtas žinutes" class="ui-button" />
		<div style="margin-top: 10px;">
			<?php
			echo $this->paginationControl($this->content, 'Sliding', 'paginator/item.phtml');
			?>
		</div>
	</div>
</div>

<script>
	$(function() {
		$('#deleteButton').click(function() {
			if (($('input[name="mail_id[]"]:checked').length>0)) {
				if (confirm("Pasirinkti laiškai bus ištrinti!")) {
					$("#inboxForm").submit();
				}
			} else {
				alert("Nepažymėjote nei vienos žinutės");
			}
		});
		$('#markAsReadButton').click(function() {
			if (($('input[name="mail_id[]"]:checked').length>0)) {
				if (confirm("Pasirinkti laiškai bus pažymėti kaip perskaityti!")) {
					$("#inboxForm").attr("action", "/mail/markasread");
					$("#inboxForm").submit();
				}
			} else {
				alert("Nepažymėjote nei vienos žinutės");
			}
		});
	})
	function checkAll(val) {
		$('input[name="mail_id[]"]').attr('checked', val);
        
	}
</script>