<style>
#mail-menu {
	display:inline;
	list-style:none;
}
#mail-menu li {
	display:inline;
	padding-right:10;
	padding-left:10
}
</style>

<div style="width:900">
<ul id="mail-menu">
	<li><a href="/mail/inbox">Gautieji</a></li>|
	<li><a href="/mail/compose">Rašyti laišką</a></li>|
	<li><a href="/mail/outbox">Išsiųsti laiškai</a></li>
	
	
</ul>
<div id="mainPanel" style="border-bottom: 3px solid #ccc;padding:10px;width:100%;text-align:center">
<table>
<?

foreach ($this->content as $item) {?>

	
	<tr>

<td width="280" align="left" style="padding:3">

<?=print_r($item);?>

</td>
</tr>
<?
}   
?>  
   
</table>
</div>

</div>
</div>
<?php echo $this->paginationControl($this->content,
                                    'Sliding',
                                    'paginator/item.phtml'); ?>
			


