<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Išsiųsti laiškai</div>
	<div class="mail_tools">
		<a href="/mail/outbox"><b>Išsiųsti laiškai</b></a>
		<a href="/mail/compose">Rašyti laišką</a>
		<a href="/mail/inbox">Gautieji</a>
		<div class="clear"></div>
	</div>
	<?php
	if (isset($this->mail)) {
		?>
		<div class="mail_info_block">
			<div class="mail_info_label">Nuo:</div>
			<div class="mail_info_text"><?= $this->mail['mail_from']; ?></div>
			<div class="clear"></div>
		</div>
		<div class="mail_info_block">
			<div class="mail_info_label">Kam:</div>
			<div class="mail_info_text"><?= str_replace(",", ", ", $this->mail['mail_to']); ?></div>
			<div class="clear"></div>
		</div>
		<div class="mail_info_block">
			<div class="mail_info_label">Data:</div>
			<div class="mail_info_text"><?= $this->mail['mail_date']; ?></div>
			<div class="clear"></div>
		</div>
		<div class="mail_info_block">
			<div class="mail_info_label">Tema:</div>
			<div class="mail_info_text"><?= $this->mail['mail_subject']; ?></div>
			<div class="clear"></div>
		</div>
		<div class="mail_contents">
			<?= nl2br(preg_replace('/((?:http|https|ftp):\/\/(?:[A-Z0-9][A-Z0-9_-]*(?:\.[A-Z0-9][A-Z0-9_-]*)+):?(\d+)?\/?[^\s\"\']+)/i', '<a href="$1" rel="nofollow" target="blank">$1</a>', $this->mail['mail_body'])); ?>
		</div>
		<?php
	}
	?>
</div>