<?php
$this->headTitle()->headTitle("Naujas laiškas");
?>
<?
$this->headScript()->appendFile("/public/ui/ui/jquery.ui.core.js");
$this->headScript()->appendFile("/public/ui/ui/jquery.ui.autocomplete.js");
$this->headLink()->appendStylesheet("/public/ui/themes/pepper-grinder/jquery.ui.autocomplete.css");
?>
<div id="brewer_session_container" class="inner_container">
	<div class="inner_header">Naujas laiškas</div>
	<div class="mail_tools">
		<a href="/mail/outbox">Išsiųsti laiškai</a>
		<a href="/mail/compose"><b>Rašyti laišką</b></a>
		<a href="/mail/inbox">Gautieji</a>
		<div class="clear"></div>
	</div>
	<?
	if (isset($this->mail)) {
		$body_arr = explode('\n', $this->mail['mail_body']);
		$body = "";
		for ($i = 0; $i < count($body_arr); $i++) {
			$body.=$this->mail['mail_from'] . " rašė: \n------------------------\n" . $body_arr[$i] . "\n------------------------";
		}
		?>
		<form action="/mail/send" method="post" id="sendMailForm">
			<dl>
				<dt>Adresatas:</dt>
				<dd>
					<input type="text" id="mail_to" name="mail_to" value="<?= $this->acc; ?>"/> 
				</dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<dt>Tema:</dt>
				<?php
					$sbj = $this->mail['mail_subject'];
					$exp = "@^Ats\[?([^/]+)\]@i";
					preg_match($exp, $sbj, $matches);
					if (isset($matches[1]) && !empty($matches[1])){
						$old = $matches[1];
						$sbj = str_replace("Ats[".$old."]:", "Ats[".($old+1)."]:", $sbj);
					} else {
						$exp2 = "@^Ats:@i";
						preg_match($exp2, $sbj, $matches2);
						if (isset($matches2[0]) && !empty($matches2[0])){
							$sbj = str_replace("Ats:", "Ats[2]:", $sbj);
						} else {
							$sbj = "Ats: ".$sbj;
						}
					}
				?>
				<dd><input type="text" name="mail_subject" id="mail_subject" value="<?= $sbj; ?>"  /></dd>
				<div class="clear"></div>
			</dl>
			<dl>
				<textArea  id="mail_body"  name="mail_body"><?=$body;?></textArea>
			</dl>
			<dl>
				<input type="button" id="sendButton" value="Siųsti" class="ui-button" />
			</dl>
		</form>
		<?
	}
	?>
</div>

<style> 
	.ui-autocomplete-loading { background: white url('/public/images/spinner.gif') right center no-repeat; }
</style> 
<script> 
	$(function() {
		function split( val ) {
			return val.split( /,\s*/ );
		}
		function extractLast( term ) {
			
			return split( term ).pop();
		}
 
		$( "#mail_to" )
		// don't navigate away from the field on tab when selecting an item
		.bind( "keydown", function( event ) {
			
			if ( event.keyCode === 9 && $( this ).data( "autocomplete" ).menu.active ) {
				event.preventDefault();
			}
		})
		.autocomplete({
			source: function( request, response ) {
				
				$.getJSON( "/mail/contacts", {
					term: extractLast( request.term )
				}, response )
			},
			search: function() {
				// custom minLength
					
				var term = extractLast( this.value );
					
				if ( term.length < 2 ) {
					return false;
				}
			},
			focus: function() {
				// prevent value inserted on focus
				return false;
			},
			select: function( event, ui ) {
				var terms = split( this.value );
				// remove the current input
				terms.pop();
				// add the selected item
				terms.push( ui.item.value );
				// add placeholder to get the comma-and-space at the end
					
				var lastOne=$.trim(terms[terms.length-1])
				var i=0;
				while (i<terms.length-1) {
					if ($.trim(terms[i])==lastOne) {
						terms.splice(i,1)
					}else{
						i++
					}
				}terms.push( "" );
				this.value = terms.join( ", " );
				return false;
			}
		});$('#sendButton').button();
		$('#sendButton').click(function() {;
			if ($("#mail_to").val().length>0) {
				$("#sendMailForm")[0].submit();
			}});
	});
	
	
</script>