<div class="new_block ico_blog">
	<div class="white">
		<div class="avatar">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
			</a>
		</div>
		<div class="post">
			<div class="post_action">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<?= $item["user_name"] ?>
				</a>
				sukūrė naują blogo įrašą
				<a href="<?=$item['blog_link']?>">
					<?= $item["blog_title"] ?>
				</a>
			</div>
			<div class="post_content">
				<?php
				$fhtml = new Zend_Filter_StripTags(array("allowTags" => array("br", "p")));
				$f = new Entities_Filter_Excerpt();
				$item['blog_content'] = str_replace(array("<p></p>", "<p> </p>", "<p>&nbsp;</p>"), array("", "", ""), trim($item['blog_content']));
				?>
				<a href="<?=$item['blog_link']?>" style="color: #666">
					<?=$f->filter($fhtml->filter($item['blog_content']), 30); ?>
				</a>
			</div>
			<div class="post_stamp">
				<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>