<div class="new_block ico_food_comment">
	<div class="white">
		<div class="avatar">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
			</a>
		</div>
		<div class="post">
			<div class="post_action">
				<a href="/brewers/<?= $item['user_id']; ?>">
					<?= $item["user_name"] ?>
				</a>
				komentavo patiekalą 
				<a href="/patiekalas/<?= $item['food_comment_food_id']; ?>-<?=$this->urlMaker($item["food_comment_food_title"])?>">
					<?= $item["food_comment_food_title"] ?>
				</a>
			</div>
			<div class="post_content">
				<?php
				$fhtml = new Zend_Filter_StripTags(array("allowTags" => array("br", "p")));
				$f = new Entities_Filter_Excerpt();
				$item['food_comment_text'] = str_replace("\n", "<br />", $item['food_comment_text']);
				?>
				<a href="/patiekalas/<?= $item['food_comment_food_id']; ?>-<?=$this->urlMaker($item["food_comment_food_title"])?>" style="color: #666">
					<?=$f->filter($fhtml->filter($item['food_comment_text']), 30); ?>
				</a>
			</div>
			<div class="post_stamp">
				<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>