<div class="new_block block_forum_post">
	<div class="avatar">
		<a href="/brewers/<?= $item['user_id']; ?>">
			<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
		</a>
	</div>
	<div class="post">
		<div class="post_action">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<?= $item["user_name"] ?>
			</a>
			bravoryja <b><?=(float)$item['session_size']?></b> ltr.   
			<a href="/alus/receptas/<?=$item['session_recipe_id']?>-<?=$this->urlMaker($item['session_recipe_name'])?>">
				<?= $item["session_recipe_name"] ?>
			</a>
		</div>
		<div class="post_stamp">
			<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
		</div>
	</div>
	<div class="clear"></div>
</div>