<div class="new_block block_forum_post">
	<div class="avatar">
		<a href="/brewers/<?= $item['user_id']; ?>">
			<img  src="http://www.gravatar.com/avatar/<?= $item['email_hash']; ?>?rating=G&size=50&default=mm" border="0"/>
		</a>
	</div>
	<div class="post">
		<div class="post_action">
			<a href="/brewers/<?= $item['user_id']; ?>">
				<?= $item["user_name"] ?>
			</a>
		</div>
		<div class="post_content">
			<div>
				<?= preg_replace('/((?:http|https|ftp):\/\/(?:[A-Z0-9][A-Z0-9_-]*(?:\.[A-Z0-9][A-Z0-9_-]*)+):?(\d+)?\/?[^\s\"\']+)/i', '<a href="$1" rel="nofollow" target="blank">$1</a>', $item['tweet_message']); ?>
			</div>
			<?php
			if (strlen($item['tweet_link_url']) > 0) { 
				?>
				<a href="<?= $item['tweet_link_url']; ?>" target="_blank">
					<div class="new_tweet-attachment">
						<div class="tw_link_image" style="max-height: 100px; overflow: hidden;">
							<?
							$img_width = 320;
							if (isset($item['tweet_link_image']) && !empty($item['tweet_link_image'])) {
								$img_width = 240;
								?>
								<img src='<?=$item['tweet_link_image']?>' width='70' />
								<?php
							}
							?>
						</div>
						<div class="tw_link_text wi-<?=$img_width;?>">
							<span>
								<?= trim($item['tweet_link_title']); ?>
							</span>
							<div class="tweet-attachment-desc">
								<? 
								if (isset($item['tweet_link_description'])) {
									print $item['tweet_link_description'];
								}
								?>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</a>
				<? 
			}
			?>
		</div>
		<div class="post_stamp">
			<span title="<?=$item['posted']?>"><?=$this->prettyStamp($item['posted']);?></span>
		</div>
	</div>
	<div class="clear"></div>
</div>