<div class="competition_stat">
	<div class="competition_title"><?=$this->title;?></div>
	<?
	if (count($this->categories)>0) {
		$i = 0;
		$max = round($this->categories[0]["count"]);
		foreach ($this->categories as $cat) {
			$i++;
			?>
			<div><?=($i).". ".$cat["name"] ." (".$cat["count"] .")" ;?></div>
			<div style="width:<?=round($cat["count"]/$max*80);?>%;" class="progressbar padifyb"></div>
			<?
		}
	}
	?>
</div>