<? $this->headLink()->appendStylesheet("/public/ui/external/jquery.editable-select.css"); ?>
<? //$this->headLink()->appendStylesheet("/public/ui/external/ui.spinner.css");       ?>
<? $this->headScript()->appendFile("/public/ui/external/ui.core.js"); ?>
<? $this->headScript()->appendFile("/public/ui/external/ui.spinner.js"); ?>
<? $this->headScript()->appendFile("/public/ui/external/jquery.editable-select.js"); ?>

<script type="text/javascript">
	function getMalts() {
		var malts = '<option malt_id="0" type="malt" ebc="3" extract="1.036">Bazinis salyklas</option>';
<?
for ($i = 0; $i < count($this->malts); $i++) {
	?>
			malts += '<option malt_id="<?= trim($this->malts[$i]['malt_id']); ?>" type="<?= trim($this->malts[$i]['malt_type']); ?>" ebc="<?= trim($this->malts[$i]['malt_ebc']); ?>" extract="<?= $this->malts[$i]['malt_extract'] ?>"><?= addslashes($this->malts[$i]['malt_name']); ?></option>';
	<?
}
?>
		return malts;
	}
	function getHops() {
		var hops = '';
<?
for ($i = 0; $i < count($this->hops); $i++) {
	?>
			hops += '<option hop_id="<?= trim($this->hops[$i]['hop_id']); ?>" alpha="<?= trim($this->hops[$i]['hop_alpham']); ?>"><?= addslashes($this->hops[$i]['hop_name']); ?></option>';
	<?
}
?>
		return hops;
	}
	function getHopUse() {
		var uses = '';
		uses += '<option value="none">-</option>';
		uses += '<option value="Mash">Salinimui</option>';
		uses += '<option value="First Wort">Pirmam miso apyniavimui</option>';
		uses += '<option value="Boil">Virimui (kartumui)</option>';
		uses += '<option value="Aroma">Aromatui</option>';
		uses += '<option value="Dry Hop">Sausam apyniavimui</option>';
		return uses;
	}
	function getHopForm() {
		var uses = '';
		uses += '<option value="none">-</option>';
		uses += '<option value="pelet">Granulės</option>';
		uses += '<option value="cone">Spurgai</option>';
		return uses;
	}
	function getYeasts() {
		var yeasts = '';
<?
for ($i = 0; $i < count($this->yeasts); $i++) {
	?>
			yeasts += '<option yeast_id="<?= trim($this->yeasts[$i]['yeast_id']); ?>" yeast_attenuation="<?= $this->yeasts[$i]['yeast_attenuation']; ?>"><?= $this->yeasts[$i]['yeast_name']; ?></option>';
	<?
}
?>
		return yeasts;
	}
	function addNull(_s) {
		if (String(_s).length == 1) {
			return "0" + _s;
		}
		return _s;
	}
	function now() {
		$d = new Date();
		return $d.getFullYear() + "." + addNull($d.getMonth() + 1) + "." + addNull($d.getDate()) + " " + addNull($d.getHours()) + "." + addNull($d.getMinutes());
	}
	function round_val(v) {
		return Math.round(v * 1000) / 1000;
	}
	function plato_sg(p, inp) {
		if (inp == "plato") {
			return P2SG(p)
		} else {
			return Math.round(SG2P(p) * 10) / 10
		}
	}
	function P2SG(p) {
		return 1.00001 + 3.8661E-3 * p + 1.3488E-5 * p * p + 4.3074E-8 * p * p * p;
	}
	function SG2P(sg) {
		return -668.962 + 1262.45 * sg - 776.43 * sg * sg + 182.94 * sg * sg * sg;
	}

	function ecb_to_lovibond(ecb) {
		//return ecb * 0.375 - 0.46;
		return ecb / 1.97;
	}
	function srm_to_ecb(srm) {
		//return srm / 0.375 + 0.46;
		return srm * 1.97;
	}
	function kg_to_pounds(kg) {
		return kg * 2.20462262;
	}
	function liters_to_gallons(l) {
		return l * 0.264172052;
	}
	function gram_to_ounce(g) {
		return g * 0.0352739619;
	}
	function calc_ABV(sg, fg) {
		return (sg - fg) * 0.131;
	}
	//
	function calc_IBU(hops, liters, gravity) {
		var gallons = liters_to_gallons(liters);
		var ttlIBU_Tinseth = 0;
		var ttlIBU_Rager = 0;
		for (var i = 0; i < hops.hop_weight.length; i++) {
			var thisIBU_Tinseth = 0;
			var thisIBU_Rager = 0;
			//calculate IBU if there are no zero values for this row
			var util = (1.65 * Math.pow(0.000125, gravity - 1)) * ((1 - Math.exp(-0.04 * hops.hop_time[i])) / 4.15);
			//	util = util.toPrecision(5);
			thisIBU_Tinseth = util * (gram_to_ounce(hops.hop_weight[i]) * (hops.hop_alpha[i] / 100) * 7490) / gallons;
			thisIBU_Rager = (gram_to_ounce(hops.hop_weight[i]) * util * (hops.hop_alpha[i] / 100) * 7489) / (gallons * gravity);
			ttlIBU_Tinseth = ttlIBU_Tinseth + thisIBU_Tinseth;
			ttlIBU_Rager = ttlIBU_Rager + thisIBU_Rager;
		}
		return ttlIBU_Tinseth.toPrecision(4);
		//document.getElementById('ibu_rager').innerHTML = 'IBU (Rager): ' + ttlIBU_Rager.toPrecision(4); 
		return true;
	}
	//
	function calc_SRM(malt_ecb, malt_kg, water_l) {
		var mcu = 0;
		for (var i = 0; i < malt_ecb.length; i++) {
			mcu += ((malt_ecb[i] / 1.97) * kg_to_pounds(malt_kg[i])) / liters_to_gallons(water_l);
		}
		return (1.4922 * Math.pow(mcu, 0.6859));
	}
	function calc_SG(malt_extract, malt_weight, malt_type, water_l, ef) {
		//100% efektyvumas
		var sg = 0;
		for (var i = 0; i < malt_weight.length; i++) {
			if (malt_type[i] == "malt") {
				sg += ((kg_to_pounds(malt_weight[i]) * ((malt_extract[i] * 1000) - 1000)) / liters_to_gallons(water_l)) * ef;
			} else {
				sg += ((kg_to_pounds(malt_weight[i]) * ((malt_extract[i] * 1000) - 1000)) / liters_to_gallons(water_l));
			}
		}
		return sg;
	}
	function colorHex(srm) {
		SRMColor = new Array();
		SRMColor.push('#FFFFFF');
		SRMColor.push('#FFE699');
		SRMColor.push('#FFD878');
		SRMColor.push('#FFCA5A');
		SRMColor.push('#FFBF42');
		SRMColor.push('#FBB123');
		SRMColor.push('#F8A600');
		SRMColor.push('#F39C00');
		SRMColor.push('#EA8F00');
		SRMColor.push('#E58500');
		SRMColor.push('#DE7C00');
		SRMColor.push('#D77200');
		SRMColor.push('#CF6900');
		SRMColor.push('#CB6200');
		SRMColor.push('#C35900');
		SRMColor.push('#BB5100');
		SRMColor.push('#B54C00');
		SRMColor.push('#B04500');
		SRMColor.push('#A63E00');
		SRMColor.push('#A13700');
		SRMColor.push('#9B3200');
		SRMColor.push('#952D00');
		SRMColor.push('#8E2900');
		SRMColor.push('#882300');
		SRMColor.push('#821E00');
		SRMColor.push('#7B1A00');
		SRMColor.push('#771900');
		SRMColor.push('#701400');
		SRMColor.push('#6A0E00');
		SRMColor.push('#660D00');
		SRMColor.push('#5E0B00');
		SRMColor.push('#5A0A02');
		SRMColor.push('#600903');
		SRMColor.push('#520907');
		SRMColor.push('#4C0505');
		SRMColor.push('#470606');
		SRMColor.push('#440607');
		SRMColor.push('#3F0708');
		SRMColor.push('#3B0607');
		SRMColor.push('#3A070B');
		SRMColor.push('#36080A');
		if (SRMColor[Math.round(srm)]) {
			return SRMColor[Math.round(srm)];
		} else {
			return "#000000";
		}
		//http://www.franklinbrew.org/brewinfo/srm.html
	}
	//
	function kgToPercent() {
		var _total = 0;
		var tot_wdt = $('input[name=malt_weight]');
		for (var i = 0; i < tot_wdt.length - 1; i++) {
			var o = $(tot_wdt[i]);
			_total += parseFloat(o.val());
		}
		for (var i = 0; i < tot_wdt.length - 1; i++) {
			var o = $(tot_wdt[i]);
			var id = o.attr("id").split("_");
			$("#malt_perc_" + id[2]).html("<b>" + (Math.round((o.val() / _total * 100) * 10) / 10) + " %</b>");
		}
	}
	//
	function beer_style_change(trigger_changes) {
		trigger_changes = typeof trigger_changes !== 'undefined' ? trigger_changes : true;
		if (trigger_changes == true) {
			there_are_changes = true;
		}
		var style_recom = $($("#beer_style")[0].options[$("#beer_style")[0].selectedIndex]);
		$('#style_sg')[0].innerHTML = " ";
		$('#style_fg')[0].innerHTML = " ";
		$('#style_abv')[0].innerHTML = " ";
		$('#style_ibu')[0].innerHTML = " ";
		$('#style_ebc')[0].innerHTML = " ";
		if (style_recom.attr("style_fghigh").length > 0) {
			if ($("input[name='extract_m']:checked").val() == "plato") {
				$('#style_fg')[0].innerHTML = " [" + plato_sg(style_recom.attr("style_fglow"), "sg") + " - " + plato_sg(style_recom.attr("style_fghigh"), "sg") + "] "
				$('#style_sg')[0].innerHTML = " [" + plato_sg(style_recom.attr("style_oglow"), "sg") + " - " + plato_sg(style_recom.attr("style_oghigh"), "sg") + "] "
			} else {
				$('#style_fg')[0].innerHTML = " [" + style_recom.attr("style_fglow") + " - " + style_recom.attr("style_fghigh") + "] ";
				$('#style_sg')[0].innerHTML = " [" + style_recom.attr("style_oglow") + " - " + style_recom.attr("style_oghigh") + "] ";
			}
			$('#style_abv')[0].innerHTML = " [" + (Math.round(calc_ABV(style_recom.attr("style_oglow") * 1000, style_recom.attr("style_fglow") * 1000) * 10) / 10) + "% - " + (Math.round(calc_ABV(style_recom.attr("style_oghigh") * 1000, style_recom.attr("style_fglow") * 1000) * 10) / 10) + "%] ";
			$('#style_ibu')[0].innerHTML = " [" + style_recom.attr("style_ibulow") + " - " + style_recom.attr("style_ibuhigh") + "] ";
			$('#style_ebc')[0].innerHTML = " [" + Math.round(srm_to_ecb(style_recom.attr("style_srmlow"))) + " - " + Math.round(srm_to_ecb(style_recom.attr("style_srmhigh"))) + "] ";
		}

	}
	//
	function calc() {
		var yeast = $('#yeast_form').serializeArray();
		var o = {yeast_weight: []};
		for (var i = 0; i < yeast.length; i++) {
			if (o[yeast[i].name]) {
				o[yeast[i].name].push(yeast[i].value);
			}
		}
		yeast_total = 0;
		for (var m = 0; m < o.yeast_weight.length; m++) {
			yeast_total = yeast_total + parseFloat(o.yeast_weight[m]);
		}
		$("#yeast-totals b").html(yeast_total.toFixed(0)+" g");

		var malt = $('#malt_form').serializeArray();
		var o = {malt_color: [], malt_weight: [], malt_extract: [], malt_type: []};
		for (var i = 0; i < malt.length; i++) {
			if (o[malt[i].name]) {
				o[malt[i].name].push(malt[i].value);
			}
		}
		malt_total = 0;
		for (var m = 0; m < o.malt_weight.length; m++) {
			malt_total = malt_total + parseFloat(o.malt_weight[m]);
		}
		$("#malt-totals b").html(malt_total.toFixed(2) + " kg");
		var bs = $('#bash_size').val();
		var ef = $("#efficiency").val();
		var att = $('#attenuation').val();
		var sg = calc_SG(o.malt_extract, o.malt_weight, o.malt_type, bs, ef);
		var srm = calc_SRM(o.malt_color, o.malt_weight, bs);
		var sgf = round_val((sg + 1000) / 1000);
		var fgf = round_val(((sg * (1 - att)) + 1000) / 1000);

		$('#recipe_sg').val(sgf)
		$('#recipe_fg').val(fgf)
		$('#recipe_abv').val((Math.round(calc_ABV(sgf * 1000, fgf * 1000) * 10) / 10))

		if ($("input[name='extract_m']:checked").val() == "plato") {
			$('#recipe_sg_span')[0].innerHTML = plato_sg(sgf, "sg").toFixed(1)
			$('.og_ph').html(plato_sg(sgf, "sg").toFixed(1));
			$('#recipe_fg_span')[0].innerHTML = plato_sg(fgf, "sg").toFixed(1)
			$('.fg_ph').html(plato_sg(fgf, "sg").toFixed(1));
		} else {
			$('#recipe_sg_span')[0].innerHTML = sgf.toFixed(3)
			$('.og_ph').html(sgf.toFixed(3));
			$('#recipe_fg_span')[0].innerHTML = fgf.toFixed(3)
			$('.fg_ph').html(fgf.toFixed(3));
		}
		//cia

		$('#recipe_abv_span')[0].innerHTML = (Math.round(calc_ABV(sgf * 1000, fgf * 1000) * 10) / 10).toFixed(1) + "%";
		$('.abv_ph').html((Math.round(calc_ABV(sgf * 1000, fgf * 1000) * 10) / 10).toFixed(1) + "%");
		$('#beer_color').css('backgroundColor', colorHex(srm));
		var hops = $('#hops_form').serializeArray();
		var o = {hop_alpha: [], hop_weight: [], hop_time: []};
		for (var i = 0; i < hops.length; i++) {
			if (o[hops[i].name]) {
				o[hops[i].name].push(hops[i].value);
			}
		}
		hop_total = 0;
		for (var m = 0; m < o.hop_weight.length; m++) {
			hop_total = hop_total + parseFloat(o.hop_weight[m]);
		}
		$("#hop-totals b").html(hop_total.toFixed(0) + " g");
		var ibu = calc_IBU(o, bs, sgf);
		$('#recipe_ebc_span')[0].innerHTML = Math.round(srm_to_ecb(srm));
		$('.ebc_ph').html(Math.round(srm_to_ecb(srm)));
		$('#recipe_ibu_span')[0].innerHTML = Math.round(ibu);
		$('.ibu_ph').html(Math.round(ibu));
		$('#recipe_ebc').val(Math.round(srm_to_ecb(srm)))
		$('#recipe_ibu').val(Math.round(ibu));
		$("#feel_container").html("-");
		var bu = roundNumber(Math.round(ibu) / ((sgf * 1000) - 1000), 2);
		if (bu >= 0 && bu <= 0.19) {
			$("#feel_container").html('<span style="font-weight: bold;">' + bu.toFixed(2) + "</span> <span class='style_recom'>kartumo nėra, dominuoja salyklas</span>");
		} else if (bu >= 0.2 && bu <= 0.39) {
			$("#feel_container").html('<span style="font-weight: bold;">' + bu.toFixed(2) + "</span> <span class='style_recom'>jaučiami apyniai, dominuoja salyklas</span>");
		} else if (bu >= 0.4 && bu <= 0.59) {
			$("#feel_container").html('<span style="font-weight: bold;">' + bu.toFixed(2) + "</span> <span class='style_recom'>kartumas ir salyklo skonis subalansuotas</span>");
		} else if (bu >= 0.6 && bu <= 0.79) {
			$("#feel_container").html('<span style="font-weight: bold;">' + bu.toFixed(2) + "</span> <span class='style_recom'>ryškus apynių skonis</span>");
		} else if (bu >= 0.8 && bu <= 100) {
			$("#feel_container").html('<span style="font-weight: bold;">' + bu.toFixed(2) + "</span> <span class='style_recom'>dominuoja apynių skonis</span>");
		}
		kgToPercent();
	}
	function roundNumber(num, dec) {
		var result = Math.round(num * Math.pow(10, dec)) / Math.pow(10, dec);
		return result;
	}
	function selectMalt(id) {
		var sItem = $('#malt-list_' + id).editableSelect("getSelectedItem");
		$('#malt_color_' + id).attr('value', sItem.ebc);
		$('#malt_extract_' + id).attr('value', sItem.extract);
		$('#malt_type_' + id).attr('value', sItem.type);
	}
	//
	function createMaltList(id) {
		$('#malt-list_' + id).editableSelect({bg_iframe: false, onSelect: function(list_item) {
				there_are_changes = true;
				selectMalt(id);
				calc();
			}, onFocus: function() {
				$('#malt_tr_' + id).click();
			}});
		//alert($('#malt-list_'+id).editableSelect('getInstance'))
	}
	function createMaltTr(values) {
		var rid = $('#malt-table').data('last_tr');
		if (!rid) {
			var rid = 0;
		}

		$("#malts_template .malt_tr").attr("id", "malt_tr_" + rid);
		$("#malts_template .malt_perc").attr("id", "malt_perc_" + rid);
		$("#malts_template .malt_list").attr("id", "malt-list_" + rid);
		$("#malts_template .malt_weight").attr("id", "malt_weight_" + rid);
		$("#malts_template .malt_extract").attr("id", "malt_extract_" + rid);
		$("#malts_template .malt_color").attr("id", "malt_color_" + rid);
		$("#malts_template .malt_type").attr("id", "malt_type_" + rid);
		$("#malts_template .malt_list").html(getMalts());
		$('#malt-table .tbody').append($("#malts_template").html());

		$("#malt_weight_" + rid).spinner({min: 0, stepping: 0.05});
		$("#malt_weight_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#malt_extract_" + rid).spinner({min: 0, stepping: 0.001});
		$("#malt_extract_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#malt_color_" + rid).spinner({min: 0});
		$("#malt_color_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$('#malt_tr_' + rid).click(function() {
			var prev = $('#malt-table').data('selected_tr');
			if (prev) {
				$('#' + prev).css("backgroundColor", "");
			}
			$('#' + this.id).css("backgroundColor", "#dddddd");
			$('#malt-table').data('selected_tr', this.id);
		});
		createMaltList(rid);
		$('#malt-table').data('last_tr', rid + 1);
		if (values) {
			$("#malt_weight_" + rid).val(values["malt_weight"]);
			$("#malt_extract_" + rid).val(values["malt_extract"]);
			$("#malt_color_" + rid).val(values["malt_ebc"]);
			$("#malt_type_" + rid).val(values["malt_type"]);
			$("#malt-list_" + rid).val(values["malt_name"]);
		}
		return rid;
	}
	function createHopList(id) {
		$('#hop-list_' + id).editableSelect({bg_iframe: false, onSelect: function(list_item) {
				var sItem = $('#hop-list_' + id).editableSelect("getSelectedItem");
				$('#hop_alpha_' + id).attr('value', sItem.alpha);
				there_are_changes = true;
				calc();
			}, onFocus: function() {
				$('#hop_tr_' + id).click();
			}});
		//alert($('#malt-list_'+id).editableSelect('getInstance'))
	}
	function createHopTr(values) {
		var rid = $('#hop-table').data('last_tr');
		if (!rid) {
			var rid = 0;
		}

		$("#hops_template .hop_tr").attr("id", "hop_tr_" + rid);
		$("#hops_template .hop_weight").attr("id", "hop_weight_" + rid);
		$("#hops_template .hop_use").attr("id", "hop_use_" + rid);
		$("#hops_template .hop_form").attr("id", "hop_form_" + rid);
		$("#hops_template .hop_alpha").attr("id", "hop_alpha_" + rid);
		$("#hops_template .hop_time").attr("id", "hop_time_" + rid);
		$("#hops_template .hop_list").attr("id", "hop-list_" + rid);
		$("#hops_template .hop_list").html(getHops());
		$("#hops_template .hop_use").html(getHopUse());
		$("#hops_template .hop_form").html(getHopForm());
		$('#hop-table .tbody').append($("#hops_template").html());

		$("#hop_weight_" + rid).spinner({min: 0});
		$("#hop_weight_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#hop_alpha_" + rid).spinner({min: 0, max: 30, stepping: 0.1});
		$("#hop_alpha_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#hop_time_" + rid).spinner({min: 0, max: 300});
		$("#hop_time_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$('#hop_tr_' + rid).click(function() {
			var prev = $('#hop-table').data('selected_tr');
			if (prev) {
				$('#' + prev).css("backgroundColor", "");
			}
			$('#' + this.id).css("backgroundColor", "#dddddd");
			$('#hop-table').data('selected_tr', this.id);
		});
		$('#hop-table').data('last_tr', rid + 1);
		createHopList(rid);
		if (values) {
			$("#hop_weight_" + rid).val(values["hop_weight"]);
			$("#hop_alpha_" + rid).val(values["hop_alpha"]);
			$("#hop_time_" + rid).val(values["hop_time"]);
			$("#hop-list_" + rid).val(values["hop_name"]);
			$("#hop_use_" + rid).val(values["hop_use"]);
			$("#hop_form_" + rid).val(values["hop_form"]);
		}
	}
	function createYeastList(id) {
		$('#yeast-list_' + id).editableSelect({bg_iframe: false, onSelect: function(list_item) {
				var sItem = $('#yeast-list_' + id).editableSelect("getSelectedItem");
				if (sItem.yeast_attenuation) {
					there_are_changes = true;
					$('#attenuation').attr('value', sItem.yeast_attenuation);
					calc();
				}
			}, onFocus: function() {
				$('#yeast_tr_' + id).click();
			}});
		//alert($('#malt-list_'+id).editableSelect('getInstance'))
	}
	function createYeastsTr(values) {
		var rid = $('#yeast-table').data('last_tr');
		if (!rid) {
			var rid = 0;
		}
		// ********************************************************************************************************************************
		$("#yeasts_template .yeast_tr").attr("id", "yeast_tr_" + rid);
		$("#yeasts_template .yeast_weight").attr("id", "yeast_weight_" + rid);
		$("#yeasts_template .yeast_list").attr("id", "yeast-list_" + rid);
		$("#yeasts_template .yeast_list").html(getYeasts());
		$('#yeast-table').append($("#yeasts_template").html());

		$("#yeast_weight_" + rid).spinner({min: 0});
		$("#yeast_weight_" + rid).bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$('#yeast_tr_' + rid).click(function() {
			var prev = $('#yeast-table').data('selected_tr');
			if (prev) {
				$('#' + prev).css("backgroundColor", "");
			}
			$('#' + this.id).css("backgroundColor", "#dddddd");
			$('#yeast-table').data('selected_tr', this.id);
		});
		$('#yeast-table').data('last_tr', rid + 1);
		createYeastList(rid);
		if (values) {
			$("#yeast_weight_" + rid).val(values["yeast_weight"]);
			$("#yeast-list_" + rid).val(values["yeast_name"]);
		}
	}
	function fitTo(l) {
		if (l * 1 > 0) {
			there_are_changes = true;
			var ratio = l / $("#bash_size").val();
			$('input[name=malt_weight]').each(function(index, value) {
				var o = $(value);
				o.val(Math.round((o.val() * ratio) * 1000) / 1000);
			});
			$('input[name=hop_weight]').each(function(index, value) {
				var o = $(value);
				o.val(Math.round((o.val() * ratio)));
			});
			$('input[name=yeast_weight]').each(function(index, value) {
				var o = $(value);
				o.val(Math.round((o.val() * ratio)));
			});
			$("#bash_size").val(l);
			there_are_changes = true;
			calc();
		}
	}

	//
	$(document).ready(function() {
		$("#comments").keyup(function() {
			there_are_changes = true;
		});
		$(".ttip_efektyvumas").simpletip({
			content: '<b>Efektyvumas</b> (angl. <i>Efficiency</i>; <i>Extraction efficiency</i>). Cukringų medžiagų "išplovimo" iš salyklo efektyvumas. Tai yra santykis cukraus, kurį iš tikrųjų "išplovėt" , su teoriškai didžiausiu įmanomu "išplauti" cukraus kiekiu.',
			fixed: false
		});
		$(".ttip_atenuacija").simpletip({
			content: '<b>Atenuacija</b>, <b>silpimas</b> (angl. <i>Attenuation</i>). Misos tirštumo mažėjimas, joje esančias cukringąsias medžiagas fermentacijos būdu perdirbant į alkoholį ir angliarūgštę. Alus laikomas pasiekęs galutinę atenuaciją, kai mielės daugiau nebegali fermentuoti saldžiųjų medžiagų.<br /><br /><b>Tariama atenuacija</b> (angl. <i>Apparent attenuation</i>). Paprastas fermentacijos, kurią patyrė misa virsdama alumi, lygio išraiškos būdas. Naudojant Gravity Units (GU), Balling (B) arba Plato (P) vienetus išreikšti tirštumui, tariama atenuacija yra lygi iš pradinio tirštumo atėmus galutinį tirštumą ir padalinus iš pradinio tirštumo. Rezultatas išreiškiamas procentais ir daugumai alaus rūšių yra lygus 65-80%.',
			fixed: false
		});
		$(".ttip_matavimosistema").simpletip({
			content: '<b>Matavimo systema</b>. Misos tirštumo, potencialaus alaus stiprumo po fermentacijos, matavimo sistema.<br /><br /><b>°Plato</b>, <b>Balingas</b>, <b>°Balling</b>. Misos tirštumo, taigi ir potencialaus alaus stiprumo po fermentacijos, mato vienetas. Balling matavimo sistema buvo sukurta čeko aludarystės mokslininko Carl Joseph Napoleon Balling. Vėliau patobulinta į °Plato.<br /><br /><b>Specifinis tirštumas</b>, <b>cukringumas</b> (angl. <i>specific gravity</i>, <i>SG</i>). Misos matas, nurodantis jos tirštumą (kietųjų medžiagų kiekį).',
			fixed: false
		});
		$(".ttip_og").simpletip({
			content: '<b>Pradinis tirštumas</b> (angl. <i>original gravity</i>, <i>OG</i>). Misos specifinis tirštumas prieš fermentaciją. Šis matas nurodo cukringųjų medžiagų, būsiančių perdirbtų į alkoholį, kiekį – kuo tirštesnė misa, tuo stipresnis alus gausis.',
			fixed: false
		});
		$(".ttip_fg").simpletip({
			content: '<b>Galutinis tirštumas</b> (angl. <i>final gravity</i>, <i>FG</i>). Misos specifinis tirštumas fermentacijos pabaigoje.',
			fixed: false
		});
		$(".ttip_abv").simpletip({
			content: '<b>Alkoholio kiekis pagal tūrį</b> (angl. <i>Alcohol By Volume</i>, <i>ABV</i>, <i>v/v</i>). Alaus stiprumas išreiškiamas procentais.',
			fixed: false
		});
		$(".ttip_ibu").simpletip({
			content: '<b>Kartumo vienetai</b> (angl. <i>International Bittering Units</i>, <i>IBU</i>). Standartinis alaus kartumo matavimo skalės vienetas, žymintis apynių apimtį ir intensyvumą.',
			fixed: false
		});
		$(".ttip_ebc").simpletip({
			content: '<b>Spalva</b> (angl. <i>EBC</i>). Šiuo atveju alaus spalvos standartas pagal European Brewery Convention (Europos Aludarių Konvencija)',
			fixed: false
		});
		$(".ttip_ibuog").simpletip({
			content: '<b>IBU/OG balansas</b> (angl. <i>IBU/Gravity ratio</i>). Kartumo ir pradinio tirštumo santykis. Išskaičiuojamas, sąlyginis vienetas apsprendžiantis tariamą burnos kartumo pojūtį.',
			fixed: false
		});
		$(".ttip_ekstraktingumas").simpletip({
			content: '<b>Ekstraktingumas</b> (tech) (angl. <i>extraction rate</i>). Kramolingųjų medžiagų kiekio, paverstų į fermentuojamąsias cukringąsias medžiagas salinimo metu, matas.',
			fixed: false
		});
		$(".ttip_alfa").simpletip({
			content: '<b>Alfa rūgštys</b> (angl. <i>alpha acids</i>, <i>AA</i>). Esminis kartumo šaltinis, gaunamas iš apynių, izomerizuojant juos virimo būdu.',
			fixed: false
		});

		$("#attenuation").spinner({min: 0, stepping: 0.01, max: 1});
		$('#attenuation').bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();

		});
		$("#efficiency").spinner({min: 0, stepping: 0.01, max: 1});
		$('#efficiency').bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#boil_time").spinner({min: 0});
		$('#boil_time').bind('spinchange', function(event, ui) {
			there_are_changes = true;
		});
		$("#bash_size").spinner({min: 0, stepping: 0.5});
		$('#bash_size').bind('spinchange', function(event, ui) {
			there_are_changes = true;
			calc();
		});
		$("#beer_style").change(function() {
			beer_style_change();
		});
		// malt
		$("#add-malt-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			selectMalt(createMaltTr());
			calc();
		});
		$("#rem-malt-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			var selItem = $('#malt-table').data('selected_tr');
			$('#' + selItem).remove();
			calc();
		});
		// hops
		$("#add-hop-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			createHopTr();
			calc();
		});
		$("#rem-hop-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			var selItem = $('#hop-table').data('selected_tr');
			$('#' + selItem).remove();
			calc();
		});
		// yeasts
		$("#add-yeast-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			createYeastsTr();
			calc();
		});
		$("#rem-yeast-btn").bind('click', function(event, ui) {
			there_are_changes = true;
			var selItem = $('#yeast-table').data('selected_tr');
			$('#' + selItem).remove();
			calc();
		});
		$("#beer_name").bind('change', function(event, ui) {
			beer_name_change();
		});
		function beer_name_change(trigger_changes) {
			trigger_changes = typeof trigger_changes !== 'undefined' ? trigger_changes : true;
			if (trigger_changes == true) {
				there_are_changes = true;
			}
			$("#beer_name").addClass("formloader");
			var dis = ($("#beer_name").val().length > 0) ? '' : 'disabled';
			$("#save").attr("disabled", dis);
			if (dis.length > 0) {
				$("#beer_name").css('border-color', '#FF0000');
			} else {
				$("#beer_name").css('border-color', '#CCCCCC');
			}
			$.ajax({
				type: 'POST',
				url: '/checkname',
				data: {
					recipe_name: $("#beer_name").val(),
					recipe_id: <?= (isset($this->data["recipe"]["recipe_id"])) ? $this->data["recipe"]["recipe_id"] : '0'; ?>
				},
				success: function(data) {
					$("#beer_name").removeClass("formloader");
					if (data != "0") {
						$("#unique_ph").show();
					} else {
						$("#unique_ph").hide();
					}
				}
			});
		}
		$("#beer_name").bind('keyup', function(event, ui) {
			beer_name_change();
		});
		$('#duplicate').click(function() {
			if ($("#duplicate").attr("disabled")) {
				return false;
			}
			if (confirm("Ar tikrai norite dublikuoti receptą?")) {
				var surl = "/recipes/save/";
				$("#status_div")[0].innerHTML = "<img src='/public/images/preload.gif'/>";
				$.ajax({type: 'POST', url: surl, data: calc_out("").serialize() + "&style_id=" + $("#beer_style option:selected").attr("style_id") + "&duplicate=true", success: function(d) {
						// alert(d)
						var data = jQuery.parseJSON(d);
						if (data) {
							if (data.status == "1") {
								if (data.errors[0].type == "authentication") {
									$("#status_div")[0].innerHTML = "Norėdami sukurti recepto kopiją turite  prisijungti";
									showLogin();
									return;
								}
							} else {
								if (data.data.recipe_id) {
									$("#recipe_id").attr("value", data.data.recipe_id);
									$("#status_div")[0].innerHTML = "<i>" + now() + "</i>  - '<a href='/recipes/view/" + data.data.recipe_id + "'>" + $("#beer_name").val() + "'</a> sukurta recepto kopija <a href='/brewer/recipes'>Mano receptuose</a>";
								}
							}
						} else {
						}
					}});
			}
		});
		$('#save').click(function() {
			var surl = "/recipes/save/";
			$("#status_div")[0].innerHTML = "<img src='/public/images/preload.gif'/>";
			$.ajax({type: 'POST', url: surl, data: calc_out("").serialize() + "&style_id=" + $("#beer_style option:selected").attr("style_id"), success: function(d) {
					// alert(d)
					var data = jQuery.parseJSON(d);
					if (data) {
						if (data.status == "1") {
							if (data.errors[0].type == "authentication") {
								$("#status_div")[0].innerHTML = "Norėdami išsaugoti receptą turite  prisijungti";
								showLogin();
								return;
							}
						} else {
							if (data.data.recipe_id) {
								$("#duplicate").removeAttr("disabled");
								$("#recipe_id").attr("value", data.data.recipe_id);
								$("#status_div")[0].innerHTML = "<i>" + now() + "</i>  - '<a href='/recipes/view/" + data.data.recipe_id + "'>" + $("#beer_name").val() + "'</a> receptas išsaugotas <a href='/brewer/recipes'>Mano receptuose</a>";
							}
						}
					} else {
					}
				}});
			there_are_changes = false;
		});
		$('#export').click(function() {
			calc_out("/index/print-recipe")[0].submit();
		});
		$('#extract_m_plato').click(function() {
			there_are_changes = true;
			calc();
			beer_style_change();
		});
		$('#extract_m_sg').click(function() {
			there_are_changes = true;
			calc();
			beer_style_change();
		});
		$('#cnv_recipe_btn').click(function() {
			fitTo($('#recalc').val())
		})
		beer_style_change(false);
		$("#duplicate").attr("disabled", "disabled");
<?
if (isset($this->data)) {
	if (isset($this->data["recipe"])) {
		?>
				setTimeout(function() {
					$("#duplicate").removeAttr("disabled")
				}, 500)
				$("#attenuation").val(<?= $this->data["recipe"]["recipe_attenuation"]; ?>);
				$("#efficiency").val(<?= $this->data["recipe"]["recipe_efficiency"]; ?>);
				$("#beer_name").val("<?= addslashes($this->data["recipe"]["recipe_name"]); ?>");
				$("#bash_size").val(<?= $this->data["recipe"]["recipe_batch"]; ?>);
				$("#boil_time").val(<?= $this->data["recipe"]["recipe_boiltime"]; ?>);
				$("#beer_style option[style_id='<?= $this->data["recipe"]["recipe_style"]; ?>']").attr("selected", "selected");
				$("#recipe_id").val(<?= $this->data["recipe"]["recipe_id"]; ?>);
				$("#comments").val(decodeURIComponent('<?= (str_replace("\n", "\\n", addslashes(rawurlencode($this->data["recipe"]["recipe_comments"])))); ?>'));
		<?
		if (isset($this->data["malt"])) {
			for ($i = 0; $i < count($this->data["malt"]); $i++) {
				?>
						createMaltTr(<?= Zend_Json::encode($this->data["malt"][$i]); ?>);
				<?
			}
		}
		if (isset($this->data["hops"])) {
			for ($i = 0; $i < count($this->data["hops"]); $i++) {
				?>
						createHopTr(<?= Zend_Json::encode($this->data["hops"][$i]); ?>);
				<?
			}
		}
		if (isset($this->data["yeast"])) {
			for ($i = 0; $i < count($this->data["yeast"]); $i++) {
				?>
						createYeastsTr(<?= Zend_Json::encode($this->data["yeast"][$i]); ?>);
				<?
			}
		}
		?>
				$("#status_div")[0].innerHTML = "<i>" + now() + "</i>  -  atidarytas receptas <a href='/recipes/view/<?= $this->data["recipe"]["recipe_id"]; ?>'>'<?= addslashes($this->data["recipe"]["recipe_name"]); ?>'</a>";
		<?
	} else {
		?>
				$("#status_div")[0].innerHTML = "<i>" + now() + "</i>  -  naujas receptas";
		<?
	}
}
?>
		setTimeout(calc, 500)
		setTimeout(beer_style_change(false), 500)
		beer_name_change(false);
	});

	function calc_out(url) {
		var fields = ["bash_size", "boil_time", "efficiency", "attenuation", "beer_name", "beer_style", "comments", "recipe_id"];
		var constants = ["recipe_sg", "recipe_fg", "recipe_abv", "recipe_ibu", "recipe_ebc"];
		var $f = $('<form></form>').attr({method: 'post', target: '_blank', action: url}).appendTo(document.body);
		var malt = $('#malt_form').serializeArray();
		var hops = $('#hops_form').serializeArray();
		var yeast = $('#yeast_form').serializeArray();
		for (var i = 0; i < fields.length; i++) {
			$('<input type="hidden" />').attr({name: fields[i], value: $('#' + fields[i]).val()}).appendTo($f);
		}
		for (var i = 0; i < constants.length; i++) {
			$('<input type="hidden" />').attr({name: constants[i], value: $('#' + constants[i]).val()}).appendTo($f);
		}
		var sel = $('#malt_form')[0].elements["malt_list"];
		if (sel) {
			sel = sel.length ? sel : [sel];
			for (var i = 0; i < sel.length; i++) {
				var e = $("#" + sel[i].id).editableSelect("getSelectedItem").malt_id;
				$('<input type="hidden" />').attr({name: 'malt_id[]', value: ((e == undefined) ? 0 : e)}).appendTo($f);
			}
		}
		var sel = $('#hops_form')[0].elements["hop_list"];
		if (sel) {
			sel = sel.length ? sel : [sel];
			for (var i = 0; i < sel.length; i++) {
				var e = $("#" + sel[i].id).editableSelect("getSelectedItem").hop_id;
				$('<input type="hidden" />').attr({name: 'hop_id[]', value: ((e == undefined) ? 0 : e)}).appendTo($f);
			}
		}
		var sel = $('#yeast_form')[0].elements["yeast_list"];
		if (sel) {
			sel = sel.length ? sel : [sel];
			for (var i = 0; i < sel.length; i++) {
				var e = $("#" + sel[i].id).editableSelect("getSelectedItem").yeast_id;
				$('<input type="hidden" />').attr({name: 'yeast_id[]', value: ((e == undefined) ? 0 : e)}).appendTo($f);
			}
		}
		for (var i = 0; i < malt.length; i++) {
			$('<input type="hidden" />').attr({name: malt[i].name + '[]', value: malt[i].value}).appendTo($f);
		}
		for (var i = 0; i < yeast.length; i++) {
			$('<input type="hidden" />').attr({name: yeast[i].name + '[]', value: yeast[i].value}).appendTo($f);
		}
		for (var i = 0; i < hops.length; i++) {
			$('<input type="hidden" />').attr({name: hops[i].name + '[]', value: hops[i].value}).appendTo($f);
		}
		return $f;
	}
</script>


<div class="calc_info_container">
	<input type="hidden" name="recipe_sg" id="recipe_sg" />
	<input type="hidden" name="recipe_fg" id="recipe_fg" />
	<input type="hidden" name="recipe_abv" id="recipe_abv" />
	<input type="hidden" name="recipe_ibu" id="recipe_ibu" />
	<input type="hidden" name="recipe_ebc" id="recipe_ebc" />
	<input type="hidden" name="recipe_id" id="recipe_id" value="" />

	<div style="margin-bottom: 20px;">
		<div id="status_div"></div>
		<div class="calc_actions">
			<input type="button" id="save" value="Saugoti" class="ui-button" />
			<input type="button" id="duplicate" value="Dublikuoti" class="ui-button" />
			<input type="button" id="export" value="Spausdinti" class="ui-button" />
		</div>
		<div class="clear"></div>
	</div>
	<div class="col_cont">
		<div class="beer_color_container">
			<div id="beer_color" style="background-color: rgb(255, 255, 255);">
				<img src="/public/images/glass.png" />
			</div>
			<div class="clear"></div>
		</div>
		<div class="coli_cont">
			<div class="calc_info_block">
				<div class="calc_info_label">Pavadinimas:</div>
				<div class="calc_info_data"><input type="text" id="beer_name" value="" /></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block" id="unique_ph" style="display: none;">
				<div class="calc_info_label">&nbsp;</div>
				<div class="calc_info_data" style="color: #ff0000">Receptas tokiu pavadinimu jau egzistuoja</div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block" style="margin-bottom: 10px;">
				<div class="calc_info_label">Stilius:</div>
				<div class="calc_info_data">
					<select name="beer_style" id="beer_style" class="editable-select">
						<?
						for ($i = 0; $i < count($this->styles); $i++) {
							if ($this->styles[$i]['style_id'] == 41) {
								?>
								<option selected style_id="<?= $this->styles[$i]['style_id']; ?>" style_oglow="<?= $this->styles[$i]['style_oglow']; ?>" style_oghigh="<?= $this->styles[$i]['style_oghigh']; ?>"  style_fglow="<?= $this->styles[$i]['style_fglow']; ?>" style_fghigh="<?= $this->styles[$i]['style_fghigh']; ?>" style_ibulow="<?= $this->styles[$i]['style_ibulow']; ?>" style_ibuhigh="<?= $this->styles[$i]['style_ibuhigh']; ?>" style_srmlow="<?= $this->styles[$i]['style_srmlow']; ?>" style_srmhigh="<?= $this->styles[$i]['style_srmhigh']; ?>"><?= $this->styles[$i]['style_name']; ?></option>
								<?
							} else {
								?>
								<option style_id="<?= $this->styles[$i]['style_id']; ?>" style_oglow="<?= $this->styles[$i]['style_oglow']; ?>"	style_oghigh="<?= $this->styles[$i]['style_oghigh']; ?>"  style_fglow="<?= $this->styles[$i]['style_fglow']; ?>" style_fghigh="<?= $this->styles[$i]['style_fghigh']; ?>" style_ibulow="<?= $this->styles[$i]['style_ibulow']; ?>" style_ibuhigh="<?= $this->styles[$i]['style_ibuhigh']; ?>" style_srmlow="<?= $this->styles[$i]['style_srmlow']; ?>" style_srmhigh="<?= $this->styles[$i]['style_srmhigh']; ?>"><?= $this->styles[$i]['style_name']; ?></option>
								<?
							}
						}
						?>
					</select>
				</div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_matavimosistema">Matavimo sistema</span>:</div>
				<div class="calc_info_data">
					<input type="radio" name="extract_m" value="plato" id="extract_m_plato" <?= ($this->use_plato === true) ? 'checked="checked"' : ''; ?>> <label for="extract_m_plato">Plato</label>
					<input type="radio" name="extract_m" value="sg" id="extract_m_sg" <?= ($this->use_plato !== true) ? 'checked="checked"' : ''; ?>> <label for="extract_m_sg">SG</label>
				</div>
				<div class="calc_info_label">Alaus kiekis:</div>
				<div class="calc_info_data"><input type="text" id="bash_size" value="20" /></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_og">OG</span>:</div>
				<div class="calc_info_data"><span id="recipe_sg_span" class="style_res">?</span><span id="style_sg" class="style_recom"></span></div>
				<div class="calc_info_label">Virimo laikas:</div>
				<div class="calc_info_data"><input type="text" id="boil_time" value="60"/></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_fg">FG</span>:</div>
				<div class="calc_info_data"><span id="recipe_fg_span" class="style_res">?</span><span id="style_fg" class="style_recom"></span></div>
				<div class="calc_info_label"><span class="ttip ttip_efektyvumas">Efektyvumas</span>:</div>
				<div class="calc_info_data"><input type="text" id="efficiency" value="0.70"/></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_abv">ABV</span>:</div>
				<div class="calc_info_data"><span id="recipe_abv_span" class="style_res">?</span><span id="style_abv" class="style_recom"></span></div>
				<div class="calc_info_label"><span class="ttip ttip_atenuacija">Atenuacija</span>:</div>
				<div class="calc_info_data"><input type="text" id="attenuation" value="0.75"/></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_ibu">IBU</span>:</div>
				<div class="calc_info_data"><span id="recipe_ibu_span" class="style_res">?</span><span id="style_ibu" class="style_recom"></span></div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_ebc">EBC</span>:</div>
				<div class="calc_info_data"><span id="recipe_ebc_span" class="style_res">?</span><span id="style_ebc" class="style_recom"></span></div>
				<div class="calc_info_label">Pritaikyti:</div>
				<div class="calc_info_data">
					<input type="text" id="recalc" value="20" onChange="fitTo(this.value)" >
					<input type="button" id="cnv_recipe_btn" value="Pritaikyti" class="ui-button ui-button-smaller" />
				</div>
				<div class="clear"></div>
			</div>
			<div class="calc_info_block smaller_block">
				<div class="calc_info_label"><span class="ttip ttip_ibuog">IBU/OG balansas</span>:</div>
				<div class="calc_info_data" style="font-size: 14px; line-height: 26px; width: 400px;"><div id="feel_container">-</div></div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="ing_block">
		<div class="ing_title">Salyklas</div>
		<div class="ing_dub">
			OG: <span class="og_ph">?</span> 
			FG: <span class="fg_ph">?</span> 
			ABV: <span class="abv_ph">?</span>
			EBC: <span class="ebc_ph">?</span>
			IBU: <span class="ibu_ph">?</span>
		</div>
		<div class="clear"></div>
	</div>
	<div class="calc_malts">
		<form id="malt_form" name="malt_form">
			<div id="malt-table" class="as-table">
				<div style="display: table-header-group" class="tbody">
					<div class="as-row">
						<div class="as-cell" style="width: 40px"></div>
						<div class="as-cell"><b>Salyklas</b></div>
						<div class="as-cell" style="width: 120px"><b>Kiekis (kg)</b></div>
						<div class="as-cell" style="width: 120px"><span class="ttip ttip_ekstraktingumas"><b>Ekstraktingumas</b></span></div>
						<div class="as-cell" style="width: 120px"><span class="ttip ttip_ebc"><b>Spalva (EBC)</b></span></div>
						<div class="as-cell" style="width: 90px"><b>Tipas</b></div>
					</div>
				</div>
				<div style="display: table-footer-group">
					<div class="as-row malt-totals">
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 40px;"></div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999;">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 120px" id="malt-totals"><b></b></div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 120px">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 120px">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 90px">&nbsp;</div>
					</div>
				</div>
			</div>
		</form>
		<div class="ing_actions">
			<input type="button" class="ui-button" id="add-malt-btn" value="Pridėti salyklą" />
			<input type="button" class="ui-button" id="rem-malt-btn" value="Pašalinti pažymėtą" />
		</div>
	</div>
	<div class="ing_block">
		<div class="ing_title">Apyniai</div>
		<div class="ing_dub">
			OG: <span class="og_ph">?</span> 
			FG: <span class="fg_ph">?</span> 
			ABV: <span class="abv_ph">?</span>
			EBC: <span class="ebc_ph">?</span>
			IBU: <span class="ibu_ph">?</span>
		</div>
		<div class="clear"></div>
	</div>
	<div class="calc_hops">
		<form id="hops_form" name="hops_form">
			<div id="hop-table" class="as-table">
				<div style="display: table-header-group" class="tbody">
					<div class="as-row">
						<div class="as-cell"><b>Apyniai</b></div>
						<div class="as-cell" style="width: 80px"><b>Forma</b></div>
						<div class="as-cell" style="width: 110px"><b>Kiekis (gr.)</b></div>
						<div class="as-cell" style="width: 110px"><span class="ttip ttip_alfa"><b>Alfa (%)</b></span></div>
						<div class="as-cell" style="width: 120px"><b>Paskirtis</b></div>
						<div class="as-cell" style="width: 110px"><b>Laikas (min.)</b></div>
					</div>
				</div>
				<div style="display: table-footer-group">
					<div class="as-row" id="hop-total-tbl">
						<div class="as-cell" style="border: none; border-top: 2px solid #999;">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 80px">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 110px" id="hop-totals"><b></b></div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 110px">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 120px">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 110px">&nbsp;</div>
					</div>
				</div>
			</div>
		</form>
		<div class="ing_actions">
			<input type="button" class="ui-button" id="add-hop-btn" value="Pridėti apynius" />
			<input type="button" class="ui-button" id="rem-hop-btn" value="Pašalinti pažymėtą" />
		</div>
	</div>
	<div class="ing_block">
		<div class="ing_title">Mielės</div>
		<div class="ing_dub">
			OG: <span class="og_ph">?</span> 
			FG: <span class="fg_ph">?</span> 
			ABV: <span class="abv_ph">?</span>
			EBC: <span class="ebc_ph">?</span>
			IBU: <span class="ibu_ph">?</span>
		</div>
		<div class="clear"></div>
	</div>
	<div class="calc_yeasts">
		<form id="yeast_form" name="yeast_form">
			<div id="yeast-table" class="as-table">
				<div style="display: table-header-group" class="tbody">
					<div class="as-row">
						<div class="as-cell"><b>Mielės</b></div>
						<div class="as-cell" style="width: 120px;"><b>Kiekis (gr.)</b></div>
					</div>
				</div>
				<div style="display: table-footer-group">
					<div class="as-row" id="yeast-total-tbl">
						<div class="as-cell" style="border: none; border-top: 2px solid #999;">&nbsp;</div>
						<div class="as-cell" style="border: none; border-top: 2px solid #999; width: 120px" id="yeast-totals"><b></b></div>
					</div>
				</div>
			</div>
		</form>
		<div class="ing_actions">
			<input type="button" class="ui-button" id="add-yeast-btn" value="Pridėti mieles" />
			<input type="button" class="ui-button" id="rem-yeast-btn" value="Pašalinti pažymėtą" />
		</div>
	</div>
	<div class="ing_block">
		<div class="ing_title">Pastabos</div>
		<div class="clear"></div>
	</div>
	<div class="calc_notes">
		<textarea id="comments"></textarea>
	</div>
</div>


<div id="malts_template" style="display: none">
	<div class="malt_tr as-row">
		<div class="as-cell malt_perc"></div>
		<div class="as-cell">
			<select name="malt_list" class="editable-select malt_list"></select>
		</div>
		<div class="as-cell">
			<input type="text" value="1" name="malt_weight" class="malt_weight" />
		</div>
		<div class="as-cell">
			<input type="text" name="malt_extract" value="1.036" class="malt_extract" />
		</div>
		<div class="as-cell">
			<input type="text" name="malt_color" value="3" class="malt_color" />
		</div>
		<div class="as-cell">
			<select onchange="calc()" name="malt_type" class="malt_type">
				<option value="malt">Salyklas</option>
				<option value="extract">Ekstraktas</option>
				<option value="sugar">Cukrus</option>
			</select>
		</div>
	</div>	
</div>
<div id="hops_template" style="display: none">
	<div class="hop_tr as-row">
		<div class="as-cell">
			<select name="hop_list" class="editable-select hop_list"></select>
		</div>
		<div class="as-cell">
			<select name="hop_form" class="hop_form"></select>
		</div>
		<div class="as-cell">
			<input type="text" name="hop_weight" class="hop_weight" value="1" />
		</div>
		<div class="as-cell">
			<input type="text" name="hop_alpha" class="hop_alpha" value="1" />
		</div>
		<div class="as-cell">
			<select name="hop_use" class="hop_use"></select>
		</div>
		<div class="as-cell">
			<input type="text" name="hop_time" class="hop_time" value="60" />
		</div>
	</div>
</div>
<div id="yeasts_template" style="display: none">
	<div class="yeast_tr as-row">
		<div class="as-cell">
			<select name="yeast_list" class="editable-select yeast_list"></select>
		</div>
		<div class="as-cell">
			<input type="text" name="yeast_weight" class="yeast_weight" value="12">
		</div>
	</div>
</div>