<?php
$isloged = isset($this->user_data->user_id);
$mail_count = "?";
if ($isloged){
	$mail = new Entities_Mail($this->user_data);
	$mail_count = $mail->getUnreadCount();
	?>
	<div class="new_user_info_block">
		<div class="new_user_info_block_username">
			<a href="/brewers/<?=$this->user_data->user_id?>"><?=$this->user_data->user_name;?></a>
		</div>
		<div class="new_user_info_block_mail">
			<a href="/mail/inbox" title="Paštas">
				<?php
				if ($mail_count > 0){
					?>
					<span><?=$mail_count?></span>
					<?php
				}
				?>
			</a>
		</div>
		<div class="new_user_info_block_recipes" title="Mano receptai">
			<a href="/brewer/recipes"></a>
		</div>
		<div class="new_user_info_block_sessions" title="Mano virimai">
			<a href="/brew-session/brewer"></a>
		</div>
		<div class="new_user_info_block_favorites" title="Mėgstamiausi receptai">
			<a href="/brewer/favorites"></a>
		</div>
		<div class="new_user_info_block_settings" title="Paskyros nustatymai">
			<a href="/brewer/profile"></a>
		</div>
		<div class="new_user_info_block_logout" title="Atsijungti">
			<a href="/auth/logout"></a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<?php
} else {
	?> 
	<div id="user-login-links">
		<a href="#"  onclick="showLogin()">prisijungti </a> / <a href="/auth/register" style="font-weight:bold">registruotis</a>
	</div>
	<?php
}
?>
<div id="login-dialog"  title="Prisijungti" style="display:none">
	<form id="login-form" onsubmit="return false">
		<dl>
			<dt>El. paštas:</dt>
			<dd><input type="text" name="user_email" /></dd>
			<div class="clear"></div>
		</dl>
		<dl>
			<dt>Slaptažodis:</dt>
			<dd><input type="password" name="user_password" /></dd>
			<div class="clear"></div>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd><input type="checkbox" name="remember" id="remember"/><label for="remember">prisiminti mane:</label></dd>
			<div class="clear"></div>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd><button id="login-button">Jungtis</button></dd>
			<div class="clear"></div>
		</dl>
	</form>
</div>
