<div class="ui-corner-all" style="background:#ffffff;padding:10">
<?$t_percents=round($this->total_styles_translated["count"]/$this->total_styles["count"]*100);?>
<div>Vertimai - <?=$t_percents;?>%<br/>

<div style="width:100;height:12;border:1px #666666 solid;background:white" align="left"><div style="width:<?=$t_percents;?>;height:10;border:1px #666666 solid;background:green"></div></div>
</div>
<?$p_percents=100;?>
<div>Programavimas - <?=$p_percents;?>%<br/>
<div style="width:100;height:12;border:1px #666666 solid;background:white" align="left"><div style="width:<?=$p_percents;?>;height:10;border:1px #666666 solid;background:green"></div></div>
</div>
<?$g_percents=88;?>
<div>Grafiniai resursai - <?=$g_percents;?>%<br/>
<div style="width:100;height:12;border:1px #666666 solid;background:white" align="left"><div style="width:<?=$g_percents;?>;height:10;border:1px #666666 solid;background:green"></div></div>
</div>
</div>
