<div class="randomstat_title"><?=$this->title;?></div>
<?php
$max = round($this->statistics[0]["data"]);
for ($i=0; $i<count($this->statistics); $i++) {
	?>
	<div class="randomstat_data"><?=($i+1).". ".$this->statistics[$i]["label"] ." (".$this->statistics[$i]["data"] .")" ;?></div>
	<div style="width:<?=round($this->statistics[$i]["data"]/$max*80);?>%;" class="progressbar"></div>
	<?php
}
?>
