<?php 
if (!isset($this->options['plain'])) { 
	?>
	<div class="rc_title">
		<a href="/alus/receptas/<?= $this->item['recipe_id']; ?>-<?= $this->escapeParam($this->item['recipe_name']); ?>">
			<? print $this->item['recipe_name']; ?>
		</a>
	</div>
	<?php 
} else { 
	?>
	<div class="rc_title">
		<? print $this->item['recipe_name']; ?>
	</div>
	<?php 
} ?>
<div class="rc_item">
	<div style="background-color:<?= $this->hex; ?>" class="rc_image">
		<img src="/public/images/glass_s.png" />
	</div>
	<div class="rc_info">
		<div>
			Tipas: 
			<? print $this->item['recipe_type'] == "grain" ? "Iš salyklo" : "Iš ekstrakto"; ?>
		</div>
		<?php 
		if (!isset($this->options['plain'])) { 
			?>
			<div>
				Stilius: 
				<a href="/stilius/<? print $this->item['recipe_style']; ?>">
					<? print $this->item['style_name']; ?>
				</a>
			</div>
			<?php 
		} else { 
			?>
			<div>
				Stilius: 
				<? print $this->item['style_name']; ?>
			</div>
			<?php 
		} 
		if (!isset($this->options['without_brewer'])) { 
			if (!isset($this->options['plain'])) { 
				?>
				<div>
					Aludaris: 
					<a href="/brewers/<? print $this->item['brewer_id']; ?>">
						<? print $this->item['user_name']; ?>
					</a>
				</div>
				<?php 
			} else { 
				?>
				<div>
					Aludaris: 
					<? print $this->item['user_name']; ?>
				</div>
				<?php 
			} 
		}
		?>
		<div>
			ABV: 
			<? print $this->item['recipe_abv']; ?>%
		</div>
		<div>
			IBU: 
			<? print $this->item['recipe_ibu']; ?>
		</div>
		<? if (!empty($this->item['recipe_awards']) && !isset($this->options['without_awards'])) : ?>
			<div style="padding-top: 5px;">
				<?
				$awards = explode("\n", trim($this->item['recipe_awards']));
				foreach ($awards as $award_string):
					$award = explode("#", $award_string);
					?>
					<img src="/public/images/<?= trim($award[0]) ?>-32_grey.gif" width="32" title="<?= trim($award[1]) ?>" />
					<?
				endforeach;
				?>
			</div>
		<? endif; ?>
	</div>
	<div class="clear"></div>
</div>