<div class="rct_block">
	<div style="background-color:<?=$this->hex;?>" class="rct_image">
		<img src="/public/images/glass_thumb.png" alt="<? print $this->item['recipe_name'];?>" />
	</div>
	<div class="rct_info">
		<div style="margin-top: 5px;">
			<h2>
				<a href="/alus/receptas/<?=$this->item['recipe_id'];?>-<?=$this->urlMaker($this->item['recipe_name']);?>" style="font-size: 14px;">
					<b>
						<? print $this->item['recipe_name'];?>
					</b>
				</a> 
			</h2>
			(<a href="/stilius/<? print $this->item['recipe_style'];?>"><? print $this->item['style_name'];?></a>)
			<?php 
			if(!isset($this->options['without_brewer'])){ 
				?>
				-
				<a href="/brewers/<? print $this->item['brewer_id'];?>" style="font-weight: bold;">
					<? print $this->item['user_name'];?>
				</a>
				<?php 
			}
			if ($this->item['recipe_total_awards'] > 0) : ?>
				<?
				$awards = $this->awards[$this->item['recipe_id']];
				if (isset($awards) && is_array($awards) && sizeof($awards) > 0){
					foreach ($awards as $key=>$val):
						$title = $val['event_name'];
						if (!empty($val['category'])){
							$title .= ", ".$val['category'];
						}
						if (!empty($val['place'])){
							$title .= ", ".$val['place']." vieta";
						}
						if (!empty($val['points']) && $val['points'] != "0"){
							$title .= " (".$val['points']." tšk.)";
						}
						?>
						<img src="/public/images/<?= trim($val['icon']) ?>-32_grey.gif" width="32" title="<?= trim($title) ?>" style="float: right;" />
						<?
					endforeach;
				}
			endif; ?>
		</div>
		<div style="margin-top: 10px;">
			ABV:
			<? print $this->item['recipe_abv'];?>%
			IBU:
			<? print $this->item['recipe_ibu'];?>
			EBC:
			<? print $this->item['recipe_ebc'];?>
			<span class="total_comments" style="margin-left: 10px;"><?=$this->item['recipe_total_comments']?></span>
			<span class="total_likes"><?=$this->item['recipe_total_likes']?></span>
			<span class="total_sessions"><?=$this->item['recipe_total_sessions']?></span>
			<span class="total_viewed"><?=$this->item['recipe_viewed']?></span>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>