<table><tr valign="top">
<td rowspan="2" style="padding-right:9"><div style="height:50px;width:26px;background-color:<?=$this->hex;?>"><img src="/public/images/glass_thumb.png" /></div></td>
<td>
<a href="/alus/receptas/<?=$this->item['recipe_id'];?>-<?=$this->escapeParam($this->item['recipe_name']);?>"><b><? print $this->item['recipe_name'];?></b></a> (<a href="/stilius/<? print $this->item['recipe_style'];?>"><? print $this->item['style_name'];?></a>)
</td>
<?php if(!isset($this->options['without_brewer'])){ ?>
<td nowrap="nowrap"> - <a href="/brewers/<? print $this->item['brewer_id'];?>"><b><? print $this->item['user_name'];?></b></a></td>
<?php } ?>
<? if (!empty($this->item['recipe_awards'])) :?>
	<td rowspan="2" nowrap="nowrap" style="padding-left: 5px;">
		<?
		$awards = explode("\n", $this->item['recipe_awards']);
		foreach ($awards as $award_string):
			$award = explode("#", $award_string);
			?>
			<img src="/public/images/<?=trim($award[0])?>-32.gif" width="32" title="<?=trim($award[1])?>" />
			<?
		endforeach;
		?>
	</td>
<? endif; ?>	



</tr>
<tr><td style="font-size:10;color:#666666" valign="top"><span>ABV:</span><span><? print $this->item['recipe_abv'];?>%</span> <span>IBU:</span><span><? print $this->item['recipe_ibu'];?></span> <span>EBC:</span><span><? print $this->item['recipe_ebc'];?></span></td></tr>
</table>

