
<script type="text/javascript">
ROWS_COUNT=<?=$this->twitter->rowsCount;?>;
REM_TWEET_URL = "/tweet/removetweet/";
ITEM_TWEET_URL= "/tweet/itemtweet/";
function removeTweet(id) {
$.post(REM_TWEET_URL,{id:id}, function(msg){	
	if(parseInt(msg)!=0){
		$('#tw-'+id).remove();
		$.post(ITEM_TWEET_URL,{sid:<?=$this->twitter->rowsCount;?>}, function(msg){
			if(parseInt(msg)!=0){
				$('ul.statuses li:last-child').after(msg);
			}
		});
		
	}	
	});
}
$(document).ready(function(){	
$('#addNewsBtn').bind('click', function() {
$('#addNewsBtn').qtip('api').set({
   'content.ajax.url': '/tweet/form/'
})});	
$('#addNewsBtn').qtip(
   {
      id: 'news', // Since we're only creating one modal, give it an ID so we can style it
      content: {
         text: '<img src="/public/images/load.gif">',
         title: {
            text: 'Pasidalink naujiena',
            button: true
         }
      },
     
      position: {
         my: 'center', // ...at the center of the viewport
         at: 'center',
         target: $(window),
      },
      show: {
         event: 'click', // Show it on click...
         solo: true, // ...and hide all other tooltips...
       
      },
 	style: { 
      
      classes:'ui-tooltip-wiki ui-tooltip-light ui-tooltip-shadow',
       width: { min: 500 },
      },
      hide: 'unfocus',
      
   })
   });
</script>
<div id="twitter-container">

<div id="tweet-timeline"><ul class="statuses">
	<?for($i=0;$i<count($this->twitterItems);$i++) {
		print $this->twitter->tweetItem($this->twitterItems[$i]);	
	}?>
	</ul>
</div>
<div align="right"><a href="#" id="addNewsBtn">Skelbk</a> | <a href="/tweet/all">Visi įrašai</a></div>
</div>
