<? $this->headLink()->appendStylesheet("/public/css/bubbles.css"); ?>
<? $this->headLink()->appendStylesheet("/public/ui/external/jquery.qtip.min.css"); ?>
<? $this->headScript()->appendFile("/public/ui/external/jquery.qtip.min.js");?>
<script type="text/javascript">
$(document).ready(function(){	
$('#addNewsBtn').bind('click', function() {
$('#addNewsBtn').qtip('api').set({
   'content.ajax.url': '/tweet/form/'
})});	
$('#addNewsBtn').qtip(
   {
      id: 'news', // Since we're only creating one modal, give it an ID so we can style it
      content: {
         text: '<img src="/public/images/load.gif">',
         title: {
            text: 'Pasidalink naujiena',
            button: true
         }
      },
     
      position: {
         my: 'center', // ...at the center of the viewport
         at: 'center',
         target: $(window),
      },
      show: {
         event: 'click', // Show it on click...
         solo: true, // ...and hide all other tooltips...
       
      },
 	style: { 
      
      classes:'ui-tooltip-wiki ui-tooltip-light ui-tooltip-shadow',
       width: { min: 500 },
      },
      hide: 'unfocus',
      
   })
   });
</script>
<div id="twitter-container">
<a href="#" id="addNewsBtn">oOooo OOOO Oooo OO:</a>
<div id="tweet-timeline"><ul class="statuses">
	<li>
	<a href="#"><img class="avatar" src="http://www.gravatar.com/avatar/1a16a695aa8dec6ed0826bda01dc27ad?rating=G&amp;size=48&amp;default=mm" border="0"/></a>
	<div class="tweetTxt">
      <strong><a href="#">demo</a></strong> asdasda123
	<div class="date">less than 5 seconds ago</div>
	</div>
	<div class="clear"></div>
	</li>
	<li>
	<a href="#"><img class="avatar" src="http://www.gravatar.com/avatar/1a16a695aa8dec6ed0826bda01dc27ad?rating=G&amp;size=48&amp;default=mm" border="0"/></a>
	<div class="tweetTxt">
	<strong><a href="#">demo</a></strong> asdasda123
	<div class="date">less than 5 seconds ago</div>
	</div>
	<div class="clear"></div>
	</li>
	<li>
	<a href="#"><img class="avatar" src="http://www.gravatar.com/avatar/1a16a695aa8dec6ed0826bda01dc27ad?rating=G&amp;size=48&amp;default=mm" border="0"/></a>
	<div class="tweetTxt">
	<strong><a href="#">demo</a></strong> asdasda123
	<div class="date">less than 5 seconds ago</div>
	</div>
	<div class="clear"></div>
	</li>
	</ul>
</div>
</div>