<?php
$this->headTitle()->headTitle("Alaus ".$this->beer['beer_display']." vertinimas");
?>
<?php
if ($this->beer['beer_votes_count'] < 1) {
	$offset = 130;
	$votes_avg = "";
} else {
	$votes_avg = round($this->beer['beer_votes_value'] / $this->beer['beer_votes_count'] / 10, 1);
	$offset = 130 - $votes_avg * 10;
	$offset = $offset - (floor($votes_avg) * 3 + 1);
}
?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#system_type").change(function(){
			if ($(this).val() == "simple"){
				$(".rate_simple_form").show();
				$(".rate_advanced_form").hide();
			} else {
				$(".rate_simple_form").hide();
				$(".rate_advanced_form").show();
			}
		});
	});
</script>
<div id="rate_container" class="inner_container">
	<div class="inner_header">Alaus "<?= $this->beer['beer_display'] ?>" vertinimas</div>
	<div style="text-align: right; margin-bottom: 10px;">
		<a href="/vertinimas/bravoras/<?= $this->beer['brewery_id'] ?>-<?= $this->urlMaker($this->beer['brewery_title']) ?>">
			&laquo; Atgal į alaus sąrašą
		</a>
	</div>
	<div class="ibrewery">
		<div class="ibrewery_image">
			<img src="/rate_images/beers/<?= $this->beer['beer_id'] ?>.jpg" />
		</div>
		<div class="ibrewery_info">
			<h1><?= $this->beer['beer_display'] ?></h1>
			<div><span>Alkoholio kiekis:</span> <?= $this->beer['beer_abv'] ?>%</div>
			<div><span>Stilius:</span> <a href="/vertinimas/stilius/<?= $this->beer['style_id'] ?>-<?= $this->urlMaker($this->beer['style_name']) ?>"><?= $this->beer['style_name'] ?></a></div>
			<div><span>Įvertinimų kiekis:</span> <?= $this->beer['beer_votes_count'] ?></div>
			<div class="brewery_rate_block" style="padding-left: 0px;">
				<div class="brewery_rate_bar" style="background-position: -<?= $offset ?>px 0px;"><img src="/public/images/rate.png" /></div>
				<div class="brewery_rate_text"><?= $votes_avg ?></div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="rate_form">
		<h1>Įvertinkite šį alų:</h1>
		<form action="/vertinimas/vertinti" method="post" id="rate_form">
			<?php
			$hide_simple = true;
			$hide_advanced = true;
			switch($this->system['system_type']){
				case "simple":
					$hide_simple = false;
					?>
					<input type="hidden" name="system_type" value="simple" />
					<?php
				break;
				case "advanced":
					$hide_advanced = false;
					?>
					<input type="hidden" name="system_type" value="advanced" />
					<?php
				break;
				case "combined":
					$hide_simple = false;
					$hide_advanced = false;
					?>
					<dl style="margin-bottom: 20px;">
						<dt>&nbsp;</dt>
						<dd>
							<select name="system_type" style="width: 575px;" id="system_type">
								<option value="simple">Supaprastinta vertinimo forma</option>
								<option value="advanced">Pilna vertinimo forma</option>
							</select>
						</dd>
						<div class="clear"></div>
					</dl>
					<?php
				break;
			}
			if ($hide_simple === false){
				?>
				<div class="rate_simple_form">
					<dl>
						<dt>Bendras įvertinimas: </dt>
						<dd>
							<select name="rate_simple_val">
								<option value="">---</option>
								<?php
								for ($i=0; $i<=$this->system['system_simple_max']; $i++){
									?>
									<option value="<?=$i?>"><?=$i?></option>
									<?php
								}
								?>
							</select>
						</dd>
						<?php
						if ($this->system['system_simple_comment'] == "1"){
							?>
							<dd>
								<textarea name="rate_simple_comment"></textarea>
							</dd>
							<?php
						}
						?>
						<div class="clear"></div>
					</dl>
					<dl>
						<dt>&nbsp;</dl>
						<dd>
							<input type="submit" name="submit" value="Vertinti" class="ui-button" />
						</dd>
						<div class="clear"></div>
					</dl>
				</div>
				<?php
			}
			if ($hide_advanced === false){
				?>
				<div class="rate_advanced_form" <?=($this->system['system_type'] == "combined") ? 'style="display: none;"' : '';?>>
					<?php
					if ($this->system['system_aroma_use'] == "1"){
						?>
						<dl>
							<dt>
								Aromatas: 
								<span>(0-<?=$this->system['system_aroma_max']?>)</span>
								<span>salyklas, apyniai, esteriai ir kt. aromatai</span>
							</dt>
							<dd>
								<select name="rate_aroma">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_aroma_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_aroma_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_aroma_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					if ($this->system['system_appearance_use'] == "1"){
						?>
						<dl>
							<dt>
								Išvaizda: 
								<span>(0-<?=$this->system['system_appearance_max']?>)</span>
								<span>spalva, skaidrumas, puta</span>
							</dt>
							<dd>
								<select name="rate_appearance">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_appearance_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_appearance_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_appearance_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					if ($this->system['system_taste_use'] == "1"){
						?>
						<dl>
							<dt>
								Skonis: 
								<span>(0-<?=$this->system['system_taste_max']?>)</span>
								<span>salyklas, apyniai, ferment. charakteris, balansas, finišas/poskonis ir kt.</span>
							</dt>
							<dd>
								<select name="rate_taste">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_taste_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_taste_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_taste_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					if ($this->system['system_body_use'] == "1"){
						?>
						<dl>
							<dt>
								Konsistencija: 
								<span>(0-<?=$this->system['system_body_max']?>)</span>
								<span>kūnas, karbonizacija, šiluma, kreminis, kt.</span>
							</dt>
							<dd>
								<select name="rate_body">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_body_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_body_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_body_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					if ($this->system['system_style_use'] == "1"){
						?>
						<dl>
							<dt>
								Atitikimas stiliui: 
								<span>(0-<?=$this->system['system_style_max']?>)</span>
								<span>ar atskleistos pagrindinės stiliaus savybės?</span>
							</dt>
							<dd>
								<select name="rate_style">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_style_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_style_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_style_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					if ($this->system['system_overall_use'] == "1"){
						?>
						<dl>
							<dt>
								Bendras įspūdis: 
								<span>(0-<?=$this->system['system_overall_max']?>)</span>
								<span>bendras gėrimo malonumas</span>
							</dt>
							<dd>
								<select name="rate_overall">
									<option value="">---</option>
									<?php
									for ($i=0; $i<=$this->system['system_overall_max']; $i++){
										?>
										<option value="<?=$i?>"><?=$i?></option>
										<?php
									}
									?>
								</select>
							</dd>
							<?php
							if ($this->system['system_overall_comment'] == "1"){
								?>
								<dd>
									<textarea name="rate_overall_comment"></textarea>
								</dd>
								<?php
							}
							?>
							<div class="clear"></div>
						</dl>
						<?php
					}
					?>
					<dl>
						<dt>&nbsp;</dl>
						<dd>
							<input type="submit" name="submit" value="Vertinti" class="ui-button" />
						</dd>
						<div class="clear"></div>
					</dl>
				</div>
				<?php
			}
			?>
		</form>
	</div>
</div>