<?php
$this->headTitle()->headTitle("Bravoro ".$this->brewery['brewery_title']." alaus vertinimas");
?>
<script type="text/javascript">
	$(document).ready(function() {
	});
</script>
<div id="rate_container" class="inner_container">
	<div class="inner_header">Bravoro "<?=$this->brewery['brewery_title']?>" alaus vertinimas</div>
	<div style="text-align: right; margin-bottom: 10px;">
		<a href="/vertinimas">
			&laquo; Atgal į bravorų sąrašą
		</a>
	</div>
	<div class="ibrewery">
		<div class="ibrewery_image">
			<img src="/rate_images/breweries/<?=$this->brewery['brewery_id']?>.jpg" />
		</div>
		<div class="ibrewery_info">
			<h1><?=$this->brewery['brewery_title']?></h1>
			<div><span>Šalis:</span> <?=$this->brewery['country_title']?></div>
			<div><span>Alaus rūšys:</span> <?=$this->brewery['brewery_beers_count']?></div>
			<?php
			if (isset($this->brewery['brewery_url']) && !empty($this->brewery['brewery_url'])){
				?>
				<div><span>Interneto svetainė:</span> <a href="<?=$this->brewery['brewery_url']?>" target="_blank"><?=$this->brewery['brewery_url']?></a></div>
				<?php
			}
			?>
			<div class="ibrewery_description"><?=str_replace("\n", "<br />", $this->brewery['brewery_description'])?></div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="brewery_list">
		<?php
		$i = 1;
		foreach($this->beers as $beer){
			if ($beer['beer_votes_count'] < 1){
				$offset = 130;
				$votes_avg = "";
			} else {
				$votes_avg = round($beer['beer_votes_value'] / $beer['beer_votes_count']/10, 1);
				$offset = 130-$votes_avg*10;
				$offset = $offset - (floor($votes_avg)*3+1);
			}
			?>
			<div class="brewery_item" data-id="<?=$beer['beer_id']?>">
				<div class="brewery_image">
					<img src="/rate_images/beers/<?=$beer['beer_id']?>.jpg" width="180" />
				</div>
				<div class="brewery_title">
					<a href="/vertinimas/alus/<?=$beer['beer_id']?>-<?=$this->urlMaker($beer['beer_display'])?>">
						<?=$beer['beer_title']?>
					</a>
				</div>
				<div class="brewery_info" style="margin-bottom: 2px;">
					<div><span>Alkoholio kiekis:</span> <?=$beer['beer_abv']?>%</div>
					<div><span>Stilius:</span> <a href="/vertinimas/stilius/<?=$beer['style_id']?>-<?=$this->urlMaker($beer['style_name'])?>"><?=$beer['style_name']?></a></div>
					<div><span>Įvertinimų kiekis:</span> <?=$beer['beer_votes_count']?></div>
				</div>
				<div class="brewery_rate_block">
					<div class="brewery_rate_bar" style="background-position: -<?=$offset?>px 0px;"><img src="/public/images/rate.png" /></div>
					<div class="brewery_rate_text"><?=$votes_avg?></div>
					<div class="clear"></div>
				</div>
			</div>
			<?php
			if ($i == 4){
				$i = 0;
				?>
				<div class="clear"></div>
				<?php
			}
			$i++;
		}
		?>
		<div class="clear"></div>
	</div>
	<?php
	if (sizeof($this->beers) > 0){
		?>
		<div>
			<?php echo $this->paginationControl($this->beers, 'Sliding', 'paginator/item.phtml'); ?>
		</div>
		<?
	}
	?>
	<div class="new_rate_link ui-state-highlight ui-corner-all">
		<a href="/vertinimas/naujas/<?=$this->brewery['brewery_id']?>">
			Sąraše nerandate norimo įvertinti šio gamintojo alaus? <span>Spauskite čia!</span>
		</a>
	</div>
</div>